<!--
  @crouton-generated
  @collection printqueues
  @layer sales
  @generated 2026-06-24

  ## AI Context
  - Form component for printqueues collection
  - Handles: create, update, delete actions
  - API endpoint: /api/teams/[id]/sales-printqueues
  - Zod schema: useSalesPrintqueues() composable
  - Fields: eventId, orderId, printerId, locationId, status, printData, printMode, errorMessage, retryCount, completedAt

  ## Common Modifications
  - Add field: Add UFormField in template, update schema in composable
  - Custom validation: Modify schema in composable
  - Custom field component: Use meta.component in schema JSON
  - Change layout: Modify CroutonFormLayout template slots

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonFormActionButton
    v-if="action === 'delete'"
    :action="action"
    :collection="collection"
    :items="items"
    :loading="loading"
    @click="handleSubmit"
  />

  <UForm
    v-else
    :schema="schema"
    :state="state"
    @submit="handleSubmit"
  >
    <CroutonFormLayout>
      <template #main>
      <div class="flex flex-col gap-4 p-1">
        <UFormField :label="t('sales.printqueues.fields.eventId', 'Event')" name="eventId" class="not-last:pb-4">
          <CroutonFormReferenceSelect
            v-model="state.eventId"
            collection="salesEvents"
            :label="t('sales.printqueues.fields.eventId', 'Event')"
          />
        </UFormField>
        <UFormField :label="t('sales.printqueues.fields.orderId', 'Order')" name="orderId" class="not-last:pb-4">
          <CroutonFormReferenceSelect
            v-model="state.orderId"
            collection="salesOrders"
            :label="t('sales.printqueues.fields.orderId', 'Order')"
          />
        </UFormField>
        <UFormField :label="t('sales.printqueues.fields.printerId', 'Printer')" name="printerId" class="not-last:pb-4">
          <CroutonFormReferenceSelect
            v-model="state.printerId"
            collection="salesPrinters"
            :label="t('sales.printqueues.fields.printerId', 'Printer')"
          />
        </UFormField>
        <UFormField :label="t('sales.printqueues.fields.locationId', 'Location')" name="locationId" class="not-last:pb-4">
          <CroutonFormReferenceSelect
            v-model="state.locationId"
            collection="salesLocations"
            :label="t('sales.printqueues.fields.locationId', 'Location')"
          />
        </UFormField>
        <UFormField :label="t('sales.printqueues.fields.status', 'Status')" name="status" class="not-last:pb-4">
          <UInput v-model="state.status" class="w-full" size="xl" />
        </UFormField>
        <UFormField :label="t('sales.printqueues.fields.printData', 'Print Data')" name="printData" class="not-last:pb-4">
          <UTextarea v-model="state.printData" class="w-full" size="xl" />
        </UFormField>
        <UFormField :label="t('sales.printqueues.fields.printMode', 'Print Mode')" name="printMode" class="not-last:pb-4">
          <UInput v-model="state.printMode" class="w-full" size="xl" />
        </UFormField>
        <UFormField :label="t('sales.printqueues.fields.errorMessage', 'Error Message')" name="errorMessage" class="not-last:pb-4">
          <UTextarea v-model="state.errorMessage" class="w-full" size="xl" />
        </UFormField>
        <UFormField :label="t('sales.printqueues.fields.retryCount', 'Retry Count')" name="retryCount" class="not-last:pb-4">
          <UInput v-model="state.retryCount" class="w-full" size="xl" />
        </UFormField>
        <UFormField :label="t('sales.printqueues.fields.completedAt', 'Completed At')" name="completedAt" class="not-last:pb-4">
          <UInput v-model="state.completedAt" class="w-full" size="xl" />
        </UFormField>
      </div>
      </template>

      <template #footer>
        <CroutonFormActionButton
          :action="action"
          :collection="collection"
          :items="items"
          :loading="loading"
        />
      </template>
    </CroutonFormLayout>
  </UForm>
</template>

<script setup lang="ts">
import type { SalesPrintqueueFormProps, SalesPrintqueueFormData } from '../../types'
import useSalesPrintqueues from '../composables/useSalesPrintqueues'

const props = defineProps<SalesPrintqueueFormProps>()
const { defaultValue, schema, collection } = useSalesPrintqueues()

// Field labels resolve through translations (team override → system → fallback)
const { t } = useT()

// Form layout configuration
const tabs = ref(false)



// Use new mutation composable for data operations
const { create, update, deleteItems } = useCollectionMutation(collection)

// useCrouton still manages modal state
const { close, loading } = useCrouton()

// Initialize form state with proper values (no watch needed!)
const initialValues = props.action === 'update' && props.activeItem?.id
  ? { ...defaultValue, ...props.activeItem }
  : { ...defaultValue }

// Draft state: seeded from defaults (required fields may start null/empty until
// the user fills them; the zod schema validates on submit), so cast the initial
// values to the validated shape.
const state = ref<SalesPrintqueueFormData & { id?: string | null }>(initialValues as SalesPrintqueueFormData & { id?: string | null })

const handleSubmit = async () => {
  try {
    if (props.action === 'create') {
      await create(state.value)
    } else if (props.action === 'update' && state.value.id) {
      await update(state.value.id, state.value)
    } else if (props.action === 'delete') {
      await deleteItems(props.items)
    }

    close()

  } catch (error) {
    console.error('Form submission failed:', error)
    // You can add toast notification here if available
    // toast.add({ title: 'Error', description: 'Failed to submit form', color: 'red' })
  }
}
</script>