<!--
  @crouton-generated
  @collection printqueues
  @layer sales
  @generated 2026-06-24

  ## AI Context
  - List component for printqueues collection
  - Collection name: salesPrintqueues
  - API endpoint: /api/teams/[id]/sales-printqueues
  - Columns composable: useSalesPrintqueues()
  - Column fields: eventId, orderId, printerId, locationId, status, printData, printMode, errorMessage, retryCount, completedAt

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="salesPrintqueues"
    :columns="columns"
    :rows="printqueues || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="SalesPrintqueues"
        :collection="'salesPrintqueues'"
        createButton
      />
    </template>
    <template #eventId-cell="{ row }">
      <CroutonItemCardMini
        v-if="row.original.eventId"
        :id="row.original.eventId"
        collection="salesEvents"
      />
    </template>
    <template #orderId-cell="{ row }">
      <CroutonItemCardMini
        v-if="row.original.orderId"
        :id="row.original.orderId"
        collection="salesOrders"
      />
    </template>
    <template #printerId-cell="{ row }">
      <CroutonItemCardMini
        v-if="row.original.printerId"
        :id="row.original.printerId"
        collection="salesPrinters"
      />
    </template>
    <template #locationId-cell="{ row }">
      <CroutonItemCardMini
        v-if="row.original.locationId"
        :id="row.original.locationId"
        collection="salesLocations"
      />
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import useSalesPrintqueues from '../composables/useSalesPrintqueues'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { columns } = useSalesPrintqueues()

const { items: printqueues, pending } = await useCollectionQuery(
  'salesPrintqueues'
)

</script>