import type { ProjectConfig } from '../types/schema'
import type { CollectionWithFields } from './useCollectionEditor'

interface ModuleAIContext {
  collections?: Array<{ name: string, description: string }>
  composables?: string[]
  components?: string[]
}

interface ModuleEntry {
  alias: string
  description: string
  layer?: { name: string; reason?: string }
  extensionPoints?: Array<{ collection: string; allowedFields: string[]; description: string }>
  configuration?: Record<string, { type: string; label: string; description?: string; default: unknown }>
  ai?: ModuleAIContext
}

/**
 * Builds the system prompt for Phase 2 (Collection Design)
 */
export function useCollectionDesignPrompt() {
  const { FIELD_TYPES, META_PROPERTIES } = useFieldTypes()
  const appConfig = useAppConfig()
  const crouton = appConfig.crouton as any ?? {}
  const allModules = (crouton.modules ?? []) as ModuleEntry[]
  const autoGeneratedFields: string[] = crouton.autoGeneratedFields ?? [
    'id', 'teamId', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy',
  ]

  function buildFieldTypeTable(): string {
    return FIELD_TYPES.map(ft =>
      `| ${ft.type} | ${ft.label} | ${ft.description} |`
    ).join('\n')
  }

  function buildMetaTable(): string {
    return META_PROPERTIES.map(mp =>
      `| ${mp.key} | ${mp.type} | ${mp.description} |`
    ).join('\n')
  }

  function buildPackageCollectionsContext(config: ProjectConfig): string {
    if (!config.packages?.length) return ''
    const blocks: string[] = []

    for (const pkgAlias of config.packages) {
      const mod = allModules.find(m => m.alias === pkgAlias)
      if (!mod) continue

      const pkgLines: string[] = [`### \`${mod.alias}\` package`]

      if (mod.ai?.collections?.length) {
        pkgLines.push('Built-in collections (already exist — **do not recreate**):')
        for (const col of mod.ai.collections) {
          pkgLines.push(`- \`${col.name}\`: ${col.description}`)
        }
      }

      if (mod.extensionPoints?.length) {
        pkgLines.push('Extension points (add custom fields here instead of a new collection):')
        for (const ep of mod.extensionPoints) {
          pkgLines.push(`- \`${ep.collection}\` — ${ep.description} (allowed fields: ${ep.allowedFields.join(', ')})`)
        }
      }

      if (mod.configuration && Object.keys(mod.configuration).length) {
        const opts = Object.entries(mod.configuration)
          .map(([k, v]) => `\`${k}\` (${v.label}${v.description ? `: ${v.description}` : ''})`)
          .join(', ')
        pkgLines.push(`Package config options: ${opts}`)
      }

      if (mod.ai?.composables?.length) {
        pkgLines.push(`Provides composables: ${mod.ai.composables.slice(0, 5).join(', ')}${mod.ai.composables.length > 5 ? ` +${mod.ai.composables.length - 5} more` : ''}`)
      }

      blocks.push(pkgLines.join('\n'))
    }

    if (blocks.length === 0) return ''

    return `\n## Selected Package Capabilities (DO NOT RECREATE THESE COLLECTIONS)
The user has selected these packages. Each package already ships with its own collections, APIs, and UI.
Your job is to design **custom collections that complement the packages** — not duplicate what they provide.
If the user needs functionality already covered by a package (e.g. page management, bookings), tell them — don't create a redundant collection.

${blocks.join('\n\n')}
`
  }

  function buildCollectionsContext(collections: CollectionWithFields[]): string {
    if (collections.length === 0) return '  (no collections yet)'
    return collections.map(col => {
      const displayLine = col.display
        ? `    display: ${JSON.stringify(col.display)}`
        : '    display: (not set)'
      const fieldLines = col.fields.map(f => {
        const meta = f.meta ? ` meta: ${JSON.stringify(f.meta)}` : ''
        const ref = f.refTarget ? ` → ${f.refTarget}` : ''
        return `    - ${f.name}: ${f.type}${ref}${meta} (id: ${f.id})`
      }).join('\n')
      return `  ${col.name} (id: ${col.id}):\n${displayLine}\n${fieldLines || '    (no fields)'}`
    }).join('\n')
  }

  function buildSystemPrompt(
    config: ProjectConfig,
    collections: CollectionWithFields[]
  ): string {
    const fieldTypes = FIELD_TYPES.map(ft => ft.type).join(', ')

    return `You are a senior full-stack developer helping design data collections for a Nuxt Crouton application. You are in Phase 2: Collection Design.

## App Context
- Name: ${config.name || 'unnamed'}
- Type: ${config.appType || 'unknown'}
- Description: ${config.description || 'none'}
- Multi-tenant: ${config.multiTenant ?? 'unknown'}
- Auth: ${config.authType || 'unknown'}
- Languages: ${config.languages?.join(', ') || 'en'}
- Packages: ${config.packages?.join(', ') || 'none'}
${buildPackageCollectionsContext(config)}
## Available Field Types
| Type | Label | Description |
|------|-------|-------------|
${buildFieldTypeTable()}

## Available Meta Properties
| Property | Type | Description |
|----------|------|-------------|
${buildMetaTable()}

## Additional Meta (set via tools, not shown in table)
- \`options\`: string[] — static options for select fields
- \`optionsCollection\` / \`optionsField\`: dynamic options from another collection
- \`readOnly\`: boolean — for reference fields, prevents editing
- \`dependsOn\` / \`dependsOnCollection\` / \`dependsOnField\`: field dependency chain
- \`component\`: string — custom Vue component name
- \`properties\`: object — nested fields for repeater type

## Current Collections
${buildCollectionsContext(collections)}

## Display Config
Every collection MUST have a \`display\` mapping that identifies which fields serve display roles.
Set this via the \`display\` parameter when calling \`create_collection\`. The mapping keys are:
- \`title\`: Primary identifier field (required — fall back to first string field named title/name/label)
- \`subtitle\`: Secondary context field (optional)
- \`image\`: Visual identifier field — only use image/file type fields (optional)
- \`badge\`: Status/category indicator field — use fields with options or displayAs:badge (optional)
- \`description\`: Summary text field (optional)

Values are field names (camelCase). Only reference fields that exist in the collection.
You know the domain — set this automatically, don't ask the user.

## Auto-Generated Fields (DO NOT CREATE THESE)
Crouton automatically adds the following fields to every collection. NEVER include them in your tool calls:
- ${autoGeneratedFields.join(', ')}
If you include any of these, they will be silently removed.

## Rules
1. ALWAYS use tool calls to create/modify/delete collections and fields. Always include display config when creating collections.
2. Be opinionated: propose complete, well-structured schemas. Don't ask "do you want X?" — propose X and let the user modify.
3. Start each collection with a \`name\` or \`title\` field as the first field. Do NOT add an \`id\` field — it is auto-generated.
4. Use \`reference\` type for relationships. Set \`refTarget\` to the target collection name.
5. Apply sensible meta defaults: mark title/name fields as required, add labels for human readability.
6. Use camelCase for field names (e.g., \`userId\`, \`isActive\`).
7. Use singular PascalCase for collection names when proposing, but the user may prefer any style.
8. Keep responses concise. After tool calls, briefly explain what you did and ask if adjustments are needed.
9. When proposing initial collections, create 3-6 collections that cover the core domain. Include relationships.
10. Suggest relevant Crouton packages inline when patterns match (e.g., rich text content → crouton-editor).
${config.packages?.includes('pages') ? '11. When the app uses crouton-pages: set `publishable: true` on collections whose items should have their own public URLs (e.g., blog posts, products, events). This auto-registers them as page types so editors can link items to pages with SEO and slug.' : ''}

## Tool Usage
- Use \`create_collection\` with initial fields to propose complete collections efficiently.
- Use \`add_field\` for adding individual fields to existing collections.
- Use \`update_field\` to modify fields — include the field ID.
- Use \`delete_field\` / \`delete_collection\` when user wants to remove items.
- Use \`reorder_fields\` to change field display order.
- Available field types: ${fieldTypes}

## Output Format
Call the appropriate tools, then provide a brief conversational message explaining what you did.`
  }

  return { buildSystemPrompt }
}
