/**
 * @crouton-generated
 * Collection Type Registry
 *
 * This file is auto-generated by @fyit/crouton-cli
 * Run `crouton sync-types` to regenerate after adding collections.
 *
 * Generated: 2026-06-15
 *
 * ## How This Works
 * This file augments the CollectionTypeMap interface from @crouton/types.
 * When you use useCollectionQuery('blogPosts'), TypeScript automatically
 * knows the return type is BlogPost[] without requiring explicit generics.
 *
 * ## Registered Collections
 * - bookingsBookings: BookingsBooking
 * - bookingsLocations: BookingsLocation
 * - bookingsSettings: BookingsSetting
 * - mainItems: MainItem
 */

import type { BookingsBooking, BookingsBookingFormData, NewBookingsBooking } from './layers/bookings/collections/bookings/types'
import type { BookingsLocation, BookingsLocationFormData, NewBookingsLocation } from './layers/bookings/collections/locations/types'
import type { BookingsSetting, BookingsSettingFormData, NewBookingsSetting } from './layers/bookings/collections/settings/types'
import type { MainItem, MainItemFormData, NewMainItem } from './layers/main/collections/items/types'

declare module '#crouton/types' {
  interface CollectionTypeMap {
    bookingsBookings: {
      Item: BookingsBooking
      FormData: BookingsBookingFormData
      NewItem: NewBookingsBooking
    }
    bookingsLocations: {
      Item: BookingsLocation
      FormData: BookingsLocationFormData
      NewItem: NewBookingsLocation
    }
    bookingsSettings: {
      Item: BookingsSetting
      FormData: BookingsSettingFormData
      NewItem: NewBookingsSetting
    }
    mainItems: {
      Item: MainItem
      FormData: MainItemFormData
      NewItem: NewMainItem
    }
  }
}

export {}
