<!--
  @crouton-generated
  @collection workitems
  @layer thinkgraph
  @generated 2026-03-19

  ## AI Context
  - List component for workitems collection
  - Collection name: thinkgraphWorkItems
  - API endpoint: /api/teams/[id]/thinkgraph-workitems
  - Columns composable: useThinkgraphWorkItems()
  - Column fields: projectId, parentId, title, type, status, brief, output, assignee, provider, sessionId, worktree, deployUrl, skill, artifacts

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="thinkgraphWorkItems"
    :columns="columns"
    :rows="workitems || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="ThinkgraphWorkItems"
        :collection="'thinkgraphWorkItems'"
        createButton
      />
    </template>
    <template #projectId-cell="{ row }">
      <CroutonItemCardMini
        v-if="row.original.projectId"
        :id="row.original.projectId"
        collection="thinkgraphProjects"
      />
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import useThinkgraphWorkItems from '../composables/useThinkgraphWorkItems'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { columns } = useThinkgraphWorkItems()

const { items: workItems, pending } = await useCollectionQuery(
  'thinkgraphWorkItems'
)

</script>