/**
 * @crouton-generated
 * Collection Type Registry
 *
 * This file is auto-generated by @friendlyinternet/nuxt-crouton-cli
 * Run `crouton sync-types` to regenerate after adding collections.
 *
 * Generated: 2025-12-22
 *
 * ## How This Works
 * This file augments the CollectionTypeMap interface from @crouton/types.
 * When you use useCollectionQuery('blogPosts'), TypeScript automatically
 * knows the return type is BlogPost[] without requiring explicit generics.
 *
 * ## Registered Collections
 * - knowledgeBaseNotes: KnowledgeBaseNote
 * - projectManagementProjects: ProjectManagementProject
 * - projectManagementTasks: ProjectManagementTask
 */

import type { KnowledgeBaseNote, KnowledgeBaseNoteFormData, NewKnowledgeBaseNote } from './layers/knowledge-base/collections/notes/types'
import type { ProjectManagementProject, ProjectManagementProjectFormData, NewProjectManagementProject } from './layers/project-management/collections/projects/types'
import type { ProjectManagementTask, ProjectManagementTaskFormData, NewProjectManagementTask } from './layers/project-management/collections/tasks/types'

declare module '#crouton/types' {
  interface CollectionTypeMap {
    knowledgeBaseNotes: {
      Item: KnowledgeBaseNote
      FormData: KnowledgeBaseNoteFormData
      NewItem: NewKnowledgeBaseNote
    }
    projectManagementProjects: {
      Item: ProjectManagementProject
      FormData: ProjectManagementProjectFormData
      NewItem: NewProjectManagementProject
    }
    projectManagementTasks: {
      Item: ProjectManagementTask
      FormData: ProjectManagementTaskFormData
      NewItem: NewProjectManagementTask
    }
  }
}

export {}
