/**
 * @crouton-generated
 * @collection notes
 * @layer knowledge-base
 * @generated 2025-12-22
 *
 * ## AI Context
 * - Composable: useKnowledgeBaseNotes
 * - Collection name: knowledgeBaseNotes
 * - API endpoint: /api/teams/[id]/knowledge-base-notes
 * - Form component: KnowledgeBaseNotesForm
 * - List component: KnowledgeBaseNotesList
 * - Fields: id, title, content, category, tags, isPinned
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @friendlyinternet/nuxt-crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

// Schema exported separately - Zod 4 schemas cannot survive deep cloning
// Keep schema outside of objects that might be serialized/cloned during SSR
export const knowledgeBaseNoteSchema = z.object({
  title: z.string().min(1, 'title is required'),
  content: z.string().optional(),
  category: z.string().optional(),
  tags: z.record(z.string(), z.any()).optional(),
  isPinned: z.boolean().optional()
})

export const knowledgeBaseNotesColumns = [
  { accessorKey: 'id', header: 'Id' },
  { accessorKey: 'title', header: 'Title' },
  { accessorKey: 'content', header: 'Content' },
  { accessorKey: 'category', header: 'Category' },
  { accessorKey: 'tags', header: 'Tags' },
  { accessorKey: 'isPinned', header: 'IsPinned' }
]

// Config object WITHOUT schema - safe for SSR serialization
const _knowledgeBaseNotesConfig = {
  name: 'knowledgeBaseNotes',
  layer: 'knowledge-base',
  apiPath: 'knowledge-base-notes',
  componentName: 'KnowledgeBaseNotesForm',
  defaultValues: {
    title: '',
    content: '',
    category: '',
    tags: {},
    isPinned: false
  },
  columns: knowledgeBaseNotesColumns,
  sortable: {
    enabled: true,
    orderField: 'order'
  },
}

// Add schema as non-enumerable property so klona skips it during cloning
Object.defineProperty(_knowledgeBaseNotesConfig, 'schema', {
  value: knowledgeBaseNoteSchema,
  enumerable: false,
  configurable: false,
  writable: false
})

export const knowledgeBaseNotesConfig = _knowledgeBaseNotesConfig as typeof _knowledgeBaseNotesConfig & { schema: typeof knowledgeBaseNoteSchema }

export const useKnowledgeBaseNotes = () => knowledgeBaseNotesConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: knowledgeBaseNotesConfig.defaultValues,
    schema: knowledgeBaseNoteSchema,
    columns: knowledgeBaseNotesConfig.columns,
    collection: knowledgeBaseNotesConfig.name
  }
}