// deploy-setup.ts — Interactive deployment setup for Cloudflare Pages
// Creates CF resources, updates wrangler config, generates CI workflow
// Run from inside the app directory: crouton deploy setup

import { execSync } from 'node:child_process'
import { join, relative } from 'node:path'
import { readFile, writeFile, mkdir, access } from 'node:fs/promises'
import * as p from '@clack/prompts'
import consola from 'consola'
import {
  parseAppConfig,
  getPackagesNeedingBuild,
  findMonorepoRoot,
} from './utils/parse-app-config.ts'
import { generateDeployWorkflow } from './templates/deploy-workflow.ts'

async function pathExists(path: string): Promise<boolean> {
  try {
    await access(path)
    return true
  } catch {
    return false
  }
}

interface DeploySetupOptions {
  dryRun?: boolean
  skipResources?: boolean
}

/**
 * Run a wrangler command and capture output
 */
function wrangler(args: string, cwd: string): string {
  try {
    return execSync(`npx wrangler ${args}`, { cwd, encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] })
  } catch (error: any) {
    throw new Error(`wrangler ${args.split(' ')[0]} failed: ${error.stderr || error.message}`)
  }
}

/**
 * Create a D1 database and return its ID
 */
function createD1(name: string, cwd: string): string | null {
  try {
    const output = wrangler(`d1 create ${name}`, cwd)
    const idMatch = output.match(/database_id\s*=\s*"?([a-f0-9-]+)"?/i)
      || output.match(/([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/)
    return idMatch?.[1] || null
  } catch (error: any) {
    // Database might already exist
    if (error.message.includes('already exists')) {
      consola.warn(`D1 database "${name}" already exists — skipping creation`)
      return null
    }
    throw error
  }
}

/**
 * Create a KV namespace and return its ID
 */
function createKv(name: string, cwd: string): string | null {
  try {
    const output = wrangler(`kv namespace create ${name}`, cwd)
    const idMatch = output.match(/id\s*=\s*"?([a-f0-9]+)"?/i)
      || output.match(/([a-f0-9]{32})/)
    return idMatch?.[1] || null
  } catch (error: any) {
    if (error.message.includes('already exists')) {
      consola.warn(`KV namespace "${name}" already exists — skipping creation`)
      return null
    }
    throw error
  }
}

/**
 * Create an R2 bucket
 */
function createR2(name: string, cwd: string): void {
  try {
    wrangler(`r2 bucket create ${name}`, cwd)
  } catch (error: any) {
    if (error.message.includes('already exists')) {
      consola.warn(`R2 bucket "${name}" already exists — skipping creation`)
      return
    }
    throw error
  }
}

/**
 * Update wrangler.toml with real resource IDs
 */
async function updateWranglerToml(
  appDir: string,
  updates: { d1Id?: string; kvId?: string; stagingD1Id?: string; stagingKvId?: string; withStaging: boolean },
): Promise<void> {
  const filePath = join(appDir, 'wrangler.toml')
  if (!await pathExists(filePath)) return

  let content = await readFile(filePath, 'utf-8')

  // Replace first placeholder ID with production D1
  if (updates.d1Id) {
    content = content.replace(/database_id\s*=\s*"TODO_REPLACE_WITH_REAL_ID"/, `database_id = "${updates.d1Id}"`)
  }

  // Replace KV placeholder
  if (updates.kvId) {
    content = content.replace(/id\s*=\s*"TODO_REPLACE_WITH_REAL_ID"/, `id = "${updates.kvId}"`)
  }

  await writeFile(filePath, content, 'utf-8')
}

/**
 * Generate wrangler.jsonc with env block for staging
 */
async function generateWranglerJsonc(
  appDir: string,
  appName: string,
  d1Id: string,
  kvId: string | null,
  r2Bucket: string | null,
  stagingD1Id: string | null,
  stagingKvId: string | null,
  stagingR2Bucket: string | null,
  withStaging: boolean,
): Promise<void> {
  const config: any = {
    name: appName,
    compatibility_date: '2024-09-02',
    compatibility_flags: ['nodejs_compat'],
    pages_build_output_dir: 'dist',
    d1_databases: [{
      binding: 'DB',
      database_name: `${appName}-db`,
      database_id: d1Id,
      migrations_dir: 'server/db/migrations/sqlite',
    }],
  }

  if (kvId) {
    config.kv_namespaces = [{ binding: 'KV', id: kvId }]
  }

  if (r2Bucket) {
    config.r2_buckets = [{ binding: 'BLOB', bucket_name: r2Bucket }]
  }

  if (withStaging) {
    const previewEnv: any = {
      d1_databases: [{
        binding: 'DB',
        database_name: `${appName}-staging-db`,
        database_id: stagingD1Id || 'TODO_SET_STAGING_DB_ID',
        migrations_dir: 'server/db/migrations/sqlite',
      }],
    }

    if (stagingKvId) {
      previewEnv.kv_namespaces = [{ binding: 'KV', id: stagingKvId }]
    }

    if (stagingR2Bucket) {
      previewEnv.r2_buckets = [{ binding: 'BLOB', bucket_name: stagingR2Bucket }]
    }

    config.env = { preview: previewEnv }
  }

  // Write as JSONC with comments
  const lines = [
    '// Cloudflare Pages configuration',
    `// Generated by: crouton deploy setup`,
    `// Deploy with: npx wrangler pages deploy dist/`,
    JSON.stringify(config, null, 2),
  ]

  await writeFile(join(appDir, 'wrangler.jsonc'), lines.join('\n') + '\n', 'utf-8')
}

// ── Main ───────────────────────────────────────────────────────────────

export async function deploySetup(appDir: string, options: DeploySetupOptions = {}): Promise<void> {
  const { dryRun = false, skipResources = false } = options
  const config = await parseAppConfig(appDir)
  const monorepoRoot = await findMonorepoRoot(appDir)

  if (!monorepoRoot) {
    consola.error('Could not find monorepo root (pnpm-workspace.yaml)')
    return
  }

  const appRelDir = relative(monorepoRoot, appDir)

  p.intro('Deploy Setup')

  // ── 1. Gather info ──────────────────────────────────────────────────

  const productionUrl = await p.text({
    message: 'Production URL',
    placeholder: `https://${config.name}.friendlyinter.net`,
    defaultValue: `https://${config.name}.friendlyinter.net`,
    validate: (v) => {
      if (!v.startsWith('https://')) return 'Must start with https://'
    },
  })

  if (p.isCancel(productionUrl)) {
    p.cancel('Setup cancelled')
    return
  }

  const withStaging = await p.confirm({
    message: 'Set up staging environment?',
    initialValue: true,
  })

  if (p.isCancel(withStaging)) {
    p.cancel('Setup cancelled')
    return
  }

  let stagingUrl: string | undefined
  let pagesProjectName: string | undefined

  if (withStaging) {
    pagesProjectName = await p.text({
      message: 'Cloudflare Pages project name (for staging URL)',
      placeholder: config.name,
      defaultValue: config.name,
    }) as string

    if (p.isCancel(pagesProjectName)) {
      p.cancel('Setup cancelled')
      return
    }

    stagingUrl = `https://staging.${pagesProjectName}.pages.dev`
  }

  // ── 2. Create Cloudflare resources ──────────────────────────────────

  let d1Id: string | null = null
  let kvId: string | null = null
  let stagingD1Id: string | null = null
  let stagingKvId: string | null = null

  if (!skipResources) {
    const createResources = await p.confirm({
      message: 'Create Cloudflare resources (D1, KV, R2) now?',
      initialValue: true,
    })

    if (p.isCancel(createResources)) {
      p.cancel('Setup cancelled')
      return
    }

    if (createResources && !dryRun) {
      const s = p.spinner()

      // D1
      s.start(`Creating D1 database: ${config.name}-db`)
      d1Id = createD1(`${config.name}-db`, appDir)
      s.stop(d1Id ? `D1 database created (${d1Id})` : 'D1 database creation skipped')

      // KV (if needed)
      if (config.hub.kv) {
        s.start(`Creating KV namespace: ${config.name}-kv`)
        kvId = createKv(`${config.name}-kv`, appDir)
        s.stop(kvId ? `KV namespace created (${kvId})` : 'KV namespace creation skipped')
      }

      // R2 (if needed)
      if (config.hub.blob) {
        s.start(`Creating R2 bucket: ${config.name}-blob`)
        createR2(`${config.name}-blob`, appDir)
        s.stop('R2 bucket created')
      }

      // Staging resources
      if (withStaging) {
        s.start(`Creating staging D1: ${config.name}-staging-db`)
        stagingD1Id = createD1(`${config.name}-staging-db`, appDir)
        s.stop(stagingD1Id ? `Staging D1 created (${stagingD1Id})` : 'Staging D1 creation skipped')

        if (config.hub.kv) {
          s.start(`Creating staging KV: ${config.name}-staging-kv`)
          stagingKvId = createKv(`${config.name}-staging-kv`, appDir)
          s.stop(stagingKvId ? `Staging KV created (${stagingKvId})` : 'Staging KV creation skipped')
        }

        if (config.hub.blob) {
          s.start(`Creating staging R2: ${config.name}-staging-blob`)
          createR2(`${config.name}-staging-blob`, appDir)
          s.stop('Staging R2 bucket created')
        }
      }
    } else if (dryRun) {
      consola.info('Would create:')
      console.log(`  D1: ${config.name}-db`)
      if (config.hub.kv) console.log(`  KV: ${config.name}-kv`)
      if (config.hub.blob) console.log(`  R2: ${config.name}-blob`)
      if (withStaging) {
        console.log(`  D1 (staging): ${config.name}-staging-db`)
        if (config.hub.kv) console.log(`  KV (staging): ${config.name}-staging-kv`)
        if (config.hub.blob) console.log(`  R2 (staging): ${config.name}-staging-blob`)
      }
    }
  }

  // ── 3. Update or generate wrangler config ───────────────────────────

  if (!dryRun) {
    if (withStaging) {
      // Need .jsonc for env block support
      consola.info('Generating wrangler.jsonc (staging requires env block)')

      // Use existing IDs from current config if we didn't create new ones
      const existingD1Id = config.wrangler?.d1Databases[0]?.databaseId
      const existingKvId = config.wrangler?.kvNamespaces[0]?.id
      const finalD1Id = d1Id || existingD1Id || 'TODO_SET_DB_ID'
      const finalKvId = kvId || existingKvId || null

      await generateWranglerJsonc(
        appDir,
        config.name,
        finalD1Id,
        config.hub.kv ? finalKvId : null,
        config.hub.blob ? `${config.name}-blob` : null,
        stagingD1Id,
        config.hub.kv ? stagingKvId : null,
        config.hub.blob ? `${config.name}-staging-blob` : null,
        true,
      )
    } else if (d1Id || kvId) {
      // Just update existing wrangler.toml with new IDs
      await updateWranglerToml(appDir, { d1Id: d1Id || undefined, kvId: kvId || undefined, withStaging: false })
    }
  }

  // ── 4. Generate CI workflow ─────────────────────────────────────────

  const packagesNeedingBuild = await getPackagesNeedingBuild(config.extends, monorepoRoot)
  // Also include the main crouton module package
  const croutonPkg = '@fyit/crouton'
  if (!packagesNeedingBuild.includes(croutonPkg)) {
    // Check if it needs building too
    const croutonPkgJson = join(monorepoRoot, 'packages', 'crouton', 'package.json')
    if (await pathExists(croutonPkgJson)) {
      try {
        const pkg = JSON.parse(await readFile(croutonPkgJson, 'utf-8'))
        if (pkg.scripts?.build) {
          packagesNeedingBuild.push(croutonPkg)
        }
      } catch { /* ignore */ }
    }
  }

  // All non-local extended packages for path filters
  const allExtendedPackages = config.extends.filter(e => !e.startsWith('./') && !e.startsWith('../'))

  const workflowContent = generateDeployWorkflow({
    appName: config.name,
    appDir: appRelDir,
    productionUrl: productionUrl as string,
    stagingUrl,
    withStaging: withStaging as boolean,
    layerPackages: packagesNeedingBuild,
    allExtendedPackages,
    dbName: config.wrangler?.d1Databases[0]?.databaseName || `${config.name}-db`,
    hasEnvBlock: withStaging as boolean,
  })

  const workflowDir = join(monorepoRoot, '.github', 'workflows')
  const workflowPath = join(workflowDir, `deploy-${config.name}.yml`)

  if (dryRun) {
    consola.info(`Would write workflow to: ${workflowPath}`)
    console.log()
    console.log(workflowContent)
  } else {
    await mkdir(workflowDir, { recursive: true })

    // Check if workflow already exists
    if (await pathExists(workflowPath)) {
      const overwrite = await p.confirm({
        message: `CI workflow already exists at deploy-${config.name}.yml. Overwrite?`,
        initialValue: false,
      })

      if (p.isCancel(overwrite) || !overwrite) {
        consola.warn('Skipping CI workflow generation')
      } else {
        await writeFile(workflowPath, workflowContent, 'utf-8')
        consola.success(`CI workflow updated: deploy-${config.name}.yml`)
      }
    } else {
      await writeFile(workflowPath, workflowContent, 'utf-8')
      consola.success(`CI workflow created: deploy-${config.name}.yml`)
    }
  }

  // ── 5. Print secrets checklist ──────────────────────────────────────

  const projectName = pagesProjectName || config.name

  p.note(
    [
      'Set these Cloudflare Pages secrets:',
      '',
      `  npx wrangler pages secret put BETTER_AUTH_SECRET --project-name ${projectName}`,
      `  npx wrangler pages secret put BETTER_AUTH_URL --project-name ${projectName}`,
      '',
      'Set these GitHub repository secrets:',
      '',
      '  CLOUDFLARE_ACCOUNT_ID    — Your Cloudflare account ID',
      '  CLOUDFLARE_API_TOKEN     — API token with Pages + D1 + R2 permissions',
      '',
      'Optional secrets (if features are enabled):',
      '',
      `  npx wrangler pages secret put NUXT_ANTHROPIC_API_KEY --project-name ${projectName}`,
      `  npx wrangler pages secret put NUXT_EMAIL_RESEND_API_KEY --project-name ${projectName}`,
    ].join('\n'),
    'Secrets Checklist',
  )

  p.outro('Deploy setup complete! Run `crouton deploy-check` to validate.')
}
