/**
 * @crouton-generated
 * @collection books
 * @layer main
 * @generated 2026-06-16
 *
 * ## AI Context
 * - Composable: useMainBooks
 * - Collection name: mainBooks
 * - API endpoint: /api/teams/[id]/main-books
 * - Form component: MainBooksForm
 * - List component: MainBooksList
 * - Fields: title, authorId, year, available
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

// Schema exported separately - Zod 4 schemas cannot survive deep cloning
// Keep schema outside of objects that might be serialized/cloned during SSR
export const mainBookSchema = z.object({
  title: z.string().min(1, 'title is required'),
  authorId: z.string().optional(),
  year: z.number().optional(),
  available: z.boolean().optional()
})

export const mainBooksColumns = [
  { accessorKey: 'title', header: 'Title' },
  { accessorKey: 'authorId', header: 'AuthorId' },
  { accessorKey: 'year', header: 'Year' },
  { accessorKey: 'available', header: 'Available' }
]

// Config object WITHOUT schema - safe for SSR serialization
const _mainBooksConfig = {
  name: 'mainBooks',
  layer: 'main',
  apiPath: 'main-books',
  componentName: 'MainBooksForm',
  defaultValues: {
    title: '',
    authorId: '',
    year: 0,
    available: false
  },
  columns: mainBooksColumns,
  fields: [
      {
          "name": "title",
          "type": "string",
          "label": "Book Title",
          "area": "main"
      },
      {
          "name": "authorId",
          "type": "string",
          "label": "Author",
          "area": "main"
      },
      {
          "name": "year",
          "type": "number",
          "label": "Year Published",
          "area": "main"
      },
      {
          "name": "available",
          "type": "boolean",
          "label": "Available",
          "area": "main"
      }
  ],
}

// Add schema as non-enumerable property so klona skips it during cloning
Object.defineProperty(_mainBooksConfig, 'schema', {
  value: mainBookSchema,
  enumerable: false,
  configurable: false,
  writable: false
})

export const mainBooksConfig = _mainBooksConfig as typeof _mainBooksConfig & { schema: typeof mainBookSchema }

export const useMainBooks = () => mainBooksConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: mainBooksConfig.defaultValues,
    schema: mainBookSchema,
    columns: mainBooksConfig.columns,
    collection: mainBooksConfig.name
  }
}