// config-builder.ts — Build crouton.config.js content from schemas and options.
// Shared between the CLI and the designer's scaffold endpoint.

interface ConfigBuilderOptions {
  appName: string
  packages?: string[]
  schemas?: Record<string, unknown>
  seedData?: Record<string, unknown[]>
  dialect?: string
  /** Package collections with their target layer names (separate from user collections) */
  packageCollections?: Array<{ name: string; layerName: string }>
  /** Collection names that should have publishable: true in the generated config */
  publishableCollections?: string[]
}

/**
 * Build crouton.config.js file content from structured input.
 */
export function buildCroutonConfig(options: ConfigBuilderOptions): string {
  const {
    appName,
    packages = [],
    schemas = {},
    seedData = {},
    dialect = 'sqlite',
    packageCollections = [],
    publishableCollections = [],
  } = options

  // Build features object (non-bundled only)
  const bundled = new Set(['auth', 'admin', 'i18n'])
  const features: Record<string, boolean> = {}
  for (const pkg of packages) {
    if (!bundled.has(pkg)) {
      features[pkg] = true
    }
  }

  const featuresStr = Object.entries(features)
    .map(([k, v]) => `    ${k}: ${v}`)
    .join(',\n')

  // Build collections array from schemas
  const collectionNames = Object.keys(schemas)

  const publishableSet = new Set(publishableCollections)

  const collectionsStr = collectionNames.map((name) => {
    const opts = [
      `name: '${name}'`,
      `fieldsFile: './schemas/${name}.json'`,
    ]

    // Add seed option if seed data exists for this collection
    if (seedData[name] && seedData[name].length > 0) {
      opts.push('seed: true')
    }

    // Add publishable flag if collection is publishable
    if (publishableSet.has(name)) {
      opts.push('publishable: true')
    }

    return `    { ${opts.join(', ')} }`
  }).join(',\n')

  // Build targets — package collections go to their own layers; user collections go to the app layer
  const pkgColNames = new Set(packageCollections.map(p => p.name))
  const userCollectionNames = collectionNames.filter(n => !pkgColNames.has(n))

  // Group package collections by their layer name
  const layerMap = new Map<string, string[]>()
  for (const pkg of packageCollections) {
    const existing = layerMap.get(pkg.layerName) ?? []
    layerMap.set(pkg.layerName, [...existing, pkg.name])
  }
  // User collections in the app layer (only if there are any)
  if (userCollectionNames.length > 0) {
    layerMap.set(appName, userCollectionNames)
  }

  const targetsStr = [...layerMap.entries()]
    .map(([layer, cols]) => `    { layer: '${layer}', collections: [${cols.map(n => `'${n}'`).join(', ')}] }`)
    .join(',\n')

  return `export default {
  // Feature flags - which crouton packages to enable
  features: {
${featuresStr ? featuresStr + '\n' : ''}  },

  // Collections generated by Schema Designer
  collections: [
${collectionsStr}
  ],

  // Target layers
  targets: [
${targetsStr}
  ],

  dialect: '${dialect}'
}
`
}
