// config-builder.ts — Build crouton.config.js content from schemas and options.
// Shared between the CLI and the designer's scaffold endpoint.

interface ConfigBuilderOptions {
  appName: string
  packages?: string[]
  schemas?: Record<string, unknown>
  seedData?: Record<string, unknown[]>
  dialect?: string
  /** Package collections with their target layer names (separate from user collections) */
  packageCollections?: Array<{ name: string; layerName: string }>
  /** Collection names that should have publishable: true in the generated config */
  publishableCollections?: string[]
}

/**
 * Build crouton.config.js file content from structured input.
 */
export function buildCroutonConfig(options: ConfigBuilderOptions): string {
  const {
    appName,
    packages = [],
    schemas = {},
    seedData = {},
    dialect = 'sqlite',
    packageCollections = [],
    publishableCollections = [],
  } = options

  // Build features object (non-bundled only)
  const bundled = new Set(['auth', 'admin', 'i18n'])
  const features: Record<string, boolean> = {}
  for (const pkg of packages) {
    if (!bundled.has(pkg)) {
      features[pkg] = true
    }
  }

  const featuresStr = Object.entries(features)
    .map(([k, v]) => `    ${k}: ${v}`)
    .join(',\n')

  // Build collections array from schemas
  const collectionNames = Object.keys(schemas)

  // Separate names: user-provided schemas vs package-only (no user schema provided)
  const pkgColNames = new Set(packageCollections.map(p => p.name))
  // Used for targets: user collections not associated with a package layer
  const userCollectionNames = collectionNames.filter(n => !pkgColNames.has(n))

  const publishableSet = new Set(publishableCollections)

  // Extra options for known package collections that provide their own form UI
  const PACKAGE_COLLECTION_CONFIGS: Record<string, { formComponent?: string; hierarchy?: string }> = {
    pages: {
      formComponent: 'CroutonPagesForm',
      hierarchy: `{ enabled: true, parentField: 'parentId', orderField: 'order', pathField: 'path', depthField: 'depth' }`,
    },
  }

  // User-provided schemas (may be for collections that are also in a package layer)
  const userEntries = collectionNames.map((name) => {
    const opts = [`name: '${name}'`, `fieldsFile: './schemas/${name}.json'`]
    if (seedData[name] && seedData[name].length > 0) opts.push('seed: true')
    if (publishableSet.has(name)) opts.push('publishable: true')
    return `    { ${opts.join(', ')} }`
  })

  // Package-only collections: in packageCollections but NOT in user-provided schemas.
  // The server writes the package's own schema file for these at scaffold time.
  const coveredSchemas = new Set(collectionNames)
  const pkgOnlyEntries = packageCollections
    .filter(pkg => !coveredSchemas.has(pkg.name))
    .map(({ name, layerName }) => {
      const opts = [`name: '${name}'`, `fieldsFile: './schemas/${name}.json'`]
      const pkgConfig = PACKAGE_COLLECTION_CONFIGS[name] ?? PACKAGE_COLLECTION_CONFIGS[layerName] ?? {}
      if (pkgConfig.formComponent) opts.push(`formComponent: '${pkgConfig.formComponent}'`)
      if (pkgConfig.hierarchy) opts.push(`hierarchy: ${pkgConfig.hierarchy}`)
      return `    { ${opts.join(', ')} }`
    })

  const collectionsStr = [...userEntries, ...pkgOnlyEntries].join(',\n')

  // Group package collections by their layer name
  const layerMap = new Map<string, string[]>()
  for (const pkg of packageCollections) {
    const existing = layerMap.get(pkg.layerName) ?? []
    layerMap.set(pkg.layerName, [...existing, pkg.name])
  }
  // User collections in the app layer (only if there are any)
  if (userCollectionNames.length > 0) {
    layerMap.set(appName, userCollectionNames)
  }

  const targetsStr = [...layerMap.entries()]
    .map(([layer, cols]) => `    { layer: '${layer}', collections: [${cols.map(n => `'${n}'`).join(', ')}] }`)
    .join(',\n')

  return `export default {
  // Feature flags - which crouton packages to enable
  features: {
${featuresStr ? featuresStr + '\n' : ''}  },

  // Collections generated by Schema Designer
  collections: [
${collectionsStr}
  ],

  // Target layers
  targets: [
${targetsStr}
  ],

  dialect: '${dialect}'
}
`
}
