/**
 * @crouton-generated
 * Server-Side Query Registry
 *
 * This file is auto-generated by @fyit/crouton-cli.
 * Run `crouton config` to regenerate after adding collections.
 *
 * Generated: 2026-06-16
 *
 * ## How This Works
 * Each entry lazily imports the collection's query module, so you only pay
 * the import cost for collections you actually query at runtime.
 *
 * ## Usage
 * ```ts
 * import { queryRegistry } from '#server/utils/crouton-query-registry'
 *
 * const getAll = await queryRegistry.contentAteliers.getAll()
 * const items = await getAll(teamId)
 * ```
 *
 * ## Registered Collections
 * - mainAuthors (main/authors)
 * - mainBooks (main/books)
 */

export const queryRegistry: Record<string, {
  getAll: () => Promise<(teamId: string) => Promise<any[]>>
  getByIds: () => Promise<(teamId: string, ids: string[]) => Promise<any[]>>
}> = {
  mainAuthors: {
    getAll: () => import('~~/layers/main/collections/authors/server/database/queries')
      .then(m => m.getAllMainAuthors),
    getByIds: () => import('~~/layers/main/collections/authors/server/database/queries')
      .then(m => m.getMainAuthorsByIds),
  },
  mainBooks: {
    getAll: () => import('~~/layers/main/collections/books/server/database/queries')
      .then(m => m.getAllMainBooks),
    getByIds: () => import('~~/layers/main/collections/books/server/database/queries')
      .then(m => m.getMainBooksByIds),
  },
}
