/**
 * @crouton-generated
 * @collection pages
 * @layer pages
 * @generated 2026-02-18
 *
 * ## AI Context
 * - Composable: usePagesPages
 * - Collection name: pagesPages
 * - API endpoint: /api/teams/[id]/pages-pages
 * - Form component: PagesPagesForm
 * - List component: PagesPagesList
 * - Fields: 
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

// Schema exported separately - Zod 4 schemas cannot survive deep cloning
// Keep schema outside of objects that might be serialized/cloned during SSR
export const pagesPageSchema = z.object({
  
})

export const pagesPagesColumns = [
  
]

// Config object WITHOUT schema - safe for SSR serialization
const _pagesPagesConfig = {
  name: 'pagesPages',
  layer: 'pages',
  apiPath: 'pages-pages',
  componentName: 'PagesPagesForm',
  defaultValues: {
    
  },
  columns: pagesPagesColumns,
  fields: [],
}

// Add schema as non-enumerable property so klona skips it during cloning
Object.defineProperty(_pagesPagesConfig, 'schema', {
  value: pagesPageSchema,
  enumerable: false,
  configurable: false,
  writable: false
})

export const pagesPagesConfig = _pagesPagesConfig as typeof _pagesPagesConfig & { schema: typeof pagesPageSchema }

export const usePagesPages = () => pagesPagesConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: pagesPagesConfig.defaultValues,
    schema: pagesPageSchema,
    columns: pagesPagesConfig.columns,
    collection: pagesPagesConfig.name
  }
}