ALTER TABLE `thinkgraph_decisions` ADD `status` text DEFAULT 'idle';
ALTER TABLE `thinkgraph_decisions` ADD `origin` text DEFAULT 'human';
ALTER TABLE `thinkgraph_decisions` ADD `notionId` text;
ALTER TABLE `thinkgraph_decisions` ADD `notionUrl` text;
ALTER TABLE `thinkgraph_decisions` ADD `worktreeRef` text;
ALTER TABLE `thinkgraph_decisions` ADD `sessionId` text;
ALTER TABLE `thinkgraph_decisions` ADD `brief` text;
ALTER TABLE `thinkgraph_decisions` ADD `contextScope` text DEFAULT 'branch';
ALTER TABLE `thinkgraph_decisions` ADD `approvedAt` text;
ALTER TABLE `thinkgraph_decisions` ADD `approvedBy` text;
