/**
 * @crouton-generated
 * @collection pages
 * @layer pages
 * @generated 2026-02-16
 *
 * ## AI Context
 * - Composable: usePagesPages
 * - Collection name: pagesPages
 * - API endpoint: /api/teams/[id]/pages-pages
 * - Form component: PagesPagesForm
 * - List component: PagesPagesList
 * - Fields: title, slug, pageType, content, config, status, visibility, publishedAt, showInNavigation, layout, seoTitle, seoDescription
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

// Schema exported separately - Zod 4 schemas cannot survive deep cloning
// Keep schema outside of objects that might be serialized/cloned during SSR
export const pagesPageSchema = z.object({
  pageType: z.string().min(1, 'pageType is required'),
  config: z.record(z.string(), z.any()).optional(),
  status: z.string().min(1, 'status is required'),
  visibility: z.string().min(1, 'visibility is required'),
  publishedAt: z.date().optional(),
  showInNavigation: z.boolean().optional(),
  layout: z.string().optional(),
  title: z.string().optional(),
  slug: z.string().optional(),
  content: z.string().optional(),
  seoTitle: z.string().optional(),
  seoDescription: z.string().optional(),
  parentId: z.string().nullable().optional(),
  translations: z.record(
    z.string(),
    z.object({
      title: z.string().optional(),
      slug: z.string().optional(),
      content: z.string().optional(),
      seoTitle: z.string().optional(),
      seoDescription: z.string().optional()
    })
  )
})

export const pagesPagesColumns = [
  { accessorKey: 'title', header: 'Title' },
  { accessorKey: 'slug', header: 'Slug' },
  { accessorKey: 'pageType', header: 'PageType' },
  { accessorKey: 'content', header: 'Content' },
  { accessorKey: 'config', header: 'Config' },
  { accessorKey: 'status', header: 'Status' },
  { accessorKey: 'visibility', header: 'Visibility' },
  { accessorKey: 'publishedAt', header: 'PublishedAt' },
  { accessorKey: 'showInNavigation', header: 'ShowInNavigation' },
  { accessorKey: 'layout', header: 'Layout' },
  { accessorKey: 'seoTitle', header: 'SeoTitle' },
  { accessorKey: 'seoDescription', header: 'SeoDescription' },
  { accessorKey: 'translations', header: 'Translations' }
]

// Config object WITHOUT schema - safe for SSR serialization
const _pagesPagesConfig = {
  name: 'pagesPages',
  layer: 'pages',
  apiPath: 'pages-pages',
  componentName: 'CroutonPagesForm',
  defaultValues: {
    title: '',
    slug: '',
    pageType: '',
    content: '',
    config: {},
    status: '',
    visibility: '',
    publishedAt: null,
    showInNavigation: false,
    layout: '',
    seoTitle: '',
    seoDescription: '',
    parentId: null,
    translations: {}
  },
  columns: pagesPagesColumns,
  hierarchy: {
    enabled: true,
    parentField: 'parentId',
    pathField: 'path',
    depthField: 'depth',
    orderField: 'order'
  },
}

// Add schema as non-enumerable property so klona skips it during cloning
Object.defineProperty(_pagesPagesConfig, 'schema', {
  value: pagesPageSchema,
  enumerable: false,
  configurable: false,
  writable: false
})

export const pagesPagesConfig = _pagesPagesConfig as typeof _pagesPagesConfig & { schema: typeof pagesPageSchema }

export const usePagesPages = () => pagesPagesConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: pagesPagesConfig.defaultValues,
    schema: pagesPageSchema,
    columns: pagesPagesConfig.columns,
    collection: pagesPagesConfig.name
  }
}