/**
 * @crouton-generated
 * @collection pages
 * @layer pages
 * @generated 2026-03-10
 *
 * ## AI Context
 * - Composable: usePagesPages
 * - Collection name: pagesPages
 * - API endpoint: /api/teams/[id]/pages-pages
 * - Form component: PagesPagesForm
 * - List component: PagesPagesList
 * - Fields: title, slug, pageType, content, config, status, visibility, publishedAt, showInNavigation, layout, seoTitle, seoDescription, ogImage, robots
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

// Schema exported separately - Zod 4 schemas cannot survive deep cloning
// Keep schema outside of objects that might be serialized/cloned during SSR
export const pagesPageSchema = z.object({
  pageType: z.string().min(1, 'pageType is required'),
  config: z.record(z.string(), z.any()).optional(),
  status: z.string().min(1, 'status is required'),
  visibility: z.string().min(1, 'visibility is required'),
  publishedAt: z.date().optional(),
  showInNavigation: z.boolean().optional(),
  layout: z.string().optional(),
  ogImage: z.string().optional(),
  robots: z.string().optional(),
  title: z.string().optional(),
  slug: z.string().optional(),
  content: z.string().optional(),
  seoTitle: z.string().optional(),
  seoDescription: z.string().optional(),
  parentId: z.string().nullable().optional(),
  translations: z.record(
    z.string(),
    z.object({
      title: z.string().min(1, 'Title is required'),
      slug: z.string().min(1, 'Slug is required'),
      content: z.string().optional(),
      seoTitle: z.string().optional(),
      seoDescription: z.string().optional()
    })
  ).refine(
    (translations) => translations.en && translations.en.title && translations.en.slug,
    { message: 'English translations for title, slug are required' }
  )
})

export const pagesPagesColumns = [
  { accessorKey: 'title', header: 'Title' },
  { accessorKey: 'slug', header: 'Slug' },
  { accessorKey: 'pageType', header: 'PageType' },
  { accessorKey: 'content', header: 'Content' },
  { accessorKey: 'config', header: 'Config' },
  { accessorKey: 'status', header: 'Status' },
  { accessorKey: 'visibility', header: 'Visibility' },
  { accessorKey: 'publishedAt', header: 'PublishedAt' },
  { accessorKey: 'showInNavigation', header: 'ShowInNavigation' },
  { accessorKey: 'layout', header: 'Layout' },
  { accessorKey: 'seoTitle', header: 'SeoTitle' },
  { accessorKey: 'seoDescription', header: 'SeoDescription' },
  { accessorKey: 'ogImage', header: 'OgImage' },
  { accessorKey: 'robots', header: 'Robots' },
  { accessorKey: 'translations', header: 'Translations' }
]

// Config object WITHOUT schema - safe for SSR serialization
const _pagesPagesConfig = {
  name: 'pagesPages',
  layer: 'pages',
  apiPath: 'pages-pages',
  componentName: 'CroutonPagesForm',
  defaultValues: {
    title: '',
    slug: '',
    pageType: '',
    content: '',
    config: {},
    status: '',
    visibility: '',
    publishedAt: null,
    showInNavigation: false,
    layout: '',
    seoTitle: '',
    seoDescription: '',
    ogImage: '',
    robots: '',
    parentId: null,
    translations: {}
  },
  columns: pagesPagesColumns,
  hierarchy: {
    enabled: true,
    parentField: 'parentId',
    pathField: 'path',
    depthField: 'depth',
    orderField: 'order'
  },
  fields: [
      {
          "name": "title",
          "type": "string",
          "label": "Title",
          "area": "main"
      },
      {
          "name": "slug",
          "type": "string",
          "label": "URL Slug",
          "area": "main"
      },
      {
          "name": "pageType",
          "type": "string",
          "label": "Page Type",
          "area": "meta"
      },
      {
          "name": "content",
          "type": "text",
          "label": "Content",
          "area": "main"
      },
      {
          "name": "config",
          "type": "json",
          "label": "Page Configuration",
          "area": "meta"
      },
      {
          "name": "status",
          "type": "string",
          "label": "Status",
          "area": "sidebar"
      },
      {
          "name": "visibility",
          "type": "string",
          "label": "Visibility",
          "area": "sidebar"
      },
      {
          "name": "publishedAt",
          "type": "date",
          "label": "Published At",
          "area": "sidebar"
      },
      {
          "name": "showInNavigation",
          "type": "boolean",
          "label": "Show in Navigation",
          "area": "sidebar"
      },
      {
          "name": "layout",
          "type": "string",
          "label": "Layout",
          "area": "sidebar"
      },
      {
          "name": "seoTitle",
          "type": "string",
          "label": "SEO Title",
          "area": "meta"
      },
      {
          "name": "seoDescription",
          "type": "string",
          "label": "SEO Description",
          "area": "meta"
      },
      {
          "name": "ogImage",
          "type": "string",
          "label": "Social Image",
          "area": "meta"
      },
      {
          "name": "robots",
          "type": "string",
          "label": "Search Engine Indexing",
          "area": "meta"
      }
  ],
}

// Add schema as non-enumerable property so klona skips it during cloning
Object.defineProperty(_pagesPagesConfig, 'schema', {
  value: pagesPageSchema,
  enumerable: false,
  configurable: false,
  writable: false
})

export const pagesPagesConfig = _pagesPagesConfig as typeof _pagesPagesConfig & { schema: typeof pagesPageSchema }

export const usePagesPages = () => pagesPagesConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: pagesPagesConfig.defaultValues,
    schema: pagesPageSchema,
    columns: pagesPagesConfig.columns,
    collection: pagesPagesConfig.name
  }
}