/**
 * @crouton-generated
 * @collection roomtypes
 * @layer bookingtest3
 * @generated 2026-02-25
 *
 * ## AI Context
 * - Main interface: Bookingtest3RoomType
 * - Form data type: Bookingtest3RoomTypeFormData
 * - New item type: NewBookingtest3RoomType
 * - Form props: Bookingtest3RoomTypeFormProps
 * - Fields: display, fields
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { bookingtest3RoomTypeSchema } from './app/composables/useBookingtest3RoomTypes'

export interface Bookingtest3RoomType {
  id: string
  teamId: string
  owner: string
  display?: string
  fields?: string
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type Bookingtest3RoomTypeFormData = z.infer<typeof bookingtest3RoomTypeSchema>
export type NewBookingtest3RoomType = Omit<Bookingtest3RoomType, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'>

// Props type for the Form component
export interface Bookingtest3RoomTypeFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: Bookingtest3RoomType | Record<string, never> // Bookingtest3RoomType for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}