/**
 * @crouton-generated
 * @collection departments
 * @layer bikeshed
 * @generated 2026-02-25
 *
 * ## AI Context
 * - Main interface: BikeshedDepartment
 * - Form data type: BikeshedDepartmentFormData
 * - New item type: NewBikeshedDepartment
 * - Form props: BikeshedDepartmentFormProps
 * - Fields: display, fields
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { bikeshedDepartmentSchema } from './app/composables/useBikeshedDepartments'

export interface BikeshedDepartment {
  id: string
  teamId: string
  owner: string
  display?: string
  fields?: string
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type BikeshedDepartmentFormData = z.infer<typeof bikeshedDepartmentSchema>
export type NewBikeshedDepartment = Omit<BikeshedDepartment, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'>

// Props type for the Form component
export interface BikeshedDepartmentFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: BikeshedDepartment | Record<string, never> // BikeshedDepartment for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}