/**
 * Stub translation composable for base nuxt-crouton layer
 *
 * Provides English fallbacks for standalone usage.
 * When nuxt-crouton-i18n layer is installed (and listed AFTER this layer),
 * its useT will override this stub via Nuxt's layer precedence.
 *
 * This is progressive enhancement:
 * - Without i18n layer: English fallbacks from this stub
 * - With i18n layer: Full translation support with team overrides
 */
export function useT() {
  const fallbacks: Record<string, string> = {
    // ===================
    // COMMON (~50 keys)
    // ===================
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.submit': 'Submit',
    'common.reset': 'Reset',
    'common.refresh': 'Refresh',
    'common.view': 'View',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.select': 'Select',
    'common.selectAll': 'Select All',
    'common.unselectAll': 'Unselect All',
    'common.actions': 'Actions',
    'common.loading': 'Loading...',
    'common.saving': 'Saving...',
    'common.deleting': 'Deleting...',
    'common.noResults': 'No results found',
    'common.noData': 'No data available',
    'common.required': 'Required',
    'common.optional': 'Optional',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.all': 'All',
    'common.none': 'None',
    'common.selected': 'Selected',
    'common.more': 'More',
    'common.less': 'Less',
    'common.showMore': 'Show more',
    'common.showLess': 'Show less',
    'common.viewAll': 'View all',
    'common.saveChanges': 'Save Changes',
    'common.proceed': 'Proceed',
    'common.change': 'Change',

    // ===================
    // EXPORT (~6 keys)
    // ===================
    'export.button': 'Export',
    'export.csv': 'Export as CSV',
    'export.json': 'Export as JSON',
    'export.noData': 'No data to export',
    'export.success': 'Export completed',
    'export.error': 'Export failed',

    // ===================
    // TABLE (~25 keys)
    // ===================
    'table.id': 'ID',
    'table.createdAt': 'Created At',
    'table.updatedAt': 'Updated At',
    'table.createdBy': 'Created By',
    'table.updatedBy': 'Updated By',
    'table.actions': 'Actions',
    'table.rowsPerPage': 'Rows per page',
    'table.rowsPerPageColon': 'Rows per page:',
    'table.page': 'Page',
    'table.of': 'of',
    'table.items': 'items',
    'table.results': 'results',
    'table.selected': 'selected',
    'table.total': 'Total',
    'table.showing': 'Showing',
    'table.to': 'to',
    'table.from': 'from',
    'table.first': 'First',
    'table.last': 'Last',
    'table.noResults': 'No results found',
    'table.sortAscending': 'Sort ascending',
    'table.sortDescending': 'Sort descending',
    'table.display': 'Display',
    'table.selectAll': 'Select all',
    'table.selectRow': 'Select row',
    'table.search': 'Search',

    // ===================
    // FORMS (~30 keys)
    // ===================
    'forms.name': 'Name',
    'forms.description': 'Description',
    'forms.status': 'Status',
    'forms.active': 'Active',
    'forms.inactive': 'Inactive',
    'forms.date': 'Date',
    'forms.time': 'Time',
    'forms.startDate': 'Start Date',
    'forms.endDate': 'End Date',
    'forms.notes': 'Notes',
    'forms.address': 'Address',
    'forms.phone': 'Phone',
    'forms.mobile': 'Mobile',
    'forms.fax': 'Fax',
    'forms.website': 'Website',
    'forms.company': 'Company',
    'forms.firstName': 'First Name',
    'forms.lastName': 'Last Name',
    'forms.fullName': 'Full Name',
    'forms.country': 'Country',
    'forms.city': 'City',
    'forms.state': 'State',
    'forms.zipCode': 'Zip Code',
    'forms.postalCode': 'Postal Code',
    'forms.language': 'Language',
    'forms.timezone': 'Timezone',
    'forms.currency': 'Currency',
    'forms.category': 'Category',
    'forms.translations': 'Translations',

    // ===================
    // ERRORS (~15 keys)
    // ===================
    'errors.generic': 'Something went wrong',
    'errors.notFound': 'Not found',
    'errors.unauthorized': 'Unauthorized',
    'errors.forbidden': 'Access denied',
    'errors.serverError': 'Server error',
    'errors.networkError': 'Network error',
    'errors.validationError': 'Validation error',
    'errors.requiredField': 'This field is required',
    'errors.invalidEmail': 'Invalid email address',
    'errors.invalidPassword': 'Invalid password',
    'errors.passwordMismatch': 'Passwords do not match',
    'errors.minLength': 'Must be at least {min} characters',
    'errors.maxLength': 'Must be at most {max} characters',
    'errors.tryAgain': 'Please try again',
    'errors.contactSupport': 'Please contact support if the problem persists',

    // ===================
    // SUCCESS (~6 keys)
    // ===================
    'success.saved': 'Saved successfully',
    'success.created': 'Created successfully',
    'success.updated': 'Updated successfully',
    'success.deleted': 'Deleted successfully',
    'success.sent': 'Sent successfully',
    'success.copied': 'Copied to clipboard',

    // ===================
    // CONFIRMATION (~6 keys)
    // ===================
    'confirmation.areYouSure': 'Are you sure?',
    'confirmation.deleteConfirm': 'Are you sure you want to delete this?',
    'confirmation.leaveConfirm': 'Are you sure you want to leave?',
    'confirmation.unsavedChanges': 'You have unsaved changes',
    'confirmation.discardChanges': 'Discard changes?',
    'confirmation.cannotUndo': 'This action cannot be undone',

    // ===================
    // TIME (~10 keys)
    // ===================
    'time.now': 'Now',
    'time.today': 'Today',
    'time.yesterday': 'Yesterday',
    'time.tomorrow': 'Tomorrow',
    'time.thisWeek': 'This week',
    'time.lastWeek': 'Last week',
    'time.thisMonth': 'This month',
    'time.lastMonth': 'Last month',
    'time.ago': '{time} ago',
    'time.in': 'in {time}',

    // ===================
    // AUTH (~30 keys)
    // For crouton-auth package
    // ===================
    'auth.signIn': 'Sign In',
    'auth.signOut': 'Sign Out',
    'auth.signUp': 'Sign Up',
    'auth.login': 'Log In',
    'auth.logout': 'Log Out',
    'auth.register': 'Register',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.resetPassword': 'Reset Password',
    'auth.changePassword': 'Change Password',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.rememberMe': 'Remember me',
    'auth.orContinueWith': 'Or continue with',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.dontHaveAccount': 'Don\'t have an account?',
    'auth.createAccount': 'Create Account',
    'auth.username': 'Username',
    'auth.verifyEmail': 'Verify your email',
    'auth.currentPassword': 'Current password',
    'auth.newPassword': 'New password',
    'auth.getStarted': 'Get Started',
    'auth.phoneNumber': 'Phone Number',
    'auth.loginWithMagicLink': 'Login with Magic Link',
    'auth.loginWithPasskey': 'Login with Passkey',
    'auth.sendResetLink': 'Send Reset Link',
    'auth.sendMagicLink': 'Send Magic Link',
    'auth.checkYourInbox': 'Check your inbox',
    'auth.backToSignIn': 'Back to Sign In',
    'auth.verify': 'Verify',
    'auth.welcomeBack': 'Welcome back!',
    'auth.magicLinkDescription': 'Enter your email and we\'ll send you a magic link to sign in.',
    'auth.signInWithMagicLink': 'Sign in with magic link',
    'auth.signInWithPassword': 'Sign in with password',
    'auth.createYourAccount': 'Create your account',
    'auth.termsAgreement': 'By creating an account, you agree to our',
    'auth.termsOfService': 'Terms of Service',
    'auth.privacyPolicy': 'Privacy Policy',
    'auth.and': 'and',
    'auth.resetYourPassword': 'Reset your password',
    'auth.resetPasswordDescription': 'Enter your email address and we\'ll send you a link to reset your password.',
    'auth.confirmNewPassword': 'Confirm new password',
    'auth.setNewPassword': 'Set new password',
    'auth.setNewPasswordDescription': 'Enter your new password below.',
    'auth.invalidResetLink': 'Invalid reset link',
    'auth.invalidResetLinkDescription': 'The password reset link is invalid or has expired. Please request a new one.',
    'auth.passwordUpdated': 'Password updated',
    'auth.passwordUpdatedDescription': 'Your password has been reset successfully. You can now sign in with your new password.',
    'auth.requestNewLink': 'Request new link',

    // ===================
    // ACCOUNT (~60 keys)
    // For account settings
    // ===================
    'account.settings': 'Account Settings',
    'account.settingsDescription': 'Manage your account settings and preferences.',
    'account.profile': 'Profile',
    'account.security': 'Security',
    'account.linkedAccounts': 'Linked Accounts',
    'account.linkedAccountsDescription': 'Connect external accounts for easy sign-in.',
    'account.dangerZone': 'Danger Zone',
    'account.deleteAccount': 'Delete Account',
    'account.deleteAccountDescription': 'Permanently delete your account and all associated data.',
    'account.deleteAccountWillPrefix': 'Deleting your account will:',
    'account.deleteWillRemoveData': 'Permanently remove all your personal data',
    'account.deleteWillCancelSubscriptions': 'Cancel any active subscriptions',
    'account.deleteWillRemoveFromTeams': 'Remove you from all teams',
    'account.deleteWillDeleteContent': 'Delete any content you\'ve created',
    'account.deleteMyAccount': 'Delete my account',
    'account.deleteAccountPermanent': 'This action is permanent and cannot be undone.',
    'account.aboutToDeleteAccount': 'You are about to permanently delete your account:',
    'account.enterYourPasswordLabel': 'Enter your password:',
    'account.typeToConfirmPrefix': 'Type',
    'account.typeToConfirmSuffix': 'to confirm:',
    'account.updateProfile': 'Update Profile',
    'account.updatePassword': 'Update Password',
    'account.twoFactorAuth': 'Two-Factor Authentication',
    'account.twoFactorDescription': 'Add an extra layer of security to your account.',
    'account.twoFactorNotEnabled': '2FA not enabled',
    'account.twoFactorNotEnabledDesc': 'Two-factor authentication is not enabled for this application.',
    'account.twoFactorEnabled': '2FA is enabled',
    'account.twoFactorEnabledDesc': 'Your account is protected with an authenticator app.',
    'account.twoFactorDisabled': '2FA is not enabled',
    'account.twoFactorDisabledDesc': 'Protect your account with an authenticator app.',
    'account.aboutTwoFactor': 'About Two-Factor Authentication',
    'account.aboutTwoFactorDesc': '2FA adds an extra layer of security by requiring a code from your authenticator app (like Google Authenticator, Authy, or 1Password) when signing in.',
    'account.enableTwoFactor': 'Enable Two-Factor Authentication',
    'account.enterPasswordToContinue': 'Enter your password to continue.',
    'account.enterYourPassword': 'Enter your password',
    'account.scanQrCode': 'Scan QR Code',
    'account.scanQrCodeDesc': 'Scan this QR code with your authenticator app.',
    'account.orEnterManually': 'Or enter this code manually:',
    'account.verifyCode': 'Verify Code',
    'account.verifyCodeDesc': 'Enter the 6-digit code from your authenticator app.',
    'account.saveBackupCodes': 'Save Backup Codes',
    'account.saveBackupCodesDesc': 'Save these backup codes in a secure place. Each can only be used once.',
    'account.backupCodesWarning': 'If you lose access to your authenticator app, you\'ll need these codes to sign in.',
    'account.copyCodes': 'Copy codes',
    'account.disableTwoFactorWarning': 'This will reduce your account security.',
    'account.disableTwoFactorDesc': 'Without 2FA, anyone with your password can access your account.',
    'account.enterPasswordToConfirm': 'Enter your password to confirm',
    'account.enterPasswordToViewCodes': 'Enter your password to view your backup codes.',
    'account.viewCodes': 'View codes',
    'account.codesRemaining': '{count} codes remaining.',
    'account.copyUnusedCodes': 'Copy unused codes',
    'account.enable2FA': 'Enable 2FA',
    'account.disable2FA': 'Disable 2FA',
    'account.backupCodes': 'Backup Codes',
    'account.viewBackupCodes': 'View Backup Codes',
    'account.profileUpdated': 'Profile updated',
    'account.passwordUpdated': 'Password updated',
    'account.socialLoginNotEnabled': 'Social login not enabled',
    'account.socialLoginNotEnabledDesc': 'Social login providers are not configured for this application.',
    'account.connectedOn': 'Connected {date}',
    'account.notConnected': 'Not connected',
    'account.disconnect': 'Disconnect',
    'account.connect': 'Connect',
    'account.keepOneLoginMethod': 'Keep at least one login method',
    'account.keepOneLoginMethodDesc': 'You need at least one way to sign in to your account. Connect another account or set a password before disconnecting this one.',
    'account.aboutLinkedAccounts': 'About Linked Accounts',
    'account.aboutLinkedAccountsDesc': 'Linking accounts lets you sign in using different services. Your data stays the same regardless of which method you use to sign in.',
    'account.passkeys': 'Passkeys',
    'account.passkeysDescription': 'Use passkeys for passwordless authentication.',
    'account.addPasskey': 'Add passkey',
    'account.browserNotSupported': 'Browser not supported',
    'account.browserNotSupportedDesc': 'Your browser doesn\'t support passkeys (WebAuthn). Try using a modern browser like Chrome, Firefox, or Safari.',
    'account.passkeysNotEnabled': 'Passkeys not enabled',
    'account.passkeysNotEnabledDesc': 'Passkey authentication is not enabled for this application.',
    'account.noPasskeysRegistered': 'No passkeys registered',
    'account.noPasskeysRegisteredDesc': 'Add a passkey to sign in without a password.',
    'account.addFirstPasskey': 'Add your first passkey',
    'account.addedOn': 'Added {date}',
    'account.aboutPasskeys': 'About Passkeys',
    'account.aboutPasskeysDesc': 'Passkeys use your device\'s biometrics (fingerprint, face) or PIN for secure, passwordless authentication. They\'re phishing-resistant and more secure than passwords.',

    // ===================
    // TEAMS (~50 keys)
    // For team management
    // ===================
    'teams.team': 'Team',
    'teams.teams': 'Teams',
    'teams.members': 'Members',
    'teams.member': 'Member',
    'teams.invite': 'Invite',
    'teams.inviteMember': 'Invite Member',
    'teams.role': 'Role',
    'teams.owner': 'Owner',
    'teams.admin': 'Admin',
    'teams.editor': 'Editor',
    'teams.viewer': 'Viewer',
    'teams.teamName': 'Team Name',
    'teams.teamNamePlaceholder': 'My Team',
    'teams.teamSettings': 'Team Settings',
    'teams.teamSettingsDescription': 'Manage your team\'s profile and settings.',
    'teams.createTeam': 'Create Team',
    'teams.leaveTeam': 'Leave Team',
    'teams.deleteTeam': 'Delete Team',
    'teams.switchTeam': 'Switch Team',
    'teams.selectTeam': 'Select team',
    'teams.teamMembers': 'Team Members',
    'teams.addMember': 'Add Member',
    'teams.removeMember': 'Remove Member',
    'teams.memberCount': '{count} member(s)',
    'teams.loadingMembers': 'Loading members...',
    'teams.noMembersFound': 'No members found',
    'teams.you': '(you)',
    'teams.urlSlug': 'URL slug',
    'teams.urlSlugHint': 'Changing the slug will update all team URLs.',
    'teams.logoUrl': 'Logo URL',
    'teams.logoUrlHint': 'Optional. Enter a URL to your team\'s logo.',
    'teams.warning': 'Warning',
    'teams.deleteTeamWillPrefix': 'Deleting this team will:',
    'teams.deleteWillRemoveMembers': 'Remove all team members',
    'teams.deleteWillCancelInvitations': 'Cancel all pending invitations',
    'teams.deleteWillDeleteData': 'Delete all team data and settings',
    'teams.deleteIsPermanent': 'This action is permanent and cannot be reversed',
    'teams.typeToConfirmPrefix': 'Type',
    'teams.typeToConfirmSuffix': 'to confirm:',
    'teams.yourInvitations': 'Your Invitations',
    'teams.pendingInvitations': 'Pending Invitations',
    'teams.yourInvitationsDescription': 'Invitations you have received to join teams.',
    'teams.pendingInvitationsDescription': 'Invitations waiting to be accepted.',
    'teams.loadingInvitations': 'Loading invitations...',
    'teams.noPendingInvitations': 'No pending invitations',
    'teams.cancelInvitation': 'Cancel invitation',
    'teams.decline': 'Decline',
    'teams.accept': 'Accept',

    // ===================
    // ADMIN (~10 keys)
    // For admin pages
    // ===================
    'admin.dashboard': 'Dashboard',
    'admin.users': 'Users',
    'admin.teams': 'Teams',
    'admin.settings': 'Settings',
    'admin.superAdmin': 'Super Admin',
    'admin.teamAdmin': 'Team Admin',
    'admin.manageTeam': 'Manage Team',
    'admin.systemSettings': 'System Settings',

    // ===================
    // NAVIGATION (~12 keys)
    // Common nav items
    // ===================
    'navigation.dashboard': 'Dashboard',
    'navigation.home': 'Home',
    'navigation.settings': 'Settings',
    'navigation.profile': 'Profile',
    'navigation.account': 'Account',
    'navigation.help': 'Help',
    'navigation.support': 'Support',
    'navigation.docs': 'Documentation',
    'navigation.backToDashboard': 'Back to Dashboard',
    'navigation.accountSettings': 'Account Settings',
    'navigation.collections': 'Collections'
  }

  const translate = (key: string, _options?: any): string => fallbacks[key] || key
  const translateString = (key: string, options?: any): string => translate(key, options)
  const translateContent = (entity: any, field: string): string => entity?.[field] || ''

  return {
    t: translate,
    tString: translateString,
    tContent: translateContent,
    tInfo: (key: string) => ({
      key,
      value: translate(key),
      mode: 'system' as const,
      category: 'ui',
      isMissing: !fallbacks[key],
      hasTeamOverride: false
    }),
    hasTranslation: (key: string) => !!fallbacks[key],
    getAvailableLocales: () => ['en'],
    getTranslationMeta: (key: string) => ({
      key,
      value: translate(key),
      hasTeamOverride: false,
      isSystemMissing: !fallbacks[key],
      availableLocales: ['en']
    }),
    refreshTranslations: async () => {},
    locale: ref('en'),
    isDev: false,
    devModeEnabled: ref(false)
  }
}
