/**
 * @crouton-generated
 * @collection venues
 * @layer main
 * @generated 2026-06-21
 *
 * ## AI Context
 * - Main interface: MainVenue
 * - Form data type: MainVenueFormData
 * - New item type: NewMainVenue
 * - Form props: MainVenueFormProps
 * - Fields: name, street, city, postcode, coordinates
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { mainVenueSchema } from './app/composables/useMainVenues'

export interface MainVenue {
  id: string
  teamId: string
  owner: string
  name: string
  street?: string
  city?: string
  postcode?: string
  coordinates?: string
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type MainVenueFormData = z.infer<typeof mainVenueSchema>
// New* allows the server-set fields (id, createdBy, updatedBy) as optional — the
// generated POST endpoint provides them; other callers (e.g. seed) may omit them.
export type NewMainVenue = Omit<MainVenue, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'> & { id?: string; createdBy?: string; updatedBy?: string }

// Props type for the Form component
export interface MainVenueFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: MainVenue | Record<string, never> // MainVenue for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}