<!--
  @crouton-generated
  @collection categories
  @layer content
  @generated 2026-03-11

  ## AI Context
  - List component for categories collection
  - Collection name: contentCategories
  - API endpoint: /api/teams/[id]/content-categories
  - Columns composable: useContentCategories()
  - Column fields: title, order, color, thumbnail, background, isSidebar

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="contentCategories"
    :columns="columns"
    :rows="categories || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="ContentCategories"
        :collection="'contentCategories'"
        createButton
      />
    </template>
    <template #title-cell="{ row }">
      {{ t(row.original, 'title') }}
    </template>
    <template #isSidebar-cell="{ row }">
      <CroutonBoolean :value="row.original.isSidebar" />
    </template>
    <template #translations-cell="{ row }">
      <CroutonI18nListCards :item="row.original" :fields="['title']" />
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import useContentCategories from '../composables/useContentCategories'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { t } = useEntityTranslations()
const { locale } = useI18n()
const { columns } = useContentCategories()

const { items: categories, pending } = await useCollectionQuery(
  'contentCategories'
)

</script>