<!--
  @crouton-generated
  @collection emailtemplates
  @layer bookings
  @generated 2026-02-25

  ## AI Context
  - Form component for emailtemplates collection
  - Handles: create, update, delete actions
  - API endpoint: /api/teams/[id]/bookings-emailtemplates
  - Zod schema: useBookingsEmailtemplates() composable
  - Fields: name, subject, body, fromEmail, triggerType, recipientType, isActive, daysOffset, locationId

  ## Common Modifications
  - Add field: Add UFormField in template, update schema in composable
  - Custom validation: Modify schema in composable
  - Custom field component: Use meta.component in schema JSON
  - Change layout: Modify CroutonFormLayout template slots

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonFormActionButton
    v-if="action === 'delete'"
    :action="action"
    :collection="collection"
    :items="items"
    :loading="loading"
    @click="handleSubmit"
  />

  <UForm
    v-else
    :schema="schema"
    :state="state"
    @submit="handleSubmit"
  >
    <CroutonFormLayout>
      <template #main>


      <div>


      <CroutonI18nInput
        v-model="state.translations"
        :fields="['name', 'subject', 'body']"
        :default-values="{
          name: state.name || '',
          subject: state.subject || '',
          body: state.body || ''
        }"
        show-ai-translate
        field-type="emailtemplates"
        :label="$t('bookings.fields.translations')"
      />
      </div>
      </template>

      <template #sidebar>
      <div class="flex flex-col gap-4 p-1">
      </div>
      <div class="flex flex-col gap-4 p-1">
        <UFormField :label="$t('bookings.fields.fromEmail')" name="fromEmail" class="not-last:pb-4">
          <UInput v-model="state.fromEmail" class="w-full" size="xl" />
        </UFormField>
        <UFormField :label="$t('bookings.fields.triggerType')" name="triggerType" class="not-last:pb-4">
          <USelect
            v-model="state.triggerType"
            :items="triggerTypeOptions"
            class="w-full"
            size="xl"
          />
        </UFormField>
        <UFormField :label="$t('bookings.fields.recipientType')" name="recipientType" class="not-last:pb-4">
          <USelect
            v-model="state.recipientType"
            :items="recipientTypeOptions"
            class="w-full"
            size="xl"
          />
        </UFormField>
        <UFormField :label="$t('bookings.fields.isActive')" name="isActive" class="not-last:pb-4">
          <UCheckbox v-model="state.isActive" />
        </UFormField>
        <UFormField :label="$t('bookings.fields.daysOffset')" name="daysOffset" class="not-last:pb-4">
          <UInputNumber v-model="state.daysOffset" class="w-full" />
        </UFormField>
        <UFormField :label="$t('bookings.fields.locationId')" name="locationId" class="not-last:pb-4">
          <CroutonFormReferenceSelect
            v-model="state.locationId as any"
            collection="bookingsLocations"
            :label="$t('bookings.fields.locationId')"
          />
        </UFormField>
      </div>
      </template>

      <template #footer>
        <CroutonFormActionButton
          :action="action"
          :collection="collection"
          :items="items"
          :loading="loading"
        />
      </template>
    </CroutonFormLayout>
  </UForm>
</template>

<script setup lang="ts">
import type { BookingsEmailtemplateFormProps, BookingsEmailtemplateFormData } from '../../types'
import useBookingsEmailtemplates from '../composables/useBookingsEmailtemplates'

const props = defineProps<BookingsEmailtemplateFormProps>()
const { defaultValue, schema, collection } = useBookingsEmailtemplates()

// Form layout configuration
const tabs = ref(false)

const { t: $t } = useI18n()

// Static select options
const triggerTypeOptions = computed(() => [
  { label: $t('bookings.triggerTypes.booking_created'), value: 'booking_created' },
  { label: $t('bookings.triggerTypes.reminder_before'), value: 'reminder_before' },
  { label: $t('bookings.triggerTypes.booking_cancelled'), value: 'booking_cancelled' },
  { label: $t('bookings.triggerTypes.follow_up_after'), value: 'follow_up_after' }
])

const recipientTypeOptions = computed(() => [
  { label: $t('bookings.recipientTypes.customer'), value: 'customer' },
  { label: $t('bookings.recipientTypes.admin'), value: 'admin' },
  { label: $t('bookings.recipientTypes.both'), value: 'both' }
])



// Use new mutation composable for data operations
const { create, update, deleteItems } = useCollectionMutation(collection)

// useCrouton still manages modal state
const { close, loading } = useCrouton()

// Initialize form state with proper values (no watch needed!)
const initialValues = props.action === 'update' && props.activeItem?.id
  ? { ...defaultValue, ...props.activeItem }
  : { ...defaultValue }

const state = ref<BookingsEmailtemplateFormData & { id?: string | null }>(initialValues)

const handleSubmit = async () => {
  try {
    if (props.action === 'create') {
      await create(state.value)
    } else if (props.action === 'update' && state.value.id) {
      await update(state.value.id, state.value)
    } else if (props.action === 'delete') {
      await deleteItems(props.items)
    }

    close()

  } catch (error) {
    console.error('Form submission failed:', error)
    // You can add toast notification here if available
    // toast.add({ title: 'Error', description: 'Failed to submit form', color: 'red' })
  }
}
</script>