<!--
  @crouton-generated
  @collection tasks
  @layer project-management
  @generated 2025-12-22

  ## AI Context
  - Form component for tasks collection
  - Handles: create, update, delete actions
  - API endpoint: /api/teams/[id]/project-management-tasks
  - Zod schema: useProjectManagementTasks() composable
  - Fields: title, description, status, priority, projectId, dueDate, completedAt, estimatedHours

  ## Common Modifications
  - Add field: Add UFormField in template, update schema in composable
  - Custom validation: Modify schema in composable
  - Custom field component: Use meta.component in schema JSON
  - Change layout: Modify CroutonFormLayout template slots

  Generated by @friendlyinternet/nuxt-crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonFormActionButton
    v-if="action === 'delete'"
    :action="action"
    :collection="collection"
    :items="items"
    :loading="loading"
    @click="handleSubmit"
  />

  <UForm
    v-else
    :schema="schema"
    :state="state"
    @submit="handleSubmit"
  >
    <CroutonFormLayout>
      <template #main>
      <div class="flex flex-col gap-4 p-1">
        <UFormField label="Title" name="title" class="not-last:pb-4">
          <UInput v-model="state.title" class="w-full" size="xl" />
        </UFormField>
        <UFormField label="Description" name="description" class="not-last:pb-4">
          <UTextarea v-model="state.description" class="w-full" size="xl" />
        </UFormField>
        <UFormField label="Status" name="status" class="not-last:pb-4">
          <UInput v-model="state.status" class="w-full" size="xl" />
        </UFormField>
        <UFormField label="Priority" name="priority" class="not-last:pb-4">
          <UInput v-model="state.priority" class="w-full" size="xl" />
        </UFormField>
        <UFormField label="ProjectId" name="projectId" class="not-last:pb-4">
          <UInput v-model="state.projectId" class="w-full" size="xl" />
        </UFormField>
        <UFormField label="DueDate" name="dueDate" class="not-last:pb-4">
          <CroutonCalendar v-model:date="state.dueDate" />
        </UFormField>
        <UFormField label="CompletedAt" name="completedAt" class="not-last:pb-4">
          <UInput v-model="state.completedAt" class="w-full" size="xl" />
        </UFormField>
        <UFormField label="EstimatedHours" name="estimatedHours" class="not-last:pb-4">
          <UInputNumber v-model="state.estimatedHours" class="w-full" />
        </UFormField>
      </div>
      </template>

      <template #footer>
        <CroutonFormActionButton
          :action="action"
          :collection="collection"
          :items="items"
          :loading="loading"
        />
      </template>
    </CroutonFormLayout>
  </UForm>
</template>

<script setup lang="ts">
import type { ProjectManagementTaskFormProps, ProjectManagementTaskFormData } from '../../types'
import useProjectManagementTasks from '../composables/useProjectManagementTasks'

const props = defineProps<ProjectManagementTaskFormProps>()
const { defaultValue, schema, collection } = useProjectManagementTasks()

// Form layout configuration
const tabs = ref(false)



// Use new mutation composable for data operations
const { create, update, deleteItems } = useCollectionMutation(collection)

// useCrouton still manages modal state
const { close, loading } = useCrouton()

// Initialize form state with proper values (no watch needed!)
const initialValues = props.action === 'update' && props.activeItem?.id
  ? { ...defaultValue, ...props.activeItem }
  : { ...defaultValue }

// Convert date strings to Date objects for date fields during editing
if (props.action === 'update' && props.activeItem?.id) {
  if (initialValues.dueDate) {
    initialValues.dueDate = new Date(initialValues.dueDate)
  }
}

const state = ref<ProjectManagementTaskFormData & { id?: string | null }>(initialValues)

const handleSubmit = async () => {
  try {
    // Serialize Date objects to ISO strings for API submission
    const serializedData = { ...state.value }
    if (serializedData.dueDate instanceof Date) {
      serializedData.dueDate = serializedData.dueDate.toISOString()
    }

    if (props.action === 'create') {
      await create(serializedData)
    } else if (props.action === 'update' && state.value.id) {
      await update(state.value.id, serializedData)
    } else if (props.action === 'delete') {
      await deleteItems(props.items)
    }

    close()

  } catch (error) {
    console.error('Form submission failed:', error)
    // You can add toast notification here if available
    // toast.add({ title: 'Error', description: 'Failed to submit form', color: 'red' })
  }
}
</script>