<!--
  @crouton-generated
  @collection contacts
  @layer people
  @generated 2026-02-20

  ## AI Context
  - List component for contacts collection
  - Collection name: peopleContacts
  - API endpoint: /api/teams/[id]/people-contacts
  - Columns composable: usePeopleContacts()
  - Column fields: name, email, phone, website, bio, avatar, resume, active, birthday, socialLinks, skills

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="peopleContacts"
    :columns="columns"
    :rows="contacts || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="PeopleContacts"
        :collection="'peopleContacts'"
        createButton
      />
    </template>
    <template #skills-cell="{ row }">
      <div v-if="row.original.skills && row.original.skills.length > 0" class="flex flex-wrap gap-1">
        <UBadge
          v-for="(item, idx) in row.original.skills"
          :key="idx"
          color="neutral"
          variant="subtle"
          size="md"
        >
          {{ item }}
        </UBadge>
      </div>
      <span v-else class="text-gray-400">—</span>
    </template>
    <template #birthday-cell="{ row }">
      <CroutonDate :date="row.original.birthday"></CroutonDate>
    </template>
    <template #active-cell="{ row }">
      <CroutonBoolean :value="row.original.active" />
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import usePeopleContacts from '../composables/usePeopleContacts'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { columns } = usePeopleContacts()

const { items: contacts, pending } = await useCollectionQuery(
  'peopleContacts'
)

</script>