export default {
  // Feature flags - which crouton packages to enable
  features: {},

  // Collections generated by Schema Designer
  collections: [],

  // Target layers
  targets: [],

  dialect: 'sqlite'
}
