export default {
  // Feature flags - which crouton packages to enable
  features: {},

  // Collections generated by Schema Designer
  collections: [
    { name: 'posts', fieldsFile: './schemas/posts.json' }
  ],

  // Target layers
  targets: [
    { layer: 'blog', collections: ['posts'] }
  ],

  dialect: 'sqlite'
}
