<!--
  @crouton-generated
  @collection locations
  @layer bookings
  @generated 2025-12-22

  ## AI Context
  - Form component for locations collection
  - Handles: create, update, delete actions
  - API endpoint: /api/teams/[id]/bookings-locations
  - Zod schema: useBookingsLocations() composable
  - Fields: title, street, zip, city, location, content, allowedMemberIds, slots, inventoryMode, quantity

  ## Common Modifications
  - Add field: Add UFormField in template, update schema in composable
  - Custom validation: Modify schema in composable
  - Custom field component: Use meta.component in schema JSON
  - Change layout: Modify CroutonFormLayout template slots

  Generated by @friendlyinternet/nuxt-crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonFormActionButton
    v-if="action === 'delete'"
    :action="action"
    :collection="collection"
    :items="items"
    :loading="loading"
    @click="handleSubmit"
  />

  <UForm
    v-else
    :schema="schema"
    :state="state"
    @submit="handleSubmit"
    @error="handleValidationError"
  >
    <CroutonFormLayout :tabs="tabs" :navigation-items="navigationItems" :tab-errors="tabErrorCounts" v-model="activeSection">
      <template #main="{ activeSection }">
      <div v-show="!tabs || activeSection === 'address'" class="flex flex-col gap-4 p-1">
        <UFormField label="Zip" name="zip" class="not-last:pb-4">
          <UInput v-model="state.zip" class="w-full" size="xl" />
        </UFormField>
      </div>

      <div v-show="!tabs || activeSection === 'scheduling'" class="flex flex-col gap-4 p-1">
        <UFormField label="Slots" name="slots" class="not-last:pb-4">
          <CroutonFormRepeater
            v-model="state.slots"
            component-name="BookingsLocationsSlotInput"
            add-label="Add Time Slot"
            :sortable="true"
          />
        </UFormField>
      </div>

      <div>


      <CroutonI18nInput
        v-model="state.translations"
        :fields="['title', 'street', 'city', 'content']"
        :default-values="{
          title: state.title || '',
          street: state.street || '',
          city: state.city || '',
          content: state.content || ''
        }"
        :field-components="{
          content: 'CroutonEditorSimple'
        }"
        label="Translations"
      />
      </div>
      </template>

      <template #sidebar>
      <div class="flex flex-col gap-4 p-1">
      </div>
      <div class="flex flex-col gap-4 p-1">
        <UFormField label="Location" name="location" class="not-last:pb-4">
          <UTextarea v-model="state.location" class="w-full" size="xl" />
        </UFormField>
      </div>

      <div class="flex flex-col gap-4 p-1">
        <UFormField label="AllowedMemberIds" name="allowedMemberIds" class="not-last:pb-4">
          <CroutonFormReferenceSelect
            v-model="state.allowedMemberIds"
            collection="member"
            label="AllowedMemberIds"
            multiple
          />
        </UFormField>
      </div>

      <div class="flex flex-col gap-4 p-1">
        <UFormField label="InventoryMode" name="inventoryMode" class="not-last:pb-4">
          <UCheckbox v-model="state.inventoryMode" />
        </UFormField>
        <UFormField label="Quantity" name="quantity" class="not-last:pb-4">
          <UInputNumber v-model="state.quantity" class="w-full" />
        </UFormField>
      </div>
      </template>

      <template #footer>
        <CroutonValidationErrorSummary
          v-if="validationErrors.length > 0"
          :tab-errors="tabErrorCounts"
          :navigation-items="navigationItems"
          @switch-tab="switchToTab"
        />

        <CroutonFormActionButton
          :action="action"
          :collection="collection"
          :items="items"
          :loading="loading"
          :has-validation-errors="validationErrors.length > 0"
        />
      </template>
    </CroutonFormLayout>
  </UForm>
</template>

<script setup lang="ts">
import type { BookingsLocationFormProps, BookingsLocationFormData } from '../../types'
import useBookingsLocations from '../composables/useBookingsLocations'

const props = defineProps<BookingsLocationFormProps>()
const { defaultValue, schema, collection } = useBookingsLocations()

// Form layout configuration
const navigationItems = [
  { label: 'Address', value: 'address' },
  { label: 'Scheduling', value: 'scheduling' }
]

const tabs = ref(true)
const activeSection = ref('address')

// Map field names to their tab groups for error tracking
const fieldToGroup: Record<string, string> = {
  'zip': 'address',
  'slots': 'scheduling'
}

// Track validation errors for tab indicators
const validationErrors = ref<Array<{ name: string; message: string }>>([])

// Handle form validation errors
const handleValidationError = (event: any) => {
  if (event?.errors) {
    validationErrors.value = event.errors
  }
}

// Compute errors per tab
const tabErrorCounts = computed(() => {
  const counts: Record<string, number> = {}

  validationErrors.value.forEach(error => {
    const tabName = fieldToGroup[error.name] || 'general'
    counts[tabName] = (counts[tabName] || 0) + 1
  })

  return counts
})

// Switch to a specific tab (for clicking error links)
const switchToTab = (tabValue: string) => {
  activeSection.value = tabValue
}

// Use new mutation composable for data operations
const { create, update, deleteItems } = useCollectionMutation(collection)

// useCrouton still manages modal state
const { close, loading } = useCrouton()

// Initialize form state with proper values (no watch needed!)
const initialValues = props.action === 'update' && props.activeItem?.id
  ? { ...defaultValue, ...props.activeItem }
  : { ...defaultValue }

const state = ref<BookingsLocationFormData & { id?: string | null }>(initialValues)

const handleSubmit = async () => {
  try {
    if (props.action === 'create') {
      await create(state.value)
    } else if (props.action === 'update' && state.value.id) {
      await update(state.value.id, state.value)
    } else if (props.action === 'delete') {
      await deleteItems(props.items)
    }

    // Clear validation errors on successful submission
    validationErrors.value = []

    close()

  } catch (error) {
    console.error('Form submission failed:', error)
    // You can add toast notification here if available
    // toast.add({ title: 'Error', description: 'Failed to submit form', color: 'red' })
  }
}
</script>