<!--
  @crouton-generated
  @collection locations
  @layer bookings
  @generated 2026-01-11

  ## AI Context
  - List component for locations collection
  - Collection name: bookingsLocations
  - API endpoint: /api/teams/[id]/bookings-locations
  - Columns composable: useBookingsLocations()
  - Column fields: title, color, street, zip, city, location, content, allowedMemberIds, slots, inventoryMode, quantity

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @friendlyinternet/nuxt-crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="bookingsLocations"
    :columns="columns"
    :rows="locations || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="BookingsLocations"
        :collection="'bookingsLocations'"
        createButton
      />
    </template>
    <template #title-cell="{ row }">
      {{ t(row.original, 'title') }}
    </template>
    <template #street-cell="{ row }">
      {{ t(row.original, 'street') }}
    </template>
    <template #zip-cell="{ row }">
      {{ t(row.original, 'zip') }}
    </template>
    <template #city-cell="{ row }">
      {{ t(row.original, 'city') }}
    </template>
    <template #allowedMemberIds-cell="{ row }">
      <div v-if="row.original.allowedMemberIds && row.original.allowedMemberIds.length > 0" class="flex flex-wrap gap-1">
        <UBadge
          v-for="(item, idx) in row.original.allowedMemberIds"
          :key="idx"
          color="neutral"
          variant="subtle"
          size="md"
        >
          {{ item }}
        </UBadge>
      </div>
      <span v-else class="text-gray-400">—</span>
    </template>
    <template #inventoryMode-cell="{ row }">
      <CroutonBoolean :value="row.original.inventoryMode" />
    </template>
    <template #slots-cell="{ row }">
      <BookingsLocationsSlotCardMini :value="row.original.slots" />
    </template>
    <template #content-cell="{ row }">
      <CroutonEditorPreview :content="row.original.content" />
    </template>
    <template #location-cell="{ row }">
      <CroutonMapsPreview :location="row.original.location" />
    </template>
    <template #translations-cell="{ row }">
      <CroutonI18nListCards :item="row.original" :fields="['title', 'street', 'zip', 'city', 'content']" />
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import useBookingsLocations from '../composables/useBookingsLocations'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { t } = useEntityTranslations()
const { locale } = useI18n()
const { columns } = useBookingsLocations()

const { items: locations, pending } = await useCollectionQuery(
  'bookingsLocations'
)
</script>