// Generator for collection-level README.md files
// Provides AI-friendly documentation for each generated collection

export function generateCollectionReadme(data, config = {}) {
  const {
    singular,
    plural,
    pascalCase,
    pascalCasePlural,
    layerPascalCase,
    layer,
    fields,
    hierarchy
  } = data

  const prefixedPascalCase = `${layerPascalCase}${pascalCase}`
  const prefixedPascalCasePlural = `${layerPascalCase}${pascalCasePlural}`
  const prefixedCamelCasePlural = `${layer}${pascalCasePlural}`
  const apiPath = `${layer}-${plural}`
  const generatedDate = new Date().toISOString().split('T')[0]

  // Build field table
  const fieldRows = fields
    .filter(f => f.name !== 'id')
    .map((field) => {
      const required = field.meta?.required ? 'Yes' : 'No'
      const refInfo = field.refTarget ? ` (→ ${field.refTarget})` : ''
      return `| ${field.name} | ${field.type}${refInfo} | ${required} |`
    })
    .join('\n')

  // Check for special features
  const hasHierarchy = hierarchy?.enabled === true
  const hasTranslations = config?.translations?.collections?.[plural]?.length > 0
  const translatableFields = config?.translations?.collections?.[plural] || []
  const referenceFields = fields.filter(f => f.refTarget)
  const repeaterFields = fields.filter(f => f.type === 'repeater')

  // Build features list
  const features = []
  if (hasHierarchy) features.push('- Tree/hierarchy structure with parent-child relationships')
  if (hasTranslations) features.push(`- Multi-language support for: ${translatableFields.join(', ')}`)
  if (referenceFields.length) features.push(`- References: ${referenceFields.map(f => `${f.name} → ${f.refTarget}`).join(', ')}`)
  if (repeaterFields.length) features.push(`- Repeater fields: ${repeaterFields.map(f => f.name).join(', ')}`)

  const featuresSection = features.length > 0
    ? `\n## Features\n\n${features.join('\n')}\n`
    : ''

  return `# ${prefixedPascalCasePlural} Collection

> Generated by @friendlyinternet/nuxt-crouton-cli on ${generatedDate}

## Overview

| Property | Value |
|----------|-------|
| Collection Name | \`${prefixedCamelCasePlural}\` |
| Layer | \`${layer}\` |
| API Base | \`/api/teams/[teamId]/${apiPath}\` |
| Form Component | \`<${prefixedPascalCasePlural}Form />\` |
| List Component | \`<${prefixedPascalCasePlural}List />\` |
| Composable | \`use${prefixedPascalCasePlural}()\` |
${featuresSection}
## File Structure

\`\`\`
collections/${plural}/
├── app/
│   ├── components/
│   │   ├── Form.vue              # CRUD form with Zod validation
│   │   └── List.vue              # Data table with actions
│   └── composables/
│       └── use${prefixedPascalCasePlural}.ts   # Schema, columns, config
├── server/
│   ├── api/teams/[id]/${apiPath}/
│   │   ├── index.get.ts          # GET all / by IDs
│   │   ├── index.post.ts         # CREATE
│   │   ├── [${singular}Id].patch.ts    # UPDATE
│   │   └── [${singular}Id].delete.ts   # DELETE${hasHierarchy
  ? `
│   │   ├── [${singular}Id]/move.patch.ts  # Move in tree
│   │   └── reorder.patch.ts      # Reorder siblings`
  : ''}
│   └── database/
│       ├── schema.ts             # Drizzle ORM schema
│       └── queries.ts            # Database query functions
├── types.ts                      # TypeScript interfaces
├── nuxt.config.ts               # Layer configuration
└── README.md                    # This file
\`\`\`

## Fields

| Field | Type | Required |
|-------|------|----------|
| id | string (primary key) | Auto |
${fieldRows}
| createdAt | timestamp | Auto |
| updatedAt | timestamp | Auto |
| createdBy | string | Auto |
| updatedBy | string | Auto |

## API Endpoints

### GET /api/teams/{teamId}/${apiPath}

Fetch all items or specific items by IDs.

\`\`\`typescript
// Fetch all
const items = await $fetch(\`/api/teams/\${teamId}/${apiPath}\`)

// Fetch by IDs
const items = await $fetch(\`/api/teams/\${teamId}/${apiPath}?ids=id1,id2,id3\`)
\`\`\`

### POST /api/teams/{teamId}/${apiPath}

Create a new item.

\`\`\`typescript
const newItem = await $fetch(\`/api/teams/\${teamId}/${apiPath}\`, {
  method: 'POST',
  body: {
    // ... fields (see schema)
  }
})
\`\`\`

### PATCH /api/teams/{teamId}/${apiPath}/{${singular}Id}

Update an existing item.

\`\`\`typescript
const updated = await $fetch(\`/api/teams/\${teamId}/${apiPath}/\${${singular}Id}\`, {
  method: 'PATCH',
  body: {
    // ... fields to update
  }
})
\`\`\`

### DELETE /api/teams/{teamId}/${apiPath}/{${singular}Id}

Delete an item.

\`\`\`typescript
await $fetch(\`/api/teams/\${teamId}/${apiPath}/\${${singular}Id}\`, {
  method: 'DELETE'
})
\`\`\`

## Usage

### In Components

\`\`\`vue
<script setup lang="ts">
// Query items
const { items: ${plural}, pending } = await useCollectionQuery('${prefixedCamelCasePlural}')

// Mutations
const { create, update, deleteItems } = useCollectionMutation('${prefixedCamelCasePlural}')
</script>

<template>
  <${prefixedPascalCasePlural}List />
</template>
\`\`\`

### Schema & Validation

\`\`\`typescript
import { ${layer}${pascalCase}Schema } from './app/composables/use${prefixedPascalCasePlural}'

// Validate data
const result = ${layer}${pascalCase}Schema.safeParse(data)
\`\`\`

## Customization Guide

### Add a New Field

1. Add field to your schema JSON file
2. Regenerate: \`crouton config --only ${plural}\`
3. Or manually:
   - Add to \`types.ts\` interface
   - Add to composable schema and defaultValues
   - Add \`<UFormField>\` in Form.vue
   - Add column in composable if needed

### Customize Form Layout

Edit \`app/components/Form.vue\`:
- Add field groups with \`meta.group\` in schema
- Modify \`CroutonFormLayout\` slots
- Add custom field components

### Add Custom Validation

Edit \`app/composables/use${prefixedPascalCasePlural}.ts\`:
\`\`\`typescript
export const ${layer}${pascalCase}Schema = z.object({
  // ... existing fields
  email: z.string().email('Invalid email'),
  age: z.number().min(0).max(120)
})
\`\`\`

### Add Server-Side Logic

Edit API endpoints in \`server/api/teams/[id]/${apiPath}/\`:
- Add validation with \`readValidatedBody\`
- Add custom business logic
- Emit custom events/hooks

---

*This README was auto-generated. Safe to modify - regeneration requires --force flag.*
`
}
