/**
 * @crouton-generated
 * @collection contacts
 * @layer people
 * @generated 2026-02-20
 *
 * ## AI Context
 * - Main interface: PeopleContact
 * - Form data type: PeopleContactFormData
 * - New item type: NewPeopleContact
 * - Form props: PeopleContactFormProps
 * - Fields: name, email, phone, website, bio, avatar, resume, active, birthday, socialLinks, skills
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { peopleContactSchema } from './app/composables/usePeopleContacts'

export interface PeopleContact {
  id: string
  teamId: string
  owner: string
  name: string
  email: string
  phone?: string
  website?: string
  bio?: string
  avatar?: string
  resume?: string
  active?: boolean
  birthday?: Date | null
  socialLinks?: Record<string, any>
  skills?: string[]
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type PeopleContactFormData = z.infer<typeof peopleContactSchema>
export type NewPeopleContact = Omit<PeopleContact, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'>

// Props type for the Form component
export interface PeopleContactFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: PeopleContact | Record<string, never> // PeopleContact for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}