/**
 * @crouton-generated
 * Server-Side Query Registry
 *
 * This file is auto-generated by @fyit/crouton-cli.
 * Run `crouton config` to regenerate after adding collections.
 *
 * Generated: 2026-06-16
 *
 * ## How This Works
 * Each entry lazily imports the collection's query module, so you only pay
 * the import cost for collections you actually query at runtime.
 *
 * ## Usage
 * ```ts
 * import { queryRegistry } from '#server/utils/crouton-query-registry'
 *
 * const getAll = await queryRegistry.contentAteliers.getAll()
 * const items = await getAll(teamId)
 * ```
 *
 * ## Registered Collections
 * - mainItems (main/items)
 * - pagesPages (pages/pages)
 */

export const queryRegistry: Record<string, {
  getAll: () => Promise<(teamId: string) => Promise<any[]>>
  getByIds: () => Promise<(teamId: string, ids: string[]) => Promise<any[]>>
}> = {
  mainItems: {
    getAll: () => import('~~/layers/main/collections/items/server/database/queries')
      .then(m => m.getAllMainItems),
    getByIds: () => import('~~/layers/main/collections/items/server/database/queries')
      .then(m => m.getMainItemsByIds),
  },
  pagesPages: {
    getAll: () => import('~~/layers/pages/collections/pages/server/database/queries')
      .then(m => m.getAllPagesPages),
    getByIds: () => import('~~/layers/pages/collections/pages/server/database/queries')
      .then(m => m.getPagesPagesByIds),
  },
}
