/**
 * @crouton-generated
 * @collection posts
 * @layer blog
 * @generated 2025-12-18
 *
 * ## AI Context
 * - Composable: useBlogPosts
 * - Collection name: blogPosts
 * - API endpoint: /api/teams/[id]/blog-posts
 * - Form component: BlogPostsForm
 * - List component: BlogPostsList
 * - Fields: id, title, slug, content, published, publishedAt, authorName
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @friendlyinternet/nuxt-crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

export const blogPostSchema = z.object({
  title: z.string().min(1, 'title is required'),
  slug: z.string().min(1, 'slug is required'),
  content: z.string().optional(),
  published: z.boolean().optional(),
  publishedAt: z.string().optional(),
  authorName: z.string().optional()
})

export const blogPostsColumns = [
  { accessorKey: 'id', header: 'Id' },
  { accessorKey: 'title', header: 'Title' },
  { accessorKey: 'slug', header: 'Slug' },
  { accessorKey: 'content', header: 'Content' },
  { accessorKey: 'published', header: 'Published' },
  { accessorKey: 'publishedAt', header: 'PublishedAt' },
  { accessorKey: 'authorName', header: 'AuthorName' }
]

export const blogPostsConfig = {
  name: 'blogPosts',
  layer: 'blog',
  apiPath: 'blog-posts',
  componentName: 'BlogPostsForm',
  schema: blogPostSchema,
  defaultValues: {
    title: '',
    slug: '',
    content: '',
    published: false,
    publishedAt: '',
    authorName: ''
  },
  columns: blogPostsColumns,
}

export const useBlogPosts = () => blogPostsConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: blogPostsConfig.defaultValues,
    schema: blogPostsConfig.schema,
    columns: blogPostsConfig.columns,
    collection: blogPostsConfig.name
  }
}