/**
 * @crouton-generated
 * @collection authors
 * @layer main
 * @generated 2026-06-16
 *
 * ## AI Context
 * - Composable: useMainAuthors
 * - Collection name: mainAuthors
 * - API endpoint: /api/teams/[id]/main-authors
 * - Form component: MainAuthorsForm
 * - List component: MainAuthorsList
 * - Fields: name, bio
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

// Schema exported separately - Zod 4 schemas cannot survive deep cloning
// Keep schema outside of objects that might be serialized/cloned during SSR
export const mainAuthorSchema = z.object({
  name: z.string().min(1, 'name is required'),
  bio: z.string().optional()
})

export const mainAuthorsColumns = [
  { accessorKey: 'name', header: 'Name' },
  { accessorKey: 'bio', header: 'Bio' }
]

// Config object WITHOUT schema - safe for SSR serialization
const _mainAuthorsConfig = {
  name: 'mainAuthors',
  layer: 'main',
  apiPath: 'main-authors',
  componentName: 'MainAuthorsForm',
  defaultValues: {
    name: '',
    bio: ''
  },
  columns: mainAuthorsColumns,
  fields: [
      {
          "name": "name",
          "type": "string",
          "label": "Author Name",
          "area": "main"
      },
      {
          "name": "bio",
          "type": "text",
          "label": "Biography",
          "area": "main"
      }
  ],
}

// Add schema as non-enumerable property so klona skips it during cloning
Object.defineProperty(_mainAuthorsConfig, 'schema', {
  value: mainAuthorSchema,
  enumerable: false,
  configurable: false,
  writable: false
})

export const mainAuthorsConfig = _mainAuthorsConfig as typeof _mainAuthorsConfig & { schema: typeof mainAuthorSchema }

export const useMainAuthors = () => mainAuthorsConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: mainAuthorsConfig.defaultValues,
    schema: mainAuthorSchema,
    columns: mainAuthorsConfig.columns,
    collection: mainAuthorsConfig.name
  }
}