/**
 * @crouton-generated
 * @collection settings
 * @layer bookings
 * @generated 2026-01-20
 *
 * ## AI Context
 * - Composable: useBookingsSettings
 * - Collection name: bookingsSettings
 * - API endpoint: /api/teams/[id]/bookings-settings
 * - Form component: BookingsSettingsForm
 * - List component: BookingsSettingsList
 * - Fields: statuses, groups
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

// Schema exported separately - Zod 4 schemas cannot survive deep cloning
// Keep schema outside of objects that might be serialized/cloned during SSR
export const bookingsSettingSchema = z.object({
  statuses: z.array(z.any()).optional(),
  groups: z.array(z.any()).optional()
})

export const bookingsSettingsColumns = [
  { accessorKey: 'statuses', header: 'Statuses' },
  { accessorKey: 'groups', header: 'Groups' }
]

// Config object WITHOUT schema - safe for SSR serialization
const _bookingsSettingsConfig = {
  name: 'bookingsSettings',
  layer: 'bookings',
  apiPath: 'bookings-settings',
  componentName: 'BookingsSettingsForm',
  defaultValues: {
    statuses: [],
    groups: []
  },
  columns: bookingsSettingsColumns,
  dependentFieldComponents: {
    statuses: 'BookingsSettingsStatuseSelect',
    groups: 'BookingsSettingsGroupSelect'
  },
}

// Add schema as non-enumerable property so klona skips it during cloning
Object.defineProperty(_bookingsSettingsConfig, 'schema', {
  value: bookingsSettingSchema,
  enumerable: false,
  configurable: false,
  writable: false
})

export const bookingsSettingsConfig = _bookingsSettingsConfig as typeof _bookingsSettingsConfig & { schema: typeof bookingsSettingSchema }

export const useBookingsSettings = () => bookingsSettingsConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: bookingsSettingsConfig.defaultValues,
    schema: bookingsSettingSchema,
    columns: bookingsSettingsConfig.columns,
    collection: bookingsSettingsConfig.name
  }
}