<!--
  @crouton-generated
  @collection watchreports
  @layer thinkgraph
  @generated 2026-04-07

  ## AI Context
  - List component for watchreports collection
  - Collection name: thinkgraphWatchReports
  - API endpoint: /api/teams/[id]/thinkgraph-watchreports
  - Columns composable: useThinkgraphWatchReports()
  - Column fields: repoId, runDate, summary, commitsSinceLast, createdNodeIds

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="thinkgraphWatchReports"
    :columns="columns"
    :rows="watchreports || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="ThinkgraphWatchReports"
        :collection="'thinkgraphWatchReports'"
        createButton
      />
    </template>
    <template #repoId-cell="{ row }">
      <CroutonItemCardMini
        v-if="row.original.repoId"
        :id="row.original.repoId"
        collection="thinkgraphWatchedRepos"
      />
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import useThinkgraphWatchReports from '../composables/useThinkgraphWatchReports'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { columns } = useThinkgraphWatchReports()

const { items: watchReports, pending } = await useCollectionQuery(
  'thinkgraphWatchReports'
)

</script>