<!--
  @crouton-generated
  @collection assets
  @layer bookings
  @generated 2026-02-18

  ## AI Context
  - List component for assets collection
  - Collection name: bookingsAssets
  - API endpoint: /api/teams/[id]/bookings-assets
  - Columns composable: useBookingsAssets()
  - Column fields: teamId, userId, filename, pathname, contentType, size, category, width, height, alt, uploadedAt, updatedBy

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="bookingsAssets"
    :columns="columns"
    :rows="assets || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="BookingsAssets"
        :collection="'bookingsAssets'"
        createButton
      />
    </template>
    <template #teamId-cell="{ row }">
      <CroutonItemCardMini
        v-if="row.original.teamId"
        :id="row.original.teamId"
        collection="bookingsOrganisations"
      />
    </template>
    <template #userId-cell="{ row }">
      <CroutonItemCardMini
        v-if="row.original.userId"
        :id="row.original.userId"
        collection="bookingsUsers"
      />
    </template>
    <template #updatedBy-cell="{ row }">
      <CroutonItemCardMini
        v-if="row.original.updatedBy"
        :id="row.original.updatedBy"
        collection="bookingsUsers"
      />
    </template>
    <template #uploadedAt-cell="{ row }">
      <CroutonDate :date="row.original.uploadedAt"></CroutonDate>
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import useBookingsAssets from '../composables/useBookingsAssets'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { columns } = useBookingsAssets()

const { items: assets, pending } = await useCollectionQuery(
  'bookingsAssets'
)

</script>