/**
 * @crouton-generated
 * @collection tasks
 * @layer project-management
 * @generated 2025-12-22
 *
 * ## AI Context
 * - Main interface: ProjectManagementTask
 * - Form data type: ProjectManagementTaskFormData
 * - New item type: NewProjectManagementTask
 * - Form props: ProjectManagementTaskFormProps
 * - Fields: id, title, description, status, priority, projectId, dueDate, completedAt, estimatedHours
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @friendlyinternet/nuxt-crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { projectManagementTaskSchema } from './app/composables/useProjectManagementTasks'

export interface ProjectManagementTask {
  id: string
  teamId: string
  owner: string
  title: string
  description?: string
  status?: string
  priority?: string
  projectId?: string
  dueDate?: Date | null
  completedAt?: string
  estimatedHours?: number
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type ProjectManagementTaskFormData = z.infer<typeof projectManagementTaskSchema>
export type NewProjectManagementTask = Omit<ProjectManagementTask, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'>

// Props type for the Form component
export interface ProjectManagementTaskFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: ProjectManagementTask | Record<string, never> // ProjectManagementTask for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}