<!--
  @crouton-generated
  @collection kdsbumps
  @layer sales
  @generated 2026-06-24

  ## AI Context
  - List component for kdsbumps collection
  - Collection name: salesKdsbumps
  - API endpoint: /api/teams/[id]/sales-kdsbumps
  - Columns composable: useSalesKdsbumps()
  - Column fields: eventId, orderId, locationId

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="salesKdsbumps"
    :columns="columns"
    :rows="kdsbumps || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="SalesKdsbumps"
        :collection="'salesKdsbumps'"
        createButton
      />
    </template>
    <template #eventId-cell="{ row }">
      <CroutonItemCardMini
        v-if="row.original.eventId"
        :id="row.original.eventId"
        collection="salesEvents"
      />
    </template>
    <template #orderId-cell="{ row }">
      <CroutonItemCardMini
        v-if="row.original.orderId"
        :id="row.original.orderId"
        collection="salesOrders"
      />
    </template>
    <template #locationId-cell="{ row }">
      <CroutonItemCardMini
        v-if="row.original.locationId"
        :id="row.original.locationId"
        collection="salesLocations"
      />
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import useSalesKdsbumps from '../composables/useSalesKdsbumps'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { columns } = useSalesKdsbumps()

const { items: kdsbumps, pending } = await useCollectionQuery(
  'salesKdsbumps'
)

</script>