/**
 * @crouton-generated
 * @collection decisions
 * @layer playground
 * @generated 2025-12-18
 *
 * ## AI Context
 * - Composable: usePlaygroundDecisions
 * - Collection name: playgroundDecisions
 * - API endpoint: /api/teams/[id]/playground-decisions
 * - Form component: PlaygroundDecisionsForm
 * - List component: PlaygroundDecisionsList
 * - Fields: id, title, description, type, status, position
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @friendlyinternet/nuxt-crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

export const playgroundDecisionSchema = z.object({
  title: z.string().min(1, 'title is required'),
  description: z.string().optional(),
  type: z.string().optional(),
  status: z.string().optional(),
  position: z.record(z.any()).optional(),
  parentId: z.string().nullable().optional()
})

export const playgroundDecisionsColumns = [
  { accessorKey: 'id', header: 'Id' },
  { accessorKey: 'title', header: 'Title' },
  { accessorKey: 'description', header: 'Description' },
  { accessorKey: 'type', header: 'Type' },
  { accessorKey: 'status', header: 'Status' },
  { accessorKey: 'position', header: 'Position' }
]

export const playgroundDecisionsConfig = {
  name: 'playgroundDecisions',
  layer: 'playground',
  apiPath: 'playground-decisions',
  componentName: 'PlaygroundDecisionsForm',
  schema: playgroundDecisionSchema,
  defaultValues: {
    title: '',
    description: '',
    type: '',
    status: '',
    position: {},
    parentId: null
  },
  columns: playgroundDecisionsColumns,
  hierarchy: {
    enabled: true,
    parentField: 'parentId',
    pathField: 'path',
    depthField: 'depth',
    orderField: 'order'
  },
}

export const usePlaygroundDecisions = () => playgroundDecisionsConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: playgroundDecisionsConfig.defaultValues,
    schema: playgroundDecisionsConfig.schema,
    columns: playgroundDecisionsConfig.columns,
    collection: playgroundDecisionsConfig.name
  }
}