/**
 * @crouton-generated
 * @collection accounts
 * @layer triage
 * @generated 2026-02-11
 *
 * ## AI Context
 * - Main interface: TriageAccount
 * - Form data type: TriageAccountFormData
 * - New item type: NewTriageAccount
 * - Form props: TriageAccountFormProps
 * - Fields: provider, label, providerAccountId, accessToken, accessTokenHint, refreshToken, tokenExpiresAt, scopes, providerMetadata, status, lastVerifiedAt
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { triageAccountSchema } from './app/composables/useTriageAccounts'

export interface TriageAccount {
  id: string
  teamId: string
  owner: string
  provider: string
  label: string
  providerAccountId: string
  accessToken: string
  accessTokenHint?: string
  refreshToken?: string
  tokenExpiresAt?: Date | null
  scopes?: string
  providerMetadata?: Record<string, any>
  status: string
  lastVerifiedAt?: Date | null
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type TriageAccountFormData = z.infer<typeof triageAccountSchema>
export type NewTriageAccount = Omit<TriageAccount, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'>

// Props type for the Form component
export interface TriageAccountFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: TriageAccount | Record<string, never> // TriageAccount for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}