/**
 * @crouton-generated
 * @collection posts
 * @layer blog
 * @generated 2025-12-20
 *
 * ## AI Context
 * - Composable: useBlogPosts
 * - Collection name: blogPosts
 * - API endpoint: /api/teams/[id]/blog-posts
 * - Form component: BlogPostsForm
 * - List component: BlogPostsList
 * - Fields: title, content, published
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @friendlyinternet/nuxt-crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

// Schema exported separately - Zod 4 schemas cannot survive deep cloning
// Keep schema outside of objects that might be serialized/cloned during SSR
export const blogPostSchema = z.object({
  title: z.string().min(1, 'title is required'),
  content: z.string().optional(),
  published: z.boolean().optional()
})

export const blogPostsColumns = [
  { accessorKey: 'title', header: 'Title' },
  { accessorKey: 'content', header: 'Content' },
  { accessorKey: 'published', header: 'Published' }
]

// Config object WITHOUT schema - safe for SSR serialization
const _blogPostsConfig = {
  name: 'blogPosts',
  layer: 'blog',
  apiPath: 'blog-posts',
  componentName: 'BlogPostsForm',
  defaultValues: {
    title: '',
    content: '',
    published: false
  },
  columns: blogPostsColumns,
}

// Add schema as non-enumerable property so klona skips it during cloning
Object.defineProperty(_blogPostsConfig, 'schema', {
  value: blogPostSchema,
  enumerable: false,
  configurable: false,
  writable: false
})

export const blogPostsConfig = _blogPostsConfig as typeof _blogPostsConfig & { schema: typeof blogPostSchema }

export const useBlogPosts = () => blogPostsConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: blogPostsConfig.defaultValues,
    schema: blogPostSchema,
    columns: blogPostsConfig.columns,
    collection: blogPostsConfig.name
  }
}