/**
 * @crouton-generated
 * @collection bookings
 * @layer bookings
 * @generated 2026-02-10
 *
 * ## AI Context
 * - Composable: useBookingsBookings
 * - Collection name: bookingsBookings
 * - API endpoint: /api/teams/[id]/bookings-bookings
 * - Form component: BookingsBookingsForm
 * - List component: BookingsBookingsList
 * - Fields: location, date, slot, group, status
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

// Schema exported separately - Zod 4 schemas cannot survive deep cloning
// Keep schema outside of objects that might be serialized/cloned during SSR
export const bookingsBookingSchema = z.object({
  location: z.string().min(1, 'location is required'),
  date: z.date({ required_error: 'date is required' }),
  slot: z.array(z.string()).min(1, 'slot is required'),
  group: z.string().optional(),
  status: z.string().min(1, 'status is required')
})

export const bookingsBookingsColumns = [
  { accessorKey: 'location', header: 'Location' },
  { accessorKey: 'date', header: 'Date' },
  { accessorKey: 'slot', header: 'Slot' },
  { accessorKey: 'group', header: 'Group' },
  { accessorKey: 'status', header: 'Status' }
]

// Config object WITHOUT schema - safe for SSR serialization
const _bookingsBookingsConfig = {
  name: 'bookingsBookings',
  layer: 'bookings',
  apiPath: 'bookings-bookings',
  componentName: 'BookingsBookingsForm',
  defaultValues: {
    location: '',
    date: null,
    slot: null,
    group: '',
    status: ''
  },
  columns: bookingsBookingsColumns,
  dependentFieldComponents: {
    slot: 'BookingsBookingsSlotSelect'
  },
}

// Add schema as non-enumerable property so klona skips it during cloning
Object.defineProperty(_bookingsBookingsConfig, 'schema', {
  value: bookingsBookingSchema,
  enumerable: false,
  configurable: false,
  writable: false
})

export const bookingsBookingsConfig = _bookingsBookingsConfig as typeof _bookingsBookingsConfig & { schema: typeof bookingsBookingSchema }

export const useBookingsBookings = () => bookingsBookingsConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: bookingsBookingsConfig.defaultValues,
    schema: bookingsBookingSchema,
    columns: bookingsBookingsConfig.columns,
    collection: bookingsBookingsConfig.name
  }
}