/**
 * @crouton-generated
 * @collection products
 * @layer sales
 * @generated 2025-12-25
 *
 * ## AI Context
 * - Main interface: SalesProduct
 * - Form data type: SalesProductFormData
 * - New item type: NewSalesProduct
 * - Form props: SalesProductFormProps
 * - Fields: id, eventId, categoryId, locationId, title, description, price, isActive, requiresRemark, remarkPrompt, hasOptions, multipleOptionsAllowed, options, sortOrder
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @friendlyinternet/nuxt-crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { salesProductSchema } from './app/composables/useSalesProducts'

export interface SalesProduct {
  id: string
  teamId: string
  owner: string
  eventId: string
  categoryId?: string
  locationId?: string
  title: string
  description?: string
  price: number
  isActive?: boolean
  requiresRemark?: boolean
  remarkPrompt?: string
  hasOptions?: boolean
  multipleOptionsAllowed?: boolean
  options?: any[]
  sortOrder?: string
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type SalesProductFormData = z.infer<typeof salesProductSchema>
export type NewSalesProduct = Omit<SalesProduct, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'>

// Props type for the Form component
export interface SalesProductFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: SalesProduct | Record<string, never> // SalesProduct for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}