/**
 * @crouton-generated
 * @collection orderitems
 * @layer sales
 * @generated 2025-12-25
 *
 * ## AI Context
 * - Main interface: SalesOrderItem
 * - Form data type: SalesOrderItemFormData
 * - New item type: NewSalesOrderItem
 * - Form props: SalesOrderItemFormProps
 * - Fields: id, orderId, productId, quantity, unitPrice, totalPrice, remarks, selectedOptions
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @friendlyinternet/nuxt-crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { salesOrderItemSchema } from './app/composables/useSalesOrderItems'

export interface SalesOrderItem {
  id: string
  teamId: string
  owner: string
  orderId: string
  productId: string
  quantity: string
  unitPrice: number
  totalPrice: number
  remarks?: string
  selectedOptions?: Record<string, any>
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type SalesOrderItemFormData = z.infer<typeof salesOrderItemSchema>
export type NewSalesOrderItem = Omit<SalesOrderItem, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'>

// Props type for the Form component
export interface SalesOrderItemFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: SalesOrderItem | Record<string, never> // SalesOrderItem for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}