/**
 * @crouton-generated
 * @collection users
 * @layer triage
 * @generated 2026-03-10
 *
 * ## AI Context
 * - Composable: useTriageUsers
 * - Collection name: triageUsers
 * - API endpoint: /api/teams/[id]/triage-users
 * - Form component: TriageUsersForm
 * - List component: TriageUsersList
 * - Fields: sourceType, sourceWorkspaceId, sourceUserId, sourceUserEmail, sourceUserName, notionUserId, notionUserName, notionUserEmail, mappingType, confidence, active, lastSyncedAt, metadata
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

// Schema exported separately - Zod 4 schemas cannot survive deep cloning
// Keep schema outside of objects that might be serialized/cloned during SSR
export const triageUserSchema = z.object({
  sourceType: z.string().min(1, 'sourceType is required'),
  sourceWorkspaceId: z.string().min(1, 'sourceWorkspaceId is required'),
  sourceUserId: z.string().min(1, 'sourceUserId is required'),
  sourceUserEmail: z.string().optional(),
  sourceUserName: z.string().optional(),
  notionUserId: z.string().min(1, 'notionUserId is required'),
  notionUserName: z.string().optional(),
  notionUserEmail: z.string().optional(),
  mappingType: z.string().min(1, 'mappingType is required'),
  confidence: z.number().optional(),
  active: z.boolean(),
  lastSyncedAt: z.string().optional(),
  metadata: z.record(z.string(), z.any()).optional()
})

export const triageUsersColumns = [
  { accessorKey: 'sourceType', header: 'SourceType' },
  { accessorKey: 'sourceWorkspaceId', header: 'SourceWorkspaceId' },
  { accessorKey: 'sourceUserId', header: 'SourceUserId' },
  { accessorKey: 'sourceUserEmail', header: 'SourceUserEmail' },
  { accessorKey: 'sourceUserName', header: 'SourceUserName' },
  { accessorKey: 'notionUserId', header: 'NotionUserId' },
  { accessorKey: 'notionUserName', header: 'NotionUserName' },
  { accessorKey: 'notionUserEmail', header: 'NotionUserEmail' },
  { accessorKey: 'mappingType', header: 'MappingType' },
  { accessorKey: 'confidence', header: 'Confidence' },
  { accessorKey: 'active', header: 'Active' },
  { accessorKey: 'lastSyncedAt', header: 'LastSyncedAt' },
  { accessorKey: 'metadata', header: 'Metadata' }
]

// Config object WITHOUT schema - safe for SSR serialization
const _triageUsersConfig = {
  name: 'triageUsers',
  layer: 'triage',
  apiPath: 'triage-users',
  componentName: 'TriageUsersForm',
  defaultValues: {
    sourceType: '',
    sourceWorkspaceId: '',
    sourceUserId: '',
    sourceUserEmail: '',
    sourceUserName: '',
    notionUserId: '',
    notionUserName: '',
    notionUserEmail: '',
    mappingType: '',
    confidence: 0,
    active: false,
    lastSyncedAt: '',
    metadata: {}
  },
  columns: triageUsersColumns,
  fields: [
      {
          "name": "sourceType",
          "type": "string",
          "label": "Source Type",
          "area": "main"
      },
      {
          "name": "sourceWorkspaceId",
          "type": "string",
          "label": "Source Workspace ID",
          "area": "main"
      },
      {
          "name": "sourceUserId",
          "type": "string",
          "label": "Source User ID",
          "area": "main"
      },
      {
          "name": "sourceUserEmail",
          "type": "string",
          "label": "Source User Email",
          "area": "main"
      },
      {
          "name": "sourceUserName",
          "type": "string",
          "label": "Source User Name",
          "area": "main"
      },
      {
          "name": "notionUserId",
          "type": "string",
          "label": "Notion User ID",
          "area": "main"
      },
      {
          "name": "notionUserName",
          "type": "string",
          "label": "Notion User Name",
          "area": "main"
      },
      {
          "name": "notionUserEmail",
          "type": "string",
          "label": "Notion User Email",
          "area": "main"
      },
      {
          "name": "mappingType",
          "type": "string",
          "label": "Mapping Type",
          "area": "sidebar"
      },
      {
          "name": "confidence",
          "type": "number",
          "label": "Confidence Score",
          "area": "sidebar"
      },
      {
          "name": "active",
          "type": "boolean",
          "label": "Active",
          "area": "sidebar"
      },
      {
          "name": "lastSyncedAt",
          "type": "string",
          "label": "Last Synced At",
          "area": "sidebar"
      },
      {
          "name": "metadata",
          "type": "json",
          "label": "Additional Metadata",
          "area": "sidebar"
      }
  ],
}

// Add schema as non-enumerable property so klona skips it during cloning
Object.defineProperty(_triageUsersConfig, 'schema', {
  value: triageUserSchema,
  enumerable: false,
  configurable: false,
  writable: false
})

export const triageUsersConfig = _triageUsersConfig as typeof _triageUsersConfig & { schema: typeof triageUserSchema }

export const useTriageUsers = () => triageUsersConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: triageUsersConfig.defaultValues,
    schema: triageUserSchema,
    columns: triageUsersConfig.columns,
    collection: triageUsersConfig.name
  }
}