/**
 * @crouton-generated
 * Collection Type Registry
 *
 * This file is auto-generated by @friendlyinternet/nuxt-crouton-cli
 * Run `crouton sync-types` to regenerate after adding collections.
 *
 * Generated: 2026-01-06
 *
 * ## How This Works
 * This file augments the CollectionTypeMap interface from @crouton/types.
 * When you use useCollectionQuery('blogPosts'), TypeScript automatically
 * knows the return type is BlogPost[] without requiring explicit generics.
 *
 * ## Registered Collections
 * - bookingsEmaillogs: BookingsEmaillog
 * - bookingsEmailtemplates: BookingsEmailtemplate
 */

import type { BookingsEmaillog, BookingsEmaillogFormData, NewBookingsEmaillog } from './layers/bookings/collections/emaillogs/types'
import type { BookingsEmailtemplate, BookingsEmailtemplateFormData, NewBookingsEmailtemplate } from './layers/bookings/collections/emailtemplates/types'

declare module '#crouton/types' {
  interface CollectionTypeMap {
    bookingsEmaillogs: {
      Item: BookingsEmaillog
      FormData: BookingsEmaillogFormData
      NewItem: NewBookingsEmaillog
    }
    bookingsEmailtemplates: {
      Item: BookingsEmailtemplate
      FormData: BookingsEmailtemplateFormData
      NewItem: NewBookingsEmailtemplate
    }
  }
}

export {}
