/**
 * @crouton-generated
 * @collection inputs
 * @layer triage
 * @generated 2026-02-11
 *
 * ## AI Context
 * - Composable: useTriageInputs
 * - Collection name: triageInputs
 * - API endpoint: /api/teams/[id]/triage-inputs
 * - Form component: TriageInputsForm
 * - List component: TriageInputsList
 * - Fields: flowId, sourceType, name, apiToken, webhookUrl, webhookSecret, emailAddress, emailSlug, sourceMetadata, active
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

// Schema exported separately - Zod 4 schemas cannot survive deep cloning
// Keep schema outside of objects that might be serialized/cloned during SSR
export const triageInputSchema = z.object({
  flowId: z.string().min(1, 'flowId is required'),
  sourceType: z.string().min(1, 'sourceType is required'),
  name: z.string().min(1, 'name is required'),
  apiToken: z.string().optional(),
  webhookUrl: z.string().optional(),
  webhookSecret: z.string().optional(),
  emailAddress: z.string().optional(),
  emailSlug: z.string().optional(),
  sourceMetadata: z.record(z.string(), z.any()).optional(),
  active: z.boolean()
})

export const triageInputsColumns = [
  { accessorKey: 'flowId', header: 'FlowId' },
  { accessorKey: 'sourceType', header: 'SourceType' },
  { accessorKey: 'name', header: 'Name' },
  { accessorKey: 'apiToken', header: 'ApiToken' },
  { accessorKey: 'webhookUrl', header: 'WebhookUrl' },
  { accessorKey: 'webhookSecret', header: 'WebhookSecret' },
  { accessorKey: 'emailAddress', header: 'EmailAddress' },
  { accessorKey: 'emailSlug', header: 'EmailSlug' },
  { accessorKey: 'sourceMetadata', header: 'SourceMetadata' },
  { accessorKey: 'active', header: 'Active' }
]

// Config object WITHOUT schema - safe for SSR serialization
const _triageInputsConfig = {
  name: 'triageInputs',
  layer: 'triage',
  apiPath: 'triage-inputs',
  componentName: 'TriageInputsForm',
  defaultValues: {
    flowId: '',
    sourceType: '',
    name: '',
    apiToken: '',
    webhookUrl: '',
    webhookSecret: '',
    emailAddress: '',
    emailSlug: '',
    sourceMetadata: {},
    active: false
  },
  columns: triageInputsColumns,
}

// Add schema as non-enumerable property so klona skips it during cloning
Object.defineProperty(_triageInputsConfig, 'schema', {
  value: triageInputSchema,
  enumerable: false,
  configurable: false,
  writable: false
})

export const triageInputsConfig = _triageInputsConfig as typeof _triageInputsConfig & { schema: typeof triageInputSchema }

export const useTriageInputs = () => triageInputsConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: triageInputsConfig.defaultValues,
    schema: triageInputSchema,
    columns: triageInputsConfig.columns,
    collection: triageInputsConfig.name
  }
}