<!--
  @crouton-generated
  @collection decisions
  @layer thinkgraph
  @generated 2026-03-12

  ## AI Context
  - Form component for decisions collection
  - Handles: create, update, delete actions
  - API endpoint: /api/teams/[id]/thinkgraph-decisions
  - Zod schema: useThinkgraphDecisions() composable
  - Fields: content, nodeType, pathType, starred, branchName, versionTag, parentId, source, model

  ## Common Modifications
  - Add field: Add UFormField in template, update schema in composable
  - Custom validation: Modify schema in composable
  - Custom field component: Use meta.component in schema JSON
  - Change layout: Modify CroutonFormLayout template slots

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonFormActionButton
    v-if="action === 'delete'"
    :action="action"
    :collection="collection"
    :items="items"
    :loading="loading"
    @click="handleSubmit"
  />

  <UForm
    v-else
    :schema="schema"
    :state="state"
    @submit="handleSubmit"
  >
    <CroutonFormLayout>
      <template #main>
      <div class="flex flex-col gap-4 p-1">
        <UFormField label="Content" name="content" class="not-last:pb-4">
          <UTextarea v-model="state.content" class="w-full" size="xl" />
        </UFormField>
      </div>
      </template>

      <template #sidebar>
      <div class="flex flex-col gap-4 p-1">
      </div>
      <div class="flex flex-col gap-4 p-1">
        <UFormField label="NodeType" name="nodeType" class="not-last:pb-4">
          <UInput v-model="state.nodeType" class="w-full" size="xl" />
        </UFormField>
        <UFormField label="PathType" name="pathType" class="not-last:pb-4">
          <UInput v-model="state.pathType" class="w-full" size="xl" />
        </UFormField>
        <UFormField label="Starred" name="starred" class="not-last:pb-4">
          <UCheckbox v-model="state.starred" />
        </UFormField>
      </div>

      <div class="flex flex-col gap-4 p-1">
        <UFormField label="BranchName" name="branchName" class="not-last:pb-4">
          <UInput v-model="state.branchName" class="w-full" size="xl" />
        </UFormField>
        <UFormField label="VersionTag" name="versionTag" class="not-last:pb-4">
          <UInput v-model="state.versionTag" class="w-full" size="xl" />
        </UFormField>
        <UFormField label="ParentId" name="parentId" class="not-last:pb-4">
          <UInput v-model="state.parentId" class="w-full" size="xl" />
        </UFormField>
      </div>

      <div class="flex flex-col gap-4 p-1">
        <UFormField label="Source" name="source" class="not-last:pb-4">
          <UInput v-model="state.source" class="w-full" size="xl" />
        </UFormField>
        <UFormField label="Model" name="model" class="not-last:pb-4">
          <UInput v-model="state.model" class="w-full" size="xl" />
        </UFormField>
      </div>
      </template>

      <template #footer>
        <CroutonFormActionButton
          :action="action"
          :collection="collection"
          :items="items"
          :loading="loading"
        />
      </template>
    </CroutonFormLayout>
  </UForm>
</template>

<script setup lang="ts">
import type { ThinkgraphDecisionFormProps, ThinkgraphDecisionFormData } from '../../types'
import useThinkgraphDecisions from '../composables/useThinkgraphDecisions'

const props = defineProps<ThinkgraphDecisionFormProps>()
const { defaultValue, schema, collection } = useThinkgraphDecisions()

// Form layout configuration
const tabs = ref(false)



// Use new mutation composable for data operations
const { create, update, deleteItems } = useCollectionMutation(collection)

// useCrouton still manages modal state
const { close, loading } = useCrouton()

// Initialize form state with proper values (no watch needed!)
const initialValues = props.action === 'update' && props.activeItem?.id
  ? { ...defaultValue, ...props.activeItem }
  : { ...defaultValue }

const state = ref<ThinkgraphDecisionFormData & { id?: string | null }>(initialValues)

const handleSubmit = async () => {
  try {
    if (props.action === 'create') {
      await create(state.value)
    } else if (props.action === 'update' && state.value.id) {
      await update(state.value.id, state.value)
    } else if (props.action === 'delete') {
      await deleteItems(props.items)
    }

    close()

  } catch (error) {
    console.error('Form submission failed:', error)
    // You can add toast notification here if available
    // toast.add({ title: 'Error', description: 'Failed to submit form', color: 'red' })
  }
}
</script>