/**
 * @crouton-generated
 * Collection Type Registry
 *
 * This file is auto-generated by @fyit/crouton-cli
 * Run `crouton sync-types` to regenerate after adding collections.
 *
 * Generated: 2026-02-18
 *
 * ## How This Works
 * This file augments the CollectionTypeMap interface from @crouton/types.
 * When you use useCollectionQuery('blogPosts'), TypeScript automatically
 * knows the return type is BlogPost[] without requiring explicit generics.
 *
 * ## Registered Collections
 * - bookingsBookings: BookingsBooking
 * - bookingsLocations: BookingsLocation
 * - bookingsSettings: BookingsSetting
 * - bookingsAppExt:bookings:bookings: BookingsAppExt:bookings:booking
 * - bookingsAppCustomers: BookingsAppCustomer
 * - bookingsAppPromotions: BookingsAppPromotion
 * - bookingsAppReviews: BookingsAppReview
 * - bookingsAppServices: BookingsAppService
 * - bookingsAppStaffs: BookingsAppStaff
 * - pagesPages: PagesPage
 */

import type { BookingsBooking, BookingsBookingFormData, NewBookingsBooking } from './layers/bookings/collections/bookings/types'
import type { BookingsLocation, BookingsLocationFormData, NewBookingsLocation } from './layers/bookings/collections/locations/types'
import type { BookingsSetting, BookingsSettingFormData, NewBookingsSetting } from './layers/bookings/collections/settings/types'
import type { BookingsAppExt:bookings:booking, BookingsAppExt:bookings:bookingFormData, NewBookingsAppExt:bookings:booking } from './layers/bookings-app/collections/__ext:bookings:bookings/types'
import type { BookingsAppCustomer, BookingsAppCustomerFormData, NewBookingsAppCustomer } from './layers/bookings-app/collections/customers/types'
import type { BookingsAppPromotion, BookingsAppPromotionFormData, NewBookingsAppPromotion } from './layers/bookings-app/collections/promotions/types'
import type { BookingsAppReview, BookingsAppReviewFormData, NewBookingsAppReview } from './layers/bookings-app/collections/reviews/types'
import type { BookingsAppService, BookingsAppServiceFormData, NewBookingsAppService } from './layers/bookings-app/collections/services/types'
import type { BookingsAppStaff, BookingsAppStaffFormData, NewBookingsAppStaff } from './layers/bookings-app/collections/staffs/types'
import type { PagesPage, PagesPageFormData, NewPagesPage } from './layers/pages/collections/pages/types'

declare module '#crouton/types' {
  interface CollectionTypeMap {
    bookingsBookings: {
      Item: BookingsBooking
      FormData: BookingsBookingFormData
      NewItem: NewBookingsBooking
    }
    bookingsLocations: {
      Item: BookingsLocation
      FormData: BookingsLocationFormData
      NewItem: NewBookingsLocation
    }
    bookingsSettings: {
      Item: BookingsSetting
      FormData: BookingsSettingFormData
      NewItem: NewBookingsSetting
    }
    bookingsAppExt:bookings:bookings: {
      Item: BookingsAppExt:bookings:booking
      FormData: BookingsAppExt:bookings:bookingFormData
      NewItem: NewBookingsAppExt:bookings:booking
    }
    bookingsAppCustomers: {
      Item: BookingsAppCustomer
      FormData: BookingsAppCustomerFormData
      NewItem: NewBookingsAppCustomer
    }
    bookingsAppPromotions: {
      Item: BookingsAppPromotion
      FormData: BookingsAppPromotionFormData
      NewItem: NewBookingsAppPromotion
    }
    bookingsAppReviews: {
      Item: BookingsAppReview
      FormData: BookingsAppReviewFormData
      NewItem: NewBookingsAppReview
    }
    bookingsAppServices: {
      Item: BookingsAppService
      FormData: BookingsAppServiceFormData
      NewItem: NewBookingsAppService
    }
    bookingsAppStaffs: {
      Item: BookingsAppStaff
      FormData: BookingsAppStaffFormData
      NewItem: NewBookingsAppStaff
    }
    pagesPages: {
      Item: PagesPage
      FormData: PagesPageFormData
      NewItem: NewPagesPage
    }
  }
}

export {}
