/**
 * @crouton-generated
 * Collection Type Registry
 *
 * This file is auto-generated by @fyit/crouton-cli
 * Run `crouton sync-types` to regenerate after adding collections.
 *
 * Generated: 2026-06-16
 *
 * ## How This Works
 * This file augments the CollectionTypeMap interface from @crouton/types.
 * When you use useCollectionQuery('blogPosts'), TypeScript automatically
 * knows the return type is BlogPost[] without requiring explicit generics.
 *
 * ## Registered Collections
 * - mainItems: MainItem
 * - pagesPages: PagesPage
 */

import type { MainItem, MainItemFormData, NewMainItem } from './layers/main/collections/items/types'
import type { PagesPage, PagesPageFormData, NewPagesPage } from './layers/pages/collections/pages/types'

declare module '#crouton/types' {
  interface CollectionTypeMap {
    mainItems: {
      Item: MainItem
      FormData: MainItemFormData
      NewItem: NewMainItem
    }
    pagesPages: {
      Item: PagesPage
      FormData: PagesPageFormData
      NewItem: NewPagesPage
    }
  }
}

export {}
