/**
 * @crouton-generated
 * @collection products
 * @layer sales
 * @generated 2026-06-24
 *
 * ## AI Context
 * - Composable: useSalesProducts
 * - Collection name: salesProducts
 * - API endpoint: /api/teams/[id]/sales-products
 * - Form component: SalesProductsForm
 * - List component: SalesProductsList
 * - Fields: id, eventId, categoryId, locationId, title, description, price, isActive, requiresRemark, remarkPrompt, hasOptions, multipleOptionsAllowed, options
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

// Schema exported separately - Zod 4 schemas cannot survive deep cloning
// Keep schema outside of objects that might be serialized/cloned during SSR
export const salesProductSchema = z.object({
  eventId: z.string().min(1, 'eventId is required'),
  categoryId: z.string().optional(),
  locationId: z.string().optional(),
  title: z.string().min(1, 'title is required'),
  description: z.string().optional(),
  price: z.number(),
  isActive: z.boolean().optional(),
  requiresRemark: z.boolean().optional(),
  remarkPrompt: z.string().optional(),
  hasOptions: z.boolean().optional(),
  multipleOptionsAllowed: z.boolean().optional(),
  options: z.array(z.any()).optional()
})

export const salesProductsColumns = [
  { accessorKey: 'id', header: 'Id' },
  { accessorKey: 'eventId', header: 'EventId' },
  { accessorKey: 'categoryId', header: 'CategoryId' },
  { accessorKey: 'locationId', header: 'LocationId' },
  { accessorKey: 'title', header: 'Title' },
  { accessorKey: 'description', header: 'Description' },
  { accessorKey: 'price', header: 'Price' },
  { accessorKey: 'isActive', header: 'IsActive' },
  { accessorKey: 'requiresRemark', header: 'RequiresRemark' },
  { accessorKey: 'remarkPrompt', header: 'RemarkPrompt' },
  { accessorKey: 'hasOptions', header: 'HasOptions' },
  { accessorKey: 'multipleOptionsAllowed', header: 'MultipleOptionsAllowed' },
  { accessorKey: 'options', header: 'Options' }
]

// Config object WITHOUT schema - safe for SSR serialization
const _salesProductsConfig = {
  name: 'salesProducts',
  layer: 'sales',
  apiPath: 'sales-products',
  componentName: 'SalesProductForm',
  defaultValues: {
    eventId: '',
    categoryId: '',
    locationId: '',
    title: '',
    description: '',
    price: 0,
    isActive: false,
    requiresRemark: false,
    remarkPrompt: '',
    hasOptions: false,
    multipleOptionsAllowed: false,
    options: []
  },
  columns: salesProductsColumns,
  dependentFieldComponents: {
    options: 'SalesProductsOptionSelect'
  },
  sortable: {
    enabled: true,
    orderField: 'order'
  },
  fields: [
      {
          "name": "eventId",
          "type": "string",
          "label": "Event",
          "area": "main"
      },
      {
          "name": "categoryId",
          "type": "string",
          "label": "Category",
          "area": "main"
      },
      {
          "name": "locationId",
          "type": "string",
          "label": "Prep Location",
          "area": "main"
      },
      {
          "name": "title",
          "type": "string",
          "label": "Product Name",
          "area": "main"
      },
      {
          "name": "description",
          "type": "text",
          "label": "Description",
          "area": "main"
      },
      {
          "name": "price",
          "type": "decimal",
          "label": "Price",
          "area": "main"
      },
      {
          "name": "isActive",
          "type": "boolean",
          "label": "Active",
          "area": "main"
      },
      {
          "name": "requiresRemark",
          "type": "boolean",
          "label": "Requires Remark",
          "area": "main"
      },
      {
          "name": "remarkPrompt",
          "type": "string",
          "label": "Remark Prompt",
          "area": "main"
      },
      {
          "name": "hasOptions",
          "type": "boolean",
          "label": "Has Options",
          "area": "main"
      },
      {
          "name": "multipleOptionsAllowed",
          "type": "boolean",
          "label": "Multiple Options",
          "area": "main"
      },
      {
          "name": "options",
          "type": "repeater",
          "label": "Options",
          "area": "main"
      }
  ],
}

// Add schema as non-enumerable property so klona skips it during cloning
Object.defineProperty(_salesProductsConfig, 'schema', {
  value: salesProductSchema,
  enumerable: false,
  configurable: false,
  writable: false
})

export const salesProductsConfig = _salesProductsConfig as typeof _salesProductsConfig & { schema: typeof salesProductSchema }

export const useSalesProducts = () => salesProductsConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: salesProductsConfig.defaultValues,
    schema: salesProductSchema,
    columns: salesProductsConfig.columns,
    collection: salesProductsConfig.name
  }
}