/**
 * @crouton-generated
 * @collection assets
 * @layer crouton
 * @generated 2026-03-11
 *
 * ## AI Context
 * - Composable: useCroutonAssets
 * - Collection name: croutonAssets
 * - API endpoint: /api/teams/[id]/crouton-assets
 * - Form component: CroutonAssetsForm
 * - List component: CroutonAssetsList
 * - Fields: userId, filename, pathname, contentType, size, category, width, height, alt, uploadedAt, updatedBy
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

// Schema exported separately - Zod 4 schemas cannot survive deep cloning
// Keep schema outside of objects that might be serialized/cloned during SSR
export const croutonAssetSchema = z.object({
  userId: z.string().min(1, 'userId is required'),
  filename: z.string().min(1, 'filename is required'),
  pathname: z.string().min(1, 'pathname is required'),
  contentType: z.string().optional(),
  size: z.number().optional(),
  category: z.string().optional(),
  width: z.number().optional(),
  height: z.number().optional(),
  uploadedAt: z.date().optional(),
  updatedBy: z.string().optional(),
  alt: z.string().optional(),
  translations: z.record(
    z.string(),
    z.object({
      alt: z.string().optional()
    })
  )
})

export const croutonAssetsColumns = [
  { accessorKey: 'userId', header: 'UserId' },
  { accessorKey: 'filename', header: 'Filename' },
  { accessorKey: 'pathname', header: 'Pathname' },
  { accessorKey: 'contentType', header: 'ContentType' },
  { accessorKey: 'size', header: 'Size' },
  { accessorKey: 'category', header: 'Category' },
  { accessorKey: 'width', header: 'Width' },
  { accessorKey: 'height', header: 'Height' },
  { accessorKey: 'alt', header: 'Alt' },
  { accessorKey: 'uploadedAt', header: 'UploadedAt' },
  { accessorKey: 'updatedBy', header: 'UpdatedBy' },
  { accessorKey: 'translations', header: 'Translations' }
]

// Config object WITHOUT schema - safe for SSR serialization
const _croutonAssetsConfig = {
  name: 'croutonAssets',
  layer: 'crouton',
  apiPath: 'crouton-assets',
  componentName: 'CroutonAssetsForm',
  defaultValues: {
    userId: '',
    filename: '',
    pathname: '',
    contentType: '',
    size: 0,
    category: '',
    width: 0,
    height: 0,
    alt: '',
    uploadedAt: null,
    updatedBy: '',
    translations: {}
  },
  columns: croutonAssetsColumns,
  kind: 'media',
  fields: [
      {
          "name": "userId",
          "type": "string",
          "label": "Uploaded By",
          "area": "meta"
      },
      {
          "name": "filename",
          "type": "string",
          "label": "Filename",
          "area": "main"
      },
      {
          "name": "pathname",
          "type": "string",
          "label": "File Path",
          "area": "main"
      },
      {
          "name": "contentType",
          "type": "string",
          "label": "MIME Type",
          "area": "sidebar"
      },
      {
          "name": "size",
          "type": "number",
          "label": "File Size (bytes)",
          "area": "sidebar"
      },
      {
          "name": "category",
          "type": "string",
          "label": "Category",
          "area": "sidebar"
      },
      {
          "name": "width",
          "type": "number",
          "label": "Width (px)",
          "area": "sidebar"
      },
      {
          "name": "height",
          "type": "number",
          "label": "Height (px)",
          "area": "sidebar"
      },
      {
          "name": "alt",
          "type": "string",
          "label": "Alt Text (for accessibility & SEO)",
          "area": "main"
      },
      {
          "name": "uploadedAt",
          "type": "date",
          "label": "Uploaded At",
          "area": "meta"
      },
      {
          "name": "updatedBy",
          "type": "string",
          "label": "Updated By",
          "area": "meta"
      }
  ],
}

// Add schema as non-enumerable property so klona skips it during cloning
Object.defineProperty(_croutonAssetsConfig, 'schema', {
  value: croutonAssetSchema,
  enumerable: false,
  configurable: false,
  writable: false
})

export const croutonAssetsConfig = _croutonAssetsConfig as typeof _croutonAssetsConfig & { schema: typeof croutonAssetSchema }

export const useCroutonAssets = () => croutonAssetsConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: croutonAssetsConfig.defaultValues,
    schema: croutonAssetSchema,
    columns: croutonAssetsConfig.columns,
    collection: croutonAssetsConfig.name
  }
}