/**
 * @crouton-generated
 * @collection events
 * @layer sales
 * @generated 2025-12-25
 *
 * ## AI Context
 * - Composable: useSalesEvents
 * - Collection name: salesEvents
 * - API endpoint: /api/teams/[id]/sales-events
 * - Form component: SalesEventsForm
 * - List component: SalesEventsList
 * - Fields: id, title, slug, description, eventType, startDate, endDate, status, isCurrent, helperPin, metadata, archivedAt
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

// Schema exported separately - Zod 4 schemas cannot survive deep cloning
// Keep schema outside of objects that might be serialized/cloned during SSR
export const salesEventSchema = z.object({
  title: z.string().min(1, 'title is required'),
  slug: z.string().min(1, 'slug is required'),
  description: z.string().optional(),
  eventType: z.string().optional(),
  startDate: z.date().optional(),
  endDate: z.date().optional(),
  status: z.string().min(1, 'status is required'),
  isCurrent: z.boolean().optional(),
  helperPin: z.string().optional(),
  metadata: z.record(z.string(), z.any()).optional(),
  archivedAt: z.date().optional()
})

export const salesEventsColumns = [
  { accessorKey: 'id', header: 'Id' },
  { accessorKey: 'title', header: 'Title' },
  { accessorKey: 'slug', header: 'Slug' },
  { accessorKey: 'description', header: 'Description' },
  { accessorKey: 'eventType', header: 'EventType' },
  { accessorKey: 'startDate', header: 'StartDate' },
  { accessorKey: 'endDate', header: 'EndDate' },
  { accessorKey: 'status', header: 'Status' },
  { accessorKey: 'isCurrent', header: 'IsCurrent' },
  { accessorKey: 'helperPin', header: 'HelperPin' },
  { accessorKey: 'metadata', header: 'Metadata' },
  { accessorKey: 'archivedAt', header: 'ArchivedAt' }
]

// Config object WITHOUT schema - safe for SSR serialization
const _salesEventsConfig = {
  name: 'salesEvents',
  layer: 'sales',
  apiPath: 'sales-events',
  componentName: 'SalesEventsForm',
  defaultValues: {
    title: '',
    slug: '',
    description: '',
    eventType: '',
    startDate: null,
    endDate: null,
    status: '',
    isCurrent: false,
    helperPin: '',
    metadata: {},
    archivedAt: null
  },
  columns: salesEventsColumns,
}

// Add schema as non-enumerable property so klona skips it during cloning
Object.defineProperty(_salesEventsConfig, 'schema', {
  value: salesEventSchema,
  enumerable: false,
  configurable: false,
  writable: false
})

export const salesEventsConfig = _salesEventsConfig as typeof _salesEventsConfig & { schema: typeof salesEventSchema }

export const useSalesEvents = () => salesEventsConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: salesEventsConfig.defaultValues,
    schema: salesEventSchema,
    columns: salesEventsConfig.columns,
    collection: salesEventsConfig.name
  }
}