<!--
  @crouton-generated
  @collection persons
  @layer content
  @generated 2026-03-11

  ## AI Context
  - List component for persons collection
  - Collection name: contentPersons
  - API endpoint: /api/teams/[id]/content-persons
  - Columns composable: useContentPersons()
  - Column fields: firstName, lastName, role, image, order

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="contentPersons"
    :columns="columns"
    :rows="persons || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="ContentPersons"
        :collection="'contentPersons'"
        createButton
      />
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import useContentPersons from '../composables/useContentPersons'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { columns } = useContentPersons()

const { items: persons, pending } = await useCollectionQuery(
  'contentPersons'
)

</script>