/**
 * @crouton-generated
 * Collection Type Registry
 *
 * This file is auto-generated by @fyit/crouton-cli
 * Run `crouton sync-types` to regenerate after adding collections.
 *
 * Generated: 2026-02-25
 *
 * ## How This Works
 * This file augments the CollectionTypeMap interface from @crouton/types.
 * When you use useCollectionQuery('blogPosts'), TypeScript automatically
 * knows the return type is BlogPost[] without requiring explicit generics.
 *
 * ## Registered Collections
 * - bookingsBookings: BookingsBooking
 * - bookingsEmaillogs: BookingsEmaillog
 * - bookingsEmailtemplates: BookingsEmailtemplate
 * - bookingsLocations: BookingsLocation
 * - bookingsSettings: BookingsSetting
 * - veloBookingrequests: VeloBookingrequest
 * - veloDepartments: VeloDepartment
 * - veloEquipments: VeloEquipment
 * - veloMembers: VeloMember
 * - veloRoomtypes: VeloRoomtype
 * - croutonAssets: CroutonAsset
 * - pagesPages: PagesPage
 */

import type { BookingsBooking, BookingsBookingFormData, NewBookingsBooking } from './layers/bookings/collections/bookings/types'
import type { BookingsEmaillog, BookingsEmaillogFormData, NewBookingsEmaillog } from './layers/bookings/collections/emaillogs/types'
import type { BookingsEmailtemplate, BookingsEmailtemplateFormData, NewBookingsEmailtemplate } from './layers/bookings/collections/emailtemplates/types'
import type { BookingsLocation, BookingsLocationFormData, NewBookingsLocation } from './layers/bookings/collections/locations/types'
import type { BookingsSetting, BookingsSettingFormData, NewBookingsSetting } from './layers/bookings/collections/settings/types'
import type { VeloBookingrequest, VeloBookingrequestFormData, NewVeloBookingrequest } from './layers/velo/collections/bookingrequests/types'
import type { VeloDepartment, VeloDepartmentFormData, NewVeloDepartment } from './layers/velo/collections/departments/types'
import type { VeloEquipment, VeloEquipmentFormData, NewVeloEquipment } from './layers/velo/collections/equipments/types'
import type { VeloMember, VeloMemberFormData, NewVeloMember } from './layers/velo/collections/members/types'
import type { VeloRoomtype, VeloRoomtypeFormData, NewVeloRoomtype } from './layers/velo/collections/roomtypes/types'
import type { CroutonAsset, CroutonAssetFormData, NewCroutonAsset } from './layers/crouton/collections/assets/types'
import type { PagesPage, PagesPageFormData, NewPagesPage } from './layers/pages/collections/pages/types'

declare module '#crouton/types' {
  interface CollectionTypeMap {
    bookingsBookings: {
      Item: BookingsBooking
      FormData: BookingsBookingFormData
      NewItem: NewBookingsBooking
    }
    bookingsEmaillogs: {
      Item: BookingsEmaillog
      FormData: BookingsEmaillogFormData
      NewItem: NewBookingsEmaillog
    }
    bookingsEmailtemplates: {
      Item: BookingsEmailtemplate
      FormData: BookingsEmailtemplateFormData
      NewItem: NewBookingsEmailtemplate
    }
    bookingsLocations: {
      Item: BookingsLocation
      FormData: BookingsLocationFormData
      NewItem: NewBookingsLocation
    }
    bookingsSettings: {
      Item: BookingsSetting
      FormData: BookingsSettingFormData
      NewItem: NewBookingsSetting
    }
    veloBookingrequests: {
      Item: VeloBookingrequest
      FormData: VeloBookingrequestFormData
      NewItem: NewVeloBookingrequest
    }
    veloDepartments: {
      Item: VeloDepartment
      FormData: VeloDepartmentFormData
      NewItem: NewVeloDepartment
    }
    veloEquipments: {
      Item: VeloEquipment
      FormData: VeloEquipmentFormData
      NewItem: NewVeloEquipment
    }
    veloMembers: {
      Item: VeloMember
      FormData: VeloMemberFormData
      NewItem: NewVeloMember
    }
    veloRoomtypes: {
      Item: VeloRoomtype
      FormData: VeloRoomtypeFormData
      NewItem: NewVeloRoomtype
    }
    croutonAssets: {
      Item: CroutonAsset
      FormData: CroutonAssetFormData
      NewItem: NewCroutonAsset
    }
    pagesPages: {
      Item: PagesPage
      FormData: PagesPageFormData
      NewItem: NewPagesPage
    }
  }
}

export {}
