/**
 * @crouton-generated
 * @collection events
 * @layer sales
 * @generated 2025-12-25
 *
 * ## AI Context
 * - Main interface: SalesEvent
 * - Form data type: SalesEventFormData
 * - New item type: NewSalesEvent
 * - Form props: SalesEventFormProps
 * - Fields: id, title, slug, description, eventType, startDate, endDate, status, isCurrent, helperPin, metadata, archivedAt
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @friendlyinternet/nuxt-crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { salesEventSchema } from './app/composables/useSalesEvents'

export interface SalesEvent {
  id: string
  teamId: string
  owner: string
  title: string
  slug: string
  description?: string
  eventType?: string
  startDate?: Date | null
  endDate?: Date | null
  status: string
  isCurrent?: boolean
  helperPin?: string
  metadata?: Record<string, any>
  archivedAt?: Date | null
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type SalesEventFormData = z.infer<typeof salesEventSchema>
export type NewSalesEvent = Omit<SalesEvent, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'>

// Props type for the Form component
export interface SalesEventFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: SalesEvent | Record<string, never> // SalesEvent for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}