/**
 * @crouton-generated
 * @collection categorize-layouts
 * @layer categorize
 * @generated 2026-03-10
 *
 * ## AI Context
 * - Composable: useCategorizeCategorizeLayouts
 * - Collection name: categorizeCategorizeLayouts
 * - API endpoint: /api/teams/[id]/categorize-categorize-layouts
 * - Form component: CategorizeCategorizeLayoutsForm
 * - List component: CategorizeCategorizeLayoutsList
 * - Fields: name, databaseId, accountId, categoryProperty, layout
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

// Schema exported separately - Zod 4 schemas cannot survive deep cloning
// Keep schema outside of objects that might be serialized/cloned during SSR
export const categorizeCategorizeLayoutSchema = z.object({
  name: z.string().optional(),
  databaseId: z.string().min(1, 'databaseId is required'),
  accountId: z.string().min(1, 'accountId is required'),
  categoryProperty: z.string().min(1, 'categoryProperty is required'),
  layout: z.record(z.string(), z.any())
})

export const categorizeCategorizeLayoutsColumns = [
  { accessorKey: 'name', header: 'Name' },
  { accessorKey: 'databaseId', header: 'DatabaseId' },
  { accessorKey: 'accountId', header: 'AccountId' },
  { accessorKey: 'categoryProperty', header: 'CategoryProperty' },
  { accessorKey: 'layout', header: 'Layout' }
]

// Config object WITHOUT schema - safe for SSR serialization
const _categorizeCategorizeLayoutsConfig = {
  name: 'categorizeCategorizeLayouts',
  layer: 'categorize',
  apiPath: 'categorize-categorize-layouts',
  componentName: 'CategorizeCategorizeLayoutsForm',
  defaultValues: {
    name: '',
    databaseId: '',
    accountId: '',
    categoryProperty: '',
    layout: {}
  },
  columns: categorizeCategorizeLayoutsColumns,
  fields: [
      {
          "name": "name",
          "type": "string",
          "label": "Name",
          "area": "main"
      },
      {
          "name": "databaseId",
          "type": "string",
          "label": "DatabaseId",
          "area": "main"
      },
      {
          "name": "accountId",
          "type": "string",
          "label": "AccountId",
          "area": "main"
      },
      {
          "name": "categoryProperty",
          "type": "string",
          "label": "CategoryProperty",
          "area": "main"
      },
      {
          "name": "layout",
          "type": "json",
          "label": "Layout",
          "area": "main"
      }
  ],
}

// Add schema as non-enumerable property so klona skips it during cloning
Object.defineProperty(_categorizeCategorizeLayoutsConfig, 'schema', {
  value: categorizeCategorizeLayoutSchema,
  enumerable: false,
  configurable: false,
  writable: false
})

export const categorizeCategorizeLayoutsConfig = _categorizeCategorizeLayoutsConfig as typeof _categorizeCategorizeLayoutsConfig & { schema: typeof categorizeCategorizeLayoutSchema }

export const useCategorizeCategorizeLayouts = () => categorizeCategorizeLayoutsConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: categorizeCategorizeLayoutsConfig.defaultValues,
    schema: categorizeCategorizeLayoutSchema,
    columns: categorizeCategorizeLayoutsConfig.columns,
    collection: categorizeCategorizeLayoutsConfig.name
  }
}