/**
 * @crouton-generated
 * @collection articles
 * @layer content
 * @generated 2026-02-20
 *
 * ## AI Context
 * - Composable: useContentArticles
 * - Collection name: contentArticles
 * - API endpoint: /api/teams/[id]/content-articles
 * - Form component: ContentArticlesForm
 * - List component: ContentArticlesList
 * - Fields: title, slug, summary, publishedAt, featured, hero, categoryId, attachment
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

// Schema exported separately - Zod 4 schemas cannot survive deep cloning
// Keep schema outside of objects that might be serialized/cloned during SSR
export const contentArticleSchema = z.object({
  title: z.string().min(1, 'title is required'),
  slug: z.string().optional(),
  summary: z.string().optional(),
  publishedAt: z.date().optional(),
  featured: z.boolean().optional(),
  hero: z.string().optional(),
  categoryId: z.string().optional(),
  attachment: z.string().optional()
})

export const contentArticlesColumns = [
  { accessorKey: 'title', header: 'Title' },
  { accessorKey: 'slug', header: 'Slug' },
  { accessorKey: 'summary', header: 'Summary' },
  { accessorKey: 'publishedAt', header: 'PublishedAt' },
  { accessorKey: 'featured', header: 'Featured' },
  { accessorKey: 'hero', header: 'Hero' },
  { accessorKey: 'categoryId', header: 'CategoryId' },
  { accessorKey: 'attachment', header: 'Attachment' }
]

// Config object WITHOUT schema - safe for SSR serialization
const _contentArticlesConfig = {
  name: 'contentArticles',
  layer: 'content',
  apiPath: 'content-articles',
  componentName: 'ContentArticlesForm',
  defaultValues: {
    title: '',
    slug: '',
    summary: '',
    publishedAt: null,
    featured: false,
    hero: '',
    categoryId: '',
    attachment: ''
  },
  columns: contentArticlesColumns,
  fields: [
      {
          "name": "title",
          "type": "string",
          "label": "Title",
          "area": "main"
      },
      {
          "name": "slug",
          "type": "string",
          "label": "URL Slug",
          "area": "main"
      },
      {
          "name": "summary",
          "type": "text",
          "label": "Summary",
          "area": "main"
      },
      {
          "name": "publishedAt",
          "type": "date",
          "label": "Published At",
          "area": "sidebar"
      },
      {
          "name": "featured",
          "type": "boolean",
          "label": "Featured",
          "area": "sidebar"
      },
      {
          "name": "hero",
          "type": "image",
          "label": "Hero Image",
          "area": "sidebar"
      },
      {
          "name": "categoryId",
          "type": "string",
          "label": "Category",
          "area": "sidebar"
      },
      {
          "name": "attachment",
          "type": "file",
          "label": "Attachment",
          "area": "sidebar"
      }
  ],
}

// Add schema as non-enumerable property so klona skips it during cloning
Object.defineProperty(_contentArticlesConfig, 'schema', {
  value: contentArticleSchema,
  enumerable: false,
  configurable: false,
  writable: false
})

export const contentArticlesConfig = _contentArticlesConfig as typeof _contentArticlesConfig & { schema: typeof contentArticleSchema }

export const useContentArticles = () => contentArticlesConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: contentArticlesConfig.defaultValues,
    schema: contentArticleSchema,
    columns: contentArticlesConfig.columns,
    collection: contentArticlesConfig.name
  }
}