/**
 * @crouton-generated
 * Collection Type Registry
 *
 * This file is auto-generated by @fyit/crouton-cli
 * Run `crouton sync-types` to regenerate after adding collections.
 *
 * Generated: 2026-03-10
 *
 * ## How This Works
 * This file augments the CollectionTypeMap interface from @crouton/types.
 * When you use useCollectionQuery('blogPosts'), TypeScript automatically
 * knows the return type is BlogPost[] without requiring explicit generics.
 *
 * ## Registered Collections
 * - contentAgendas: ContentAgenda
 * - contentArticles: ContentArticle
 * - contentCategories: ContentCategory
 * - contentTags: ContentTag
 * - croutonAssets: CroutonAsset
 * - pagesPages: PagesPage
 */

import type { ContentAgenda, ContentAgendaFormData, NewContentAgenda } from './layers/content/collections/agendas/types'
import type { ContentArticle, ContentArticleFormData, NewContentArticle } from './layers/content/collections/articles/types'
import type { ContentCategory, ContentCategoryFormData, NewContentCategory } from './layers/content/collections/categories/types'
import type { ContentTag, ContentTagFormData, NewContentTag } from './layers/content/collections/tags/types'
import type { CroutonAsset, CroutonAssetFormData, NewCroutonAsset } from './layers/crouton/collections/assets/types'
import type { PagesPage, PagesPageFormData, NewPagesPage } from './layers/pages/collections/pages/types'

declare module '#crouton/types' {
  interface CollectionTypeMap {
    contentAgendas: {
      Item: ContentAgenda
      FormData: ContentAgendaFormData
      NewItem: NewContentAgenda
    }
    contentArticles: {
      Item: ContentArticle
      FormData: ContentArticleFormData
      NewItem: NewContentArticle
    }
    contentCategories: {
      Item: ContentCategory
      FormData: ContentCategoryFormData
      NewItem: NewContentCategory
    }
    contentTags: {
      Item: ContentTag
      FormData: ContentTagFormData
      NewItem: NewContentTag
    }
    croutonAssets: {
      Item: CroutonAsset
      FormData: CroutonAssetFormData
      NewItem: NewCroutonAsset
    }
    pagesPages: {
      Item: PagesPage
      FormData: PagesPageFormData
      NewItem: NewPagesPage
    }
  }
}

export {}
