/**
 * @crouton-generated
 * @collection members
 * @layer bikeshed
 * @generated 2026-02-25
 *
 * ## AI Context
 * - Main interface: BikeshedMember
 * - Form data type: BikeshedMemberFormData
 * - New item type: NewBikeshedMember
 * - Form props: BikeshedMemberFormProps
 * - Fields: display, fields
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { bikeshedMemberSchema } from './app/composables/useBikeshedMembers'

export interface BikeshedMember {
  id: string
  teamId: string
  owner: string
  display?: string
  fields?: string
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type BikeshedMemberFormData = z.infer<typeof bikeshedMemberSchema>
export type NewBikeshedMember = Omit<BikeshedMember, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'>

// Props type for the Form component
export interface BikeshedMemberFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: BikeshedMember | Record<string, never> // BikeshedMember for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}