/**
 * @crouton-generated
 * @collection eventsettings
 * @layer sales
 * @generated 2025-12-25
 *
 * ## AI Context
 * - Main interface: SalesEventSetting
 * - Form data type: SalesEventSettingFormData
 * - New item type: NewSalesEventSetting
 * - Form props: SalesEventSettingFormProps
 * - Fields: id, eventId, settingKey, settingValue, description
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { salesEventSettingSchema } from './app/composables/useSalesEventSettings'

export interface SalesEventSetting {
  id: string
  teamId: string
  owner: string
  eventId: string
  settingKey: string
  settingValue?: string
  description?: string
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type SalesEventSettingFormData = z.infer<typeof salesEventSettingSchema>
export type NewSalesEventSetting = Omit<SalesEventSetting, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'>

// Props type for the Form component
export interface SalesEventSettingFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: SalesEventSetting | Record<string, never> // SalesEventSetting for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}