<!--
  @crouton-generated
  @collection orderitems
  @layer sales
  @generated 2026-06-24

  ## AI Context
  - List component for orderitems collection
  - Collection name: salesOrderitems
  - API endpoint: /api/teams/[id]/sales-orderitems
  - Columns composable: useSalesOrderitems()
  - Column fields: orderId, productId, quantity, unitPrice, totalPrice, remarks, selectedOptions

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="salesOrderitems"
    :columns="columns"
    :rows="orderitems || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="SalesOrderitems"
        :collection="'salesOrderitems'"
        createButton
      />
    </template>
    <template #orderId-cell="{ row }">
      <CroutonItemCardMini
        v-if="row.original.orderId"
        :id="row.original.orderId"
        collection="salesOrders"
      />
    </template>
    <template #productId-cell="{ row }">
      <CroutonItemCardMini
        v-if="row.original.productId"
        :id="row.original.productId"
        collection="salesProducts"
      />
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import useSalesOrderitems from '../composables/useSalesOrderitems'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { columns } = useSalesOrderitems()

const { items: orderitems, pending } = await useCollectionQuery(
  'salesOrderitems'
)

</script>