/**
 * @crouton-generated
 * @collection bookingrequests
 * @layer bookingtest3
 * @generated 2026-02-25
 *
 * ## AI Context
 * - Main interface: Bookingtest3BookingRequest
 * - Form data type: Bookingtest3BookingRequestFormData
 * - New item type: NewBookingtest3BookingRequest
 * - Form props: Bookingtest3BookingRequestFormProps
 * - Fields: display, fields
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { bookingtest3BookingRequestSchema } from './app/composables/useBookingtest3BookingRequests'

export interface Bookingtest3BookingRequest {
  id: string
  teamId: string
  owner: string
  display?: string
  fields?: string
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type Bookingtest3BookingRequestFormData = z.infer<typeof bookingtest3BookingRequestSchema>
export type NewBookingtest3BookingRequest = Omit<Bookingtest3BookingRequest, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'>

// Props type for the Form component
export interface Bookingtest3BookingRequestFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: Bookingtest3BookingRequest | Record<string, never> // Bookingtest3BookingRequest for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}