/**
 * Field types loaded from package manifests via the CLI manifest-loader.
 *
 * Call loadFieldTypes() during server startup before handling requests.
 * Functions like isValidFieldType() and getFieldTypeReference() use
 * the loaded data (with a hardcoded fallback if manifests are unavailable).
 */

import { createJiti } from 'jiti'

export interface FieldTypeMapping {
  db: string
  drizzle: string
  zod: string
  default: string
  tsType: string
}

// Fallback field types (used if manifest-loader is unavailable)
const FALLBACK_FIELD_TYPES: Record<string, FieldTypeMapping> = {
  string:    { db: 'VARCHAR(255)',    drizzle: 'text',      zod: 'z.string()',          default: '\'\'',  tsType: 'string' },
  text:      { db: 'TEXT',            drizzle: 'text',      zod: 'z.string()',          default: '\'\'',  tsType: 'string' },
  number:    { db: 'INTEGER',         drizzle: 'integer',   zod: 'z.number()',          default: '0',     tsType: 'number' },
  decimal:   { db: 'DECIMAL(10,2)',   drizzle: 'decimal',   zod: 'z.number()',          default: '0',     tsType: 'number' },
  boolean:   { db: 'BOOLEAN',         drizzle: 'boolean',   zod: 'z.boolean()',         default: 'false', tsType: 'boolean' },
  date:      { db: 'TIMESTAMP',       drizzle: 'timestamp', zod: 'z.date()',            default: 'null',  tsType: 'Date | null' },
  json:      { db: 'JSON',            drizzle: 'json',      zod: 'z.record(z.any())',   default: '{}',    tsType: 'Record<string, any>' },
  repeater:  { db: 'JSON',            drizzle: 'json',      zod: 'z.array(z.any())',    default: '[]',    tsType: 'any[]' },
  array:     { db: 'TEXT',            drizzle: 'text',      zod: 'z.array(z.string())', default: '[]',    tsType: 'string[]' },
  reference: { db: 'VARCHAR(255)',    drizzle: 'text',      zod: 'z.string()',          default: '\'\'',  tsType: 'string' },
  image:     { db: 'VARCHAR(255)',    drizzle: 'text',      zod: 'z.string()',          default: '\'\'',  tsType: 'string' },
  file:      { db: 'VARCHAR(255)',    drizzle: 'text',      zod: 'z.string()',          default: '\'\'',  tsType: 'string' },
}

const FALLBACK_AUTO_GENERATED = [
  'id', 'teamId', 'owner', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy',
]

// Mutable state — populated by loadFieldTypes() at startup
export let FIELD_TYPES: Record<string, FieldTypeMapping> = { ...FALLBACK_FIELD_TYPES }
export let VALID_FIELD_TYPES: string[] = Object.keys(FALLBACK_FIELD_TYPES)

let _autoGeneratedFields: string[] = [...FALLBACK_AUTO_GENERATED]

/**
 * Initialize field types from package manifests.
 * Must be called during server startup before handling requests.
 */
export async function loadFieldTypes(): Promise<void> {
  try {
    const jiti = createJiti(import.meta.url, { interopDefault: true })
    const loader = await jiti.import('@fyit/crouton-cli/lib/utils/manifest-loader') as {
      discoverManifests: (rootDir?: string) => Promise<unknown[]>
      getTypeMapping: (manifests: unknown[]) => Record<string, FieldTypeMapping>
      getAutoGeneratedFields: (manifests: unknown[]) => string[]
    }

    const manifests = await loader.discoverManifests()

    const loaded = loader.getTypeMapping(manifests)
    if (Object.keys(loaded).length > 0) {
      FIELD_TYPES = loaded
      VALID_FIELD_TYPES = Object.keys(loaded)
    }

    const autoGen = loader.getAutoGeneratedFields(manifests)
    if (autoGen.length > 0) {
      _autoGeneratedFields = autoGen
    }

    console.error(`[crouton-mcp] Loaded ${Object.keys(FIELD_TYPES).length} field types from ${manifests.length} manifests`)
  }
  catch {
    console.error('[crouton-mcp] Manifest loader unavailable, using fallback field types')
  }
}

/**
 * Get the list of auto-generated fields from manifests.
 */
export function getAutoGeneratedFields(): string[] {
  return _autoGeneratedFields
}

export function isValidFieldType(type: string): boolean {
  return VALID_FIELD_TYPES.includes(type)
}

export function getFieldTypeReference(): string {
  const lines = ['# Field Types Reference', '']
  lines.push('| Type | Zod Validation | TypeScript | Default |')
  lines.push('|------|----------------|------------|---------|')

  for (const [type, mapping] of Object.entries(FIELD_TYPES)) {
    lines.push(`| ${type} | \`${mapping.zod}\` | \`${mapping.tsType}\` | \`${mapping.default}\` |`)
  }

  lines.push('')
  lines.push('## Usage in Schema')
  lines.push('')
  lines.push('```json')
  lines.push('{')
  lines.push('  "fieldName": {')
  lines.push('    "type": "string",')
  lines.push('    "meta": {')
  lines.push('      "required": true,')
  lines.push('      "maxLength": 255')
  lines.push('    }')
  lines.push('  }')
  lines.push('}')
  lines.push('```')

  return lines.join('\n')
}
