/**
 * Generator for server-side query registry
 *
 * Scans all layers and collections to generate a registry that maps
 * collection names to lazy-loaded query functions (getAll, getByIds).
 *
 * Output location: server/utils/crouton-query-registry.ts (in project root)
 */

import fsp from 'node:fs/promises'
import path from 'node:path'
import { fileExists } from '@fyit/crouton-core/shared/utils/fs'
import { getAllLayers, getAllCollectionsInLayer } from '../utils/layer-discovery.ts'

/**
 * Convert a string to PascalCase
 */
function toPascalCase(str: string): string {
  return str
    .split(/[-_\s]+/)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('')
}

/**
 * Convert a string to camelCase
 */
function toCamelCase(str: string): string {
  const pascal = toPascalCase(str)
  return pascal.charAt(0).toLowerCase() + pascal.slice(1)
}

interface CollectionQueryInfo {
  layer: string
  collection: string
  /** camelCase key, e.g. "contentAteliers" */
  collectionKey: string
  /** PascalCase prefix for query functions, e.g. "ContentAteliers" */
  prefixedPascalCasePlural: string
  /** Import path using ~~ alias */
  importPath: string
}

/**
 * Discover all collections that have a queries.ts file
 */
export async function discoverCollectionQueries(basePath: string = '.'): Promise<CollectionQueryInfo[]> {
  const layers = await getAllLayers(basePath)
  const collections: CollectionQueryInfo[] = []

  for (const layer of layers) {
    const layerCollections = await getAllCollectionsInLayer(layer, basePath)

    for (const collection of layerCollections) {
      const queriesPath = path.resolve(basePath, 'layers', layer, 'collections', collection, 'server', 'database', 'queries.ts')

      if (!await fileExists(queriesPath)) {
        continue
      }

      const layerPascal = toPascalCase(layer)
      const collectionPascal = toPascalCase(collection)
      const collectionKey = `${toCamelCase(layer)}${collectionPascal}`
      const prefixedPascalCasePlural = `${layerPascal}${collectionPascal}`
      const importPath = `~~/layers/${layer}/collections/${collection}/server/database/queries`

      collections.push({
        layer,
        collection,
        collectionKey,
        prefixedPascalCasePlural,
        importPath,
      })
    }
  }

  return collections
}

/**
 * Generate the query registry file content from discovered collections
 */
export function generateQueryRegistry(collections: CollectionQueryInfo[]): string {
  if (collections.length === 0) {
    return `/**
 * @crouton-generated
 * Server-Side Query Registry
 *
 * This file is auto-generated by @fyit/crouton-cli.
 * Run \`crouton config\` to regenerate after adding collections.
 *
 * No collections found. Generate some collections first!
 */

export const queryRegistry: Record<string, {
  getAll: () => Promise<(teamId: string) => Promise<any[]>>
  getByIds: () => Promise<(teamId: string, ids: string[]) => Promise<any[]>>
}> = {}
`
  }

  const entries = collections.map((col) => {
    return `  ${col.collectionKey}: {
    getAll: () => import('${col.importPath}')
      .then(m => m.getAll${col.prefixedPascalCasePlural}),
    getByIds: () => import('${col.importPath}')
      .then(m => m.get${col.prefixedPascalCasePlural}ByIds),
  }`
  }).join(',\n')

  return `/**
 * @crouton-generated
 * Server-Side Query Registry
 *
 * This file is auto-generated by @fyit/crouton-cli.
 * Run \`crouton config\` to regenerate after adding collections.
 *
 * Generated: ${new Date().toISOString().split('T')[0]}
 *
 * ## How This Works
 * Each entry lazily imports the collection's query module, so you only pay
 * the import cost for collections you actually query at runtime.
 *
 * ## Usage
 * \`\`\`ts
 * import { queryRegistry } from '#server/utils/crouton-query-registry'
 *
 * const getAll = await queryRegistry.contentAteliers.getAll()
 * const items = await getAll(teamId)
 * \`\`\`
 *
 * ## Registered Collections
${collections.map(col => ` * - ${col.collectionKey} (${col.layer}/${col.collection})`).join('\n')}
 */

export const queryRegistry: Record<string, {
  getAll: () => Promise<(teamId: string) => Promise<any[]>>
  getByIds: () => Promise<(teamId: string, ids: string[]) => Promise<any[]>>
}> = {
${entries},
}
`
}

/**
 * Main function: discover collections and write the query registry file
 */
export async function generateQueryRegistryFile(basePath: string = '.', outputPath: string | null = null): Promise<{ outputPath: string; collectionsCount: number }> {
  const collections = await discoverCollectionQueries(basePath)
  const content = generateQueryRegistry(collections)

  const finalOutputPath = outputPath || path.resolve(basePath, 'server', 'utils', 'crouton-query-registry.ts')

  // Ensure directory exists
  await fsp.mkdir(path.dirname(finalOutputPath), { recursive: true })

  await fsp.writeFile(finalOutputPath, content, 'utf-8')

  return {
    outputPath: finalOutputPath,
    collectionsCount: collections.length,
  }
}
