<!--
  @crouton-generated
  @collection flowinputs
  @layer triage
  @generated 2026-02-10

  ## AI Context
  - List component for flowinputs collection
  - Collection name: triageFlowInputs
  - API endpoint: /api/teams/[id]/triage-flowinputs
  - Columns composable: useTriageFlowInputs()
  - Column fields: flowId, sourceType, name, apiToken, webhookUrl, webhookSecret, emailAddress, emailSlug, sourceMetadata, active

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="triageFlowInputs"
    :columns="columns"
    :rows="flowinputs || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="TriageFlowInputs"
        :collection="'triageFlowInputs'"
        createButton
      />
    </template>
    <template #flowId-cell="{ row }">
      <CroutonItemCardMini
        v-if="row.original.flowId"
        :id="row.original.flowId"
        collection="triageFlows"
      />
    </template>
    <template #active-cell="{ row }">
      <CroutonBoolean :value="row.original.active" />
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import useTriageFlowInputs from '../composables/useTriageFlowInputs'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { columns } = useTriageFlowInputs()

const { items: flowInputs, pending } = await useCollectionQuery(
  'triageFlowInputs'
)

</script>