<!--
  @crouton-generated
  @collection werkvergunningens
  @layer kvr
  @generated 2026-04-23

  ## AI Context
  - List component for werkvergunningens collection
  - Collection name: kvrWerkvergunningens
  - API endpoint: /api/teams/[id]/kvr-werkvergunningens
  - Columns composable: useKvrWerkvergunningens()
  - Column fields: sblNumber, datum, workType, cables, straat, huisnummer, postcode, gemeente, ploegLeden, plaats, opgemaaktOp, werkverantwoordelijkeNaam, werkverantwoordelijkeVoornaam, werkverantwoordelijkeHoedanigheid, werkverantwoordelijkeAannemer, werkverantwoordelijkeHandtekening, schakelbevoegdeNaam, schakelbevoegdeVoornaam, schakelbevoegdeHandtekening, photos, recipientEmail, emailStatus

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="kvrWerkvergunningens"
    :columns="columns"
    :rows="werkvergunningens || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="KvrWerkvergunningens"
        :collection="'kvrWerkvergunningens'"
        createButton
      />
    </template>
    <template #datum-cell="{ row }">
      <CroutonDate :date="row.original.datum"></CroutonDate>
    </template>
    <template #opgemaaktOp-cell="{ row }">
      <CroutonDate :date="row.original.opgemaaktOp"></CroutonDate>
    </template>
    <template #cables-cell="{ row }">
      <KvrWerkvergunningensCableCardMini :value="row.original.cables" />
    </template>
    <template #photos-cell="{ row }">
      <KvrWerkvergunningensPhotoCardMini :value="row.original.photos" />
    </template>
    <template #recipientEmail-cell="{ row }">
      <CroutonOptionsFieldCardMini
        v-if="row.original.recipientEmail"
        :value="row.original.recipientEmail"
        options-collection="kvrSettings"
        options-field="recipients"
      />
      <span v-else class="text-gray-400">—</span>
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import useKvrWerkvergunningens from '../composables/useKvrWerkvergunningens'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { columns } = useKvrWerkvergunningens()

const { items: werkvergunningens, pending } = await useCollectionQuery(
  'kvrWerkvergunningens'
)

</script>