/**
 * @crouton-generated
 * @collection werkvergunningens
 * @layer kvr
 * @generated 2026-04-23
 *
 * ## AI Context
 * - Main interface: KvrWerkvergunningen
 * - Form data type: KvrWerkvergunningenFormData
 * - New item type: NewKvrWerkvergunningen
 * - Form props: KvrWerkvergunningenFormProps
 * - Fields: sblNumber, datum, workType, cables, straat, huisnummer, postcode, gemeente, ploegLeden, plaats, opgemaaktOp, werkverantwoordelijkeNaam, werkverantwoordelijkeVoornaam, werkverantwoordelijkeHoedanigheid, werkverantwoordelijkeAannemer, werkverantwoordelijkeHandtekening, schakelbevoegdeNaam, schakelbevoegdeVoornaam, schakelbevoegdeHandtekening, photos, recipientEmail, emailStatus
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { kvrWerkvergunningenSchema } from './app/composables/useKvrWerkvergunningens'

export interface KvrWerkvergunningensCableItem {
  id: string
  van?: string
  naar?: string
  buitenSpanningGeaard?: boolean
  losgekoppeld?: boolean
  sleufGeidentificeerd?: boolean
}

export interface KvrWerkvergunningensPhotoItem {
  id: string
  assetId?: string
  caption?: string
}

export interface KvrWerkvergunningen {
  id: string
  teamId: string
  owner: string
  sblNumber: string
  datum: Date | null
  workType: string
  cables?: any[]
  straat: string
  huisnummer: string
  postcode: string
  gemeente: string
  ploegLeden?: string
  plaats?: string
  opgemaaktOp?: Date | null
  werkverantwoordelijkeNaam?: string
  werkverantwoordelijkeVoornaam?: string
  werkverantwoordelijkeHoedanigheid?: string
  werkverantwoordelijkeAannemer?: string
  werkverantwoordelijkeHandtekening?: Record<string, any>
  schakelbevoegdeNaam?: string
  schakelbevoegdeVoornaam?: string
  schakelbevoegdeHandtekening?: Record<string, any>
  photos?: any[]
  recipientEmail: string
  emailStatus?: string
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type KvrWerkvergunningenFormData = z.infer<typeof kvrWerkvergunningenSchema>
export type NewKvrWerkvergunningen = Omit<KvrWerkvergunningen, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'>

// Props type for the Form component
export interface KvrWerkvergunningenFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: KvrWerkvergunningen | Record<string, never> // KvrWerkvergunningen for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}