/**
 * @crouton-generated
 * @collection discussions
 * @layer triage
 * @generated 2026-02-11
 *
 * ## AI Context
 * - Main interface: TriageDiscussion
 * - Form data type: TriageDiscussionFormData
 * - New item type: NewTriageDiscussion
 * - Form props: TriageDiscussionFormProps
 * - Fields: sourceType, sourceThreadId, sourceUrl, flowInputId, title, content, authorHandle, participants, status, threadData, totalMessages, aiSummary, aiKeyPoints, aiTasks, isMultiTask, syncJobId, notionTaskIds, rawPayload, metadata, processedAt
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { triageDiscussionSchema } from './app/composables/useTriageDiscussions'

export interface TriageDiscussion {
  id: string
  teamId: string
  owner: string
  sourceType: string
  sourceThreadId: string
  sourceUrl: string
  flowInputId: string
  title: string
  content: string
  authorHandle: string
  participants?: string[]
  status: string
  threadData?: Record<string, any>
  totalMessages?: number
  aiSummary?: string
  aiKeyPoints?: string[]
  aiTasks?: Record<string, any>
  isMultiTask?: boolean
  syncJobId?: string
  notionTaskIds?: string[]
  rawPayload?: Record<string, any>
  metadata?: Record<string, any>
  processedAt?: Date | null
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type TriageDiscussionFormData = z.infer<typeof triageDiscussionSchema>
export type NewTriageDiscussion = Omit<TriageDiscussion, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'>

// Props type for the Form component
export interface TriageDiscussionFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: TriageDiscussion | Record<string, never> // TriageDiscussion for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}