/**
 * @crouton-generated
 * @collection inputs
 * @layer triage
 * @generated 2026-02-10
 *
 * ## AI Context
 * - Main interface: TriageInput
 * - Form data type: TriageInputFormData
 * - New item type: NewTriageInput
 * - Form props: TriageInputFormProps
 * - Fields: flowId, sourceType, name, apiToken, webhookUrl, webhookSecret, emailAddress, emailSlug, sourceMetadata, active
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { triageInputSchema } from './app/composables/useTriageInputs'

export interface TriageInput {
  id: string
  teamId: string
  owner: string
  flowId: string
  sourceType: string
  name: string
  apiToken?: string
  webhookUrl?: string
  webhookSecret?: string
  emailAddress?: string
  emailSlug?: string
  sourceMetadata?: Record<string, any>
  active: boolean
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type TriageInputFormData = z.infer<typeof triageInputSchema>
export type NewTriageInput = Omit<TriageInput, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'>

// Props type for the Form component
export interface TriageInputFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: TriageInput | Record<string, never> // TriageInput for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}