/**
 * @crouton-generated
 * @collection printers
 * @layer sales
 * @generated 2025-12-25
 *
 * ## AI Context
 * - Composable: useSalesPrinters
 * - Collection name: salesPrinters
 * - API endpoint: /api/teams/[id]/sales-printers
 * - Form component: SalesPrintersForm
 * - List component: SalesPrintersList
 * - Fields: id, eventId, locationId, title, ipAddress, port, status, showPrices, isActive
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

// Schema exported separately - Zod 4 schemas cannot survive deep cloning
// Keep schema outside of objects that might be serialized/cloned during SSR
export const salesPrinterSchema = z.object({
  eventId: z.string().min(1, 'eventId is required'),
  locationId: z.string().min(1, 'locationId is required'),
  title: z.string().min(1, 'title is required'),
  ipAddress: z.string().min(1, 'ipAddress is required'),
  port: z.string().optional(),
  status: z.string().optional(),
  showPrices: z.boolean().optional(),
  isActive: z.boolean().optional()
})

export const salesPrintersColumns = [
  { accessorKey: 'id', header: 'Id' },
  { accessorKey: 'eventId', header: 'EventId' },
  { accessorKey: 'locationId', header: 'LocationId' },
  { accessorKey: 'title', header: 'Title' },
  { accessorKey: 'ipAddress', header: 'IpAddress' },
  { accessorKey: 'port', header: 'Port' },
  { accessorKey: 'status', header: 'Status' },
  { accessorKey: 'showPrices', header: 'ShowPrices' },
  { accessorKey: 'isActive', header: 'IsActive' }
]

// Config object WITHOUT schema - safe for SSR serialization
const _salesPrintersConfig = {
  name: 'salesPrinters',
  layer: 'sales',
  apiPath: 'sales-printers',
  componentName: 'SalesPrintersForm',
  defaultValues: {
    eventId: '',
    locationId: '',
    title: '',
    ipAddress: '',
    port: '',
    status: '',
    showPrices: false,
    isActive: false
  },
  columns: salesPrintersColumns,
}

// Add schema as non-enumerable property so klona skips it during cloning
Object.defineProperty(_salesPrintersConfig, 'schema', {
  value: salesPrinterSchema,
  enumerable: false,
  configurable: false,
  writable: false
})

export const salesPrintersConfig = _salesPrintersConfig as typeof _salesPrintersConfig & { schema: typeof salesPrinterSchema }

export const useSalesPrinters = () => salesPrintersConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: salesPrintersConfig.defaultValues,
    schema: salesPrinterSchema,
    columns: salesPrintersConfig.columns,
    collection: salesPrintersConfig.name
  }
}