/**
 * @crouton-generated
 * @collection customers
 * @layer bookings-app
 * @generated 2026-02-18
 *
 * ## AI Context
 * - Main interface: BookingsAppCustomer
 * - Form data type: BookingsAppCustomerFormData
 * - New item type: NewBookingsAppCustomer
 * - Form props: BookingsAppCustomerFormProps
 * - Fields: display, fields
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { bookingsAppCustomerSchema } from './app/composables/useBookingsAppCustomers'

export interface BookingsAppCustomer {
  id: string
  teamId: string
  owner: string
  display?: string
  fields?: string
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type BookingsAppCustomerFormData = z.infer<typeof bookingsAppCustomerSchema>
export type NewBookingsAppCustomer = Omit<BookingsAppCustomer, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'>

// Props type for the Form component
export interface BookingsAppCustomerFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: BookingsAppCustomer | Record<string, never> // BookingsAppCustomer for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}