<!--
  @crouton-generated
  @collection promotions
  @layer bookings-app
  @generated 2026-02-18

  ## AI Context
  - List component for promotions collection
  - Collection name: bookingsAppPromotions
  - API endpoint: /api/teams/[id]/bookings-app-promotions
  - Columns composable: useBookingsAppPromotions()
  - Column fields: display, fields

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="bookingsAppPromotions"
    :columns="columns"
    :rows="promotions || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="BookingsAppPromotions"
        :collection="'bookingsAppPromotions'"
        createButton
      />
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import useBookingsAppPromotions from '../composables/useBookingsAppPromotions'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { columns } = useBookingsAppPromotions()

const { items: promotions, pending } = await useCollectionQuery(
  'bookingsAppPromotions'
)

</script>