CREATE TABLE `crouton_assets` (
	`id` text PRIMARY KEY NOT NULL,
	`teamId` text NOT NULL,
	`owner` text NOT NULL,
	`order` integer NOT NULL,
	`userId` text NOT NULL,
	`filename` text NOT NULL,
	`pathname` text NOT NULL,
	`contentType` text,
	`size` integer,
	`category` text,
	`width` integer,
	`height` integer,
	`alt` text,
	`uploadedAt` integer,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL,
	`createdBy` text NOT NULL,
	`updatedBy` text NOT NULL
);
