/**
 * @crouton-generated
 * @collection printers
 * @layer sales
 * @generated 2026-06-09
 *
 * ## AI Context
 * - Main interface: SalesPrinter
 * - Form data type: SalesPrinterFormData
 * - New item type: NewSalesPrinter
 * - Form props: SalesPrinterFormProps
 * - Fields: id, eventId, locationId, title, ipAddress, port, status, showPrices, isActive
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { salesPrinterSchema } from './app/composables/useSalesPrinters'

export interface SalesPrinter {
  id: string
  teamId: string
  owner: string
  eventId: string
  /** Kitchen routing key — null for receipt printers (they print the whole order) */
  locationId: string | null
  title: string
  ipAddress: string
  port?: string
  /** kitchen = per-location tickets (default, also NULL); receipt = combined customer receipt */
  type?: 'kitchen' | 'receipt'
  status?: string
  showPrices?: boolean
  isActive?: boolean
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type SalesPrinterFormData = z.infer<typeof salesPrinterSchema>
// New* allows the server-set fields (id, createdBy, updatedBy) as optional — the
// generated POST endpoint provides them; other callers (e.g. seed) may omit them.
export type NewSalesPrinter = Omit<SalesPrinter, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy' | 'locationId'> & { id?: string; createdBy?: string; updatedBy?: string; locationId?: string | null }

// Props type for the Form component
export interface SalesPrinterFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: SalesPrinter | Record<string, never> // SalesPrinter for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}