<!--
  @crouton-generated
  @collection categorize-layouts
  @layer categorize
  @generated 2026-03-10

  ## AI Context
  - Form component for categorize-layouts collection
  - Handles: create, update, delete actions
  - API endpoint: /api/teams/[id]/categorize-categorize-layouts
  - Zod schema: useCategorizeCategorizeLayouts() composable
  - Fields: name, databaseId, accountId, categoryProperty, layout

  ## Common Modifications
  - Add field: Add UFormField in template, update schema in composable
  - Custom validation: Modify schema in composable
  - Custom field component: Use meta.component in schema JSON
  - Change layout: Modify CroutonFormLayout template slots

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonFormActionButton
    v-if="action === 'delete'"
    :action="action"
    :collection="collection"
    :items="items"
    :loading="loading"
    @click="handleSubmit"
  />

  <UForm
    v-else
    :schema="schema"
    :state="state"
    @submit="handleSubmit"
  >
    <CroutonFormLayout>
      <template #main>
      <div class="flex flex-col gap-4 p-1">
        <UFormField label="Name" name="name" class="not-last:pb-4">
          <UInput v-model="state.name" class="w-full" size="xl" />
        </UFormField>
        <UFormField label="DatabaseId" name="databaseId" class="not-last:pb-4">
          <UInput v-model="state.databaseId" class="w-full" size="xl" />
        </UFormField>
        <UFormField label="AccountId" name="accountId" class="not-last:pb-4">
          <UInput v-model="state.accountId" class="w-full" size="xl" />
        </UFormField>
        <UFormField label="CategoryProperty" name="categoryProperty" class="not-last:pb-4">
          <UInput v-model="state.categoryProperty" class="w-full" size="xl" />
        </UFormField>
        <UFormField label="Layout" name="layout" class="not-last:pb-4">
          <UTextarea
            :model-value="typeof state.layout === 'string' ? state.layout : JSON.stringify(state.layout, null, 2)"
            @update:model-value="(val) => { try { state.layout = val ? JSON.parse(val) : {} } catch (e) { console.error('Invalid JSON:', e) } }"
            class="w-full font-mono text-sm"
            :rows="8"
            placeholder="Enter JSON object"
          />
        </UFormField>
      </div>
      </template>

      <template #footer>
        <CroutonFormActionButton
          :action="action"
          :collection="collection"
          :items="items"
          :loading="loading"
        />
      </template>
    </CroutonFormLayout>
  </UForm>
</template>

<script setup lang="ts">
import type { CategorizeCategorizeLayoutFormProps, CategorizeCategorizeLayoutFormData } from '../../types'
import useCategorizeCategorizeLayouts from '../composables/useCategorizeCategorizeLayouts'

const props = defineProps<CategorizeCategorizeLayoutFormProps>()
const { defaultValue, schema, collection } = useCategorizeCategorizeLayouts()

// Form layout configuration
const tabs = ref(false)



// Use new mutation composable for data operations
const { create, update, deleteItems } = useCollectionMutation(collection)

// useCrouton still manages modal state
const { close, loading } = useCrouton()

// Initialize form state with proper values (no watch needed!)
const initialValues = props.action === 'update' && props.activeItem?.id
  ? { ...defaultValue, ...props.activeItem }
  : { ...defaultValue }

const state = ref<CategorizeCategorizeLayoutFormData & { id?: string | null }>(initialValues)

const handleSubmit = async () => {
  try {
    if (props.action === 'create') {
      await create(state.value)
    } else if (props.action === 'update' && state.value.id) {
      await update(state.value.id, state.value)
    } else if (props.action === 'delete') {
      await deleteItems(props.items)
    }

    close()

  } catch (error) {
    console.error('Form submission failed:', error)
    // You can add toast notification here if available
    // toast.add({ title: 'Error', description: 'Failed to submit form', color: 'red' })
  }
}
</script>