<!--
  @crouton-generated
  @collection categorize-layouts
  @layer categorize
  @generated 2026-03-10

  ## AI Context
  - List component for categorize-layouts collection
  - Collection name: categorizeCategorizeLayouts
  - API endpoint: /api/teams/[id]/categorize-categorize-layouts
  - Columns composable: useCategorizeCategorizeLayouts()
  - Column fields: name, databaseId, accountId, categoryProperty, layout

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="categorizeCategorizeLayouts"
    :columns="columns"
    :rows="categorize-layouts || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="CategorizeCategorizeLayouts"
        :collection="'categorizeCategorizeLayouts'"
        createButton
      />
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import useCategorizeCategorizeLayouts from '../composables/useCategorizeCategorizeLayouts'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { columns } = useCategorizeCategorizeLayouts()

const { items: categorizeLayouts, pending } = await useCollectionQuery(
  'categorizeCategorizeLayouts'
)

</script>