<!--
  @crouton-generated
  @collection staffs
  @layer bookings-app
  @generated 2026-02-18

  ## AI Context
  - List component for staffs collection
  - Collection name: bookingsAppStaffs
  - API endpoint: /api/teams/[id]/bookings-app-staffs
  - Columns composable: useBookingsAppStaffs()
  - Column fields: display, fields

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="bookingsAppStaffs"
    :columns="columns"
    :rows="staffs || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="BookingsAppStaffs"
        :collection="'bookingsAppStaffs'"
        createButton
      />
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import useBookingsAppStaffs from '../composables/useBookingsAppStaffs'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { columns } = useBookingsAppStaffs()

const { items: staffs, pending } = await useCollectionQuery(
  'bookingsAppStaffs'
)

</script>