<!--
  @crouton-generated
  @collection tasks
  @layer projects
  @generated 2026-02-20

  ## AI Context
  - List component for tasks collection
  - Collection name: projectsTasks
  - API endpoint: /api/teams/[id]/projects-tasks
  - Columns composable: useProjectsTasks()
  - Column fields: title, description, status, dueDate, completed, priority, assigneeId, subtasks

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="projectsTasks"
    :columns="columns"
    :rows="tasks || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="ProjectsTasks"
        :collection="'projectsTasks'"
        createButton
      />
    </template>
    <template #assigneeId-cell="{ row }">
      <CroutonItemCardMini
        v-if="row.original.assigneeId"
        :id="row.original.assigneeId"
        collection="projectsContacts"
      />
    </template>
    <template #dueDate-cell="{ row }">
      <CroutonDate :date="row.original.dueDate"></CroutonDate>
    </template>
    <template #completed-cell="{ row }">
      <CroutonBoolean :value="row.original.completed" />
    </template>
    <template #subtasks-cell="{ row }">
      <ProjectsTasksSubtaskCardMini :value="row.original.subtasks" />
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import useProjectsTasks from '../composables/useProjectsTasks'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { columns } = useProjectsTasks()

const { items: tasks, pending } = await useCollectionQuery(
  'projectsTasks'
)

</script>