/**
 * @crouton-generated
 * @collection assets
 * @layer bookings
 * @generated 2026-02-18
 *
 * ## AI Context
 * - Composable: useBookingsAssets
 * - Collection name: bookingsAssets
 * - API endpoint: /api/teams/[id]/bookings-assets
 * - Form component: BookingsAssetsForm
 * - List component: BookingsAssetsList
 * - Fields: id, teamId, userId, filename, pathname, contentType, size, category, width, height, alt, uploadedAt, updatedBy
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

// Schema exported separately - Zod 4 schemas cannot survive deep cloning
// Keep schema outside of objects that might be serialized/cloned during SSR
export const bookingsAssetSchema = z.object({
  teamId: z.string().min(1, 'teamId is required'),
  userId: z.string().min(1, 'userId is required'),
  filename: z.string().min(1, 'filename is required'),
  pathname: z.string().min(1, 'pathname is required'),
  contentType: z.string().optional(),
  size: z.number().optional(),
  category: z.string().optional(),
  width: z.number().optional(),
  height: z.number().optional(),
  alt: z.string().optional(),
  uploadedAt: z.date().optional(),
  updatedBy: z.string().optional()
})

export const bookingsAssetsColumns = [
  { accessorKey: 'id', header: 'Id' },
  { accessorKey: 'teamId', header: 'TeamId' },
  { accessorKey: 'userId', header: 'UserId' },
  { accessorKey: 'filename', header: 'Filename' },
  { accessorKey: 'pathname', header: 'Pathname' },
  { accessorKey: 'contentType', header: 'ContentType' },
  { accessorKey: 'size', header: 'Size' },
  { accessorKey: 'category', header: 'Category' },
  { accessorKey: 'width', header: 'Width' },
  { accessorKey: 'height', header: 'Height' },
  { accessorKey: 'alt', header: 'Alt' },
  { accessorKey: 'uploadedAt', header: 'UploadedAt' },
  { accessorKey: 'updatedBy', header: 'UpdatedBy' }
]

// Config object WITHOUT schema - safe for SSR serialization
const _bookingsAssetsConfig = {
  name: 'bookingsAssets',
  layer: 'bookings',
  apiPath: 'bookings-assets',
  componentName: 'BookingsAssetsForm',
  defaultValues: {
    teamId: '',
    userId: '',
    filename: '',
    pathname: '',
    contentType: '',
    size: 0,
    category: '',
    width: 0,
    height: 0,
    alt: '',
    uploadedAt: null,
    updatedBy: ''
  },
  columns: bookingsAssetsColumns,
  fields: [
      {
          "name": "teamId",
          "type": "string",
          "label": "Team/Organisation",
          "area": "meta"
      },
      {
          "name": "userId",
          "type": "string",
          "label": "Uploaded By",
          "area": "meta"
      },
      {
          "name": "filename",
          "type": "string",
          "label": "Filename",
          "area": "main"
      },
      {
          "name": "pathname",
          "type": "string",
          "label": "File Path",
          "area": "main"
      },
      {
          "name": "contentType",
          "type": "string",
          "label": "MIME Type",
          "area": "sidebar"
      },
      {
          "name": "size",
          "type": "number",
          "label": "File Size (bytes)",
          "area": "sidebar"
      },
      {
          "name": "category",
          "type": "string",
          "label": "Category",
          "area": "sidebar",
          "displayAs": "optionsSelect"
      },
      {
          "name": "width",
          "type": "number",
          "label": "Width (px)",
          "area": "sidebar"
      },
      {
          "name": "height",
          "type": "number",
          "label": "Height (px)",
          "area": "sidebar"
      },
      {
          "name": "alt",
          "type": "string",
          "label": "Alt Text (for accessibility & SEO)",
          "area": "main"
      },
      {
          "name": "uploadedAt",
          "type": "date",
          "label": "Uploaded At",
          "area": "meta"
      },
      {
          "name": "updatedBy",
          "type": "string",
          "label": "Updated By",
          "area": "meta"
      }
  ],
}

// Add schema as non-enumerable property so klona skips it during cloning
Object.defineProperty(_bookingsAssetsConfig, 'schema', {
  value: bookingsAssetSchema,
  enumerable: false,
  configurable: false,
  writable: false
})

export const bookingsAssetsConfig = _bookingsAssetsConfig as typeof _bookingsAssetsConfig & { schema: typeof bookingsAssetSchema }

export const useBookingsAssets = () => bookingsAssetsConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: bookingsAssetsConfig.defaultValues,
    schema: bookingsAssetSchema,
    columns: bookingsAssetsConfig.columns,
    collection: bookingsAssetsConfig.name
  }
}