<!--
  @crouton-generated
  @collection authors
  @layer main
  @generated 2026-06-16

  ## AI Context
  - List component for authors collection
  - Collection name: mainAuthors
  - API endpoint: /api/teams/[id]/main-authors
  - Columns composable: useMainAuthors()
  - Column fields: name, bio

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="mainAuthors"
    :columns="columns"
    :rows="authors || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="MainAuthors"
        :collection="'mainAuthors'"
        createButton
      />
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import useMainAuthors from '../composables/useMainAuthors'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { columns } = useMainAuthors()

const { items: authors, pending } = await useCollectionQuery(
  'mainAuthors'
)

</script>