/**
 * @crouton-generated
 * Server-Side Query Registry
 *
 * This file is auto-generated by @fyit/crouton-cli.
 * Run `crouton config` to regenerate after adding collections.
 *
 * Generated: 2026-03-12
 *
 * ## How This Works
 * Each entry lazily imports the collection's query module, so you only pay
 * the import cost for collections you actually query at runtime.
 *
 * ## Usage
 * ```ts
 * import { queryRegistry } from '#server/utils/crouton-query-registry'
 *
 * const getAll = await queryRegistry.contentAteliers.getAll()
 * const items = await getAll(teamId)
 * ```
 *
 * ## Registered Collections
 * - thinkgraphChatconversations (thinkgraph/chatconversations)
 * - thinkgraphDecisions (thinkgraph/decisions)
 * - thinkgraphGraphs (thinkgraph/graphs)
 */

export const queryRegistry: Record<string, {
  getAll: () => Promise<(teamId: string) => Promise<any[]>>
  getByIds: () => Promise<(teamId: string, ids: string[]) => Promise<any[]>>
}> = {
  thinkgraphChatconversations: {
    getAll: () => import('~~/layers/thinkgraph/collections/chatconversations/server/database/queries')
      .then(m => m.getAllThinkgraphChatconversations),
    getByIds: () => import('~~/layers/thinkgraph/collections/chatconversations/server/database/queries')
      .then(m => m.getThinkgraphChatconversationsByIds),
  },
  thinkgraphDecisions: {
    getAll: () => import('~~/layers/thinkgraph/collections/decisions/server/database/queries')
      .then(m => m.getAllThinkgraphDecisions),
    getByIds: () => import('~~/layers/thinkgraph/collections/decisions/server/database/queries')
      .then(m => m.getThinkgraphDecisionsByIds),
  },
  thinkgraphGraphs: {
    getAll: () => import('~~/layers/thinkgraph/collections/graphs/server/database/queries')
      .then(m => m.getAllThinkgraphGraphs),
    getByIds: () => import('~~/layers/thinkgraph/collections/graphs/server/database/queries')
      .then(m => m.getThinkgraphGraphsByIds),
  },
}
