/**
 * @crouton-generated
 * Server-Side Query Registry
 *
 * This file is auto-generated by @fyit/crouton-cli.
 * Run `crouton config` to regenerate after adding collections.
 *
 * Generated: 2026-03-16
 *
 * ## How This Works
 * Each entry lazily imports the collection's query module, so you only pay
 * the import cost for collections you actually query at runtime.
 *
 * ## Usage
 * ```ts
 * import { queryRegistry } from '#server/utils/crouton-query-registry'
 *
 * const getAll = await queryRegistry.contentAteliers.getAll()
 * const items = await getAll(teamId)
 * ```
 *
 * ## Registered Collections
 * - thinkgraphCanvases (thinkgraph/canvases)
 * - thinkgraphChatconversations (thinkgraph/chatconversations)
 * - thinkgraphDecisions (thinkgraph/decisions)
 * - thinkgraphGraphs (thinkgraph/graphs)
 * - thinkgraphInjectrequests (thinkgraph/injectrequests)
 * - thinkgraphNodes (thinkgraph/nodes)
 */

export const queryRegistry: Record<string, {
  getAll: () => Promise<(teamId: string) => Promise<any[]>>
  getByIds: () => Promise<(teamId: string, ids: string[]) => Promise<any[]>>
}> = {
  thinkgraphCanvases: {
    getAll: () => import('~~/layers/thinkgraph/collections/canvases/server/database/queries')
      .then(m => m.getAllThinkgraphCanvases),
    getByIds: () => import('~~/layers/thinkgraph/collections/canvases/server/database/queries')
      .then(m => m.getThinkgraphCanvasesByIds),
  },
  thinkgraphChatconversations: {
    getAll: () => import('~~/layers/thinkgraph/collections/chatconversations/server/database/queries')
      .then(m => m.getAllThinkgraphChatconversations),
    getByIds: () => import('~~/layers/thinkgraph/collections/chatconversations/server/database/queries')
      .then(m => m.getThinkgraphChatconversationsByIds),
  },
  thinkgraphDecisions: {
    getAll: () => import('~~/layers/thinkgraph/collections/decisions/server/database/queries')
      .then(m => m.getAllThinkgraphDecisions),
    getByIds: () => import('~~/layers/thinkgraph/collections/decisions/server/database/queries')
      .then(m => m.getThinkgraphDecisionsByIds),
  },
  thinkgraphGraphs: {
    getAll: () => import('~~/layers/thinkgraph/collections/graphs/server/database/queries')
      .then(m => m.getAllThinkgraphGraphs),
    getByIds: () => import('~~/layers/thinkgraph/collections/graphs/server/database/queries')
      .then(m => m.getThinkgraphGraphsByIds),
  },
  thinkgraphInjectrequests: {
    getAll: () => import('~~/layers/thinkgraph/collections/injectrequests/server/database/queries')
      .then(m => m.getAllThinkgraphInjectrequests),
    getByIds: () => import('~~/layers/thinkgraph/collections/injectrequests/server/database/queries')
      .then(m => m.getThinkgraphInjectrequestsByIds),
  },
  thinkgraphNodes: {
    getAll: () => import('~~/layers/thinkgraph/collections/nodes/server/database/queries')
      .then(m => m.getAllThinkgraphNodes),
    getByIds: () => import('~~/layers/thinkgraph/collections/nodes/server/database/queries')
      .then(m => m.getThinkgraphNodesByIds),
  },
}
