/**
 * Manifest Injection Module
 *
 * Discovers crouton.manifest.ts files from all packages and injects
 * the merged registry into appConfig.crouton for runtime access.
 *
 * Consumers use useAppConfig().crouton.fieldTypes, .reservedFieldNames, etc.
 */
import { defineNuxtModule } from '@nuxt/kit'

export default defineNuxtModule({
  meta: {
    name: 'crouton-manifest-injection',
  },
  async setup(_options, nuxt) {
    try {
      const {
        discoverManifests,
        getFieldTypeRegistry,
        getAutoGeneratedFields,
        getReservedFieldNames,
        getReservedCollectionNames,
        getModuleRegistry,
      } = await import('@fyit/crouton-cli/lib/utils/manifest-loader')

      const manifests = await discoverManifests(nuxt.options.rootDir)

      const existing = (nuxt.options.appConfig.crouton ?? {}) as Record<string, unknown>
      // Use JSON.parse(JSON.stringify()) to strip non-enumerable properties (e.g. from jiti module
      // loading) that can create circular references when klona/full tries to deep-clone the
      // nitro config. klona uses Object.getOwnPropertyNames (includes non-enumerable), while
      // JSON.stringify only serializes enumerable properties, so this safely removes the cycles.
      const sanitize = <T>(data: T): T => JSON.parse(JSON.stringify(data))
      nuxt.options.appConfig.crouton = {
        ...existing,
        fieldTypes: sanitize(getFieldTypeRegistry(manifests)) as any,
        autoGeneratedFields: getAutoGeneratedFields(manifests),
        reservedFieldNames: getReservedFieldNames(manifests),
        reservedCollectionNames: getReservedCollectionNames(manifests),
        modules: sanitize(getModuleRegistry(manifests)) as any,
      }

      console.log(`🍞 crouton:core Loaded ${manifests.length} package manifests into app.config`)
    }
    catch {
      // Manifest loader not available (e.g., CLI not installed in production)
      if (process.env.DEBUG) {
        console.warn('🍞 crouton:core Manifest injection skipped (crouton-cli not available)')
      }
    }
  },
})
