/**
 * @crouton-generated
 * @collection locations
 * @layer bookings
 * @generated 2026-02-16
 *
 * ## AI Context
 * - Composable: useBookingsLocations
 * - Collection name: bookingsLocations
 * - API endpoint: /api/teams/[id]/bookings-locations
 * - Form component: BookingsLocationsForm
 * - List component: BookingsLocationsList
 * - Fields: title, color, street, zip, city, location, content, allowedMemberIds, slots, openDays, slotSchedule, blockedDates, inventoryMode, quantity
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

// Schema exported separately - Zod 4 schemas cannot survive deep cloning
// Keep schema outside of objects that might be serialized/cloned during SSR
export const bookingsLocationSchema = z.object({
  color: z.string().optional(),
  location: z.string().optional(),
  allowedMemberIds: z.array(z.string()).optional(),
  slots: z.array(z.any()).optional(),
  openDays: z.array(z.string()).nullish(),
  slotSchedule: z.record(z.string(), z.any()).nullish(),
  blockedDates: z.array(z.any()).optional(),
  inventoryMode: z.boolean().optional(),
  quantity: z.number().optional(),
  title: z.string().optional(),
  street: z.string().optional(),
  zip: z.string().optional(),
  city: z.string().optional(),
  content: z.string().optional(),
  translations: z.record(
    z.string(),
    z.object({
      title: z.string().min(1, 'Title is required'),
      street: z.string().optional(),
      zip: z.string().optional(),
      city: z.string().optional(),
      content: z.string().optional()
    })
  ).refine(
    (translations) => translations.en && translations.en.title,
    { message: 'English translations for title are required' }
  )
})

export const bookingsLocationsColumns = [
  { accessorKey: 'title', header: 'Title' },
  { accessorKey: 'color', header: 'Color' },
  { accessorKey: 'street', header: 'Street' },
  { accessorKey: 'zip', header: 'Zip' },
  { accessorKey: 'city', header: 'City' },
  { accessorKey: 'location', header: 'Location' },
  { accessorKey: 'content', header: 'Content' },
  { accessorKey: 'allowedMemberIds', header: 'AllowedMemberIds' },
  { accessorKey: 'slots', header: 'Slots' },
  { accessorKey: 'openDays', header: 'OpenDays' },
  { accessorKey: 'slotSchedule', header: 'SlotSchedule' },
  { accessorKey: 'blockedDates', header: 'BlockedDates' },
  { accessorKey: 'inventoryMode', header: 'InventoryMode' },
  { accessorKey: 'quantity', header: 'Quantity' },
  { accessorKey: 'translations', header: 'Translations' }
]

// Config object WITHOUT schema - safe for SSR serialization
const _bookingsLocationsConfig = {
  name: 'bookingsLocations',
  layer: 'bookings',
  apiPath: 'bookings-locations',
  componentName: 'BookingsLocationsForm',
  defaultValues: {
    title: '',
    color: '',
    street: '',
    zip: '',
    city: '',
    location: '',
    content: '',
    allowedMemberIds: [],
    slots: [],
    openDays: [],
    slotSchedule: {},
    blockedDates: [],
    inventoryMode: false,
    quantity: 0,
    translations: {}
  },
  columns: bookingsLocationsColumns,
  dependentFieldComponents: {
    slots: 'BookingsLocationsSlotSelect',
    blockedDates: 'BookingsLocationsBlockedDateSelect',
    quantity: 'BookingsLocationsQuantitySelect'
  },
  sortable: {
    enabled: true,
    orderField: 'order'
  },
}

// Add schema as non-enumerable property so klona skips it during cloning
Object.defineProperty(_bookingsLocationsConfig, 'schema', {
  value: bookingsLocationSchema,
  enumerable: false,
  configurable: false,
  writable: false
})

export const bookingsLocationsConfig = _bookingsLocationsConfig as typeof _bookingsLocationsConfig & { schema: typeof bookingsLocationSchema }

export const useBookingsLocations = () => bookingsLocationsConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: bookingsLocationsConfig.defaultValues,
    schema: bookingsLocationSchema,
    columns: bookingsLocationsConfig.columns,
    collection: bookingsLocationsConfig.name
  }
}