/**
 * @crouton-generated
 * @collection fields
 * @layer designer
 * @generated 2026-02-16
 *
 * ## AI Context
 * - Composable: useDesignerFields
 * - Collection name: designerFields
 * - API endpoint: /api/teams/[id]/designer-fields
 * - Form component: DesignerFieldsForm
 * - List component: DesignerFieldsList
 * - Fields: id, collectionId, name, type, meta, refTarget, sortOrder
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

// Schema exported separately - Zod 4 schemas cannot survive deep cloning
// Keep schema outside of objects that might be serialized/cloned during SSR
export const designerFieldSchema = z.object({
  collectionId: z.string().min(1, 'collectionId is required'),
  name: z.string().min(1, 'name is required'),
  type: z.string().min(1, 'type is required'),
  meta: z.record(z.string(), z.any()).optional(),
  refTarget: z.string().optional(),
  sortOrder: z.string().optional()
})

export const designerFieldsColumns = [
  { accessorKey: 'id', header: 'Id' },
  { accessorKey: 'collectionId', header: 'CollectionId' },
  { accessorKey: 'name', header: 'Name' },
  { accessorKey: 'type', header: 'Type' },
  { accessorKey: 'meta', header: 'Meta' },
  { accessorKey: 'refTarget', header: 'RefTarget' },
  { accessorKey: 'sortOrder', header: 'SortOrder' }
]

// Config object WITHOUT schema - safe for SSR serialization
const _designerFieldsConfig = {
  name: 'designerFields',
  layer: 'designer',
  apiPath: 'designer-fields',
  componentName: 'DesignerFieldsForm',
  defaultValues: {
    collectionId: '',
    name: '',
    type: '',
    meta: {},
    refTarget: '',
    sortOrder: ''
  },
  columns: designerFieldsColumns,
}

// Add schema as non-enumerable property so klona skips it during cloning
Object.defineProperty(_designerFieldsConfig, 'schema', {
  value: designerFieldSchema,
  enumerable: false,
  configurable: false,
  writable: false
})

export const designerFieldsConfig = _designerFieldsConfig as typeof _designerFieldsConfig & { schema: typeof designerFieldSchema }

export const useDesignerFields = () => designerFieldsConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: designerFieldsConfig.defaultValues,
    schema: designerFieldSchema,
    columns: designerFieldsConfig.columns,
    collection: designerFieldsConfig.name
  }
}