<!--
  @crouton-generated
  @collection agendas
  @layer content
  @generated 2026-03-06

  ## AI Context
  - List component for agendas collection
  - Collection name: contentAgendas
  - API endpoint: /api/teams/[id]/content-agendas
  - Columns composable: useContentAgendas()
  - Column fields: title, date, content, thumbnail, draft

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="contentAgendas"
    :columns="columns"
    :rows="agendas || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="ContentAgendas"
        :collection="'contentAgendas'"
        createButton
      />
    </template>
    <template #content-cell="{ row }">
      <CroutonEditorPreview :content="row.original.content" />
    </template>
    <template #date-cell="{ row }">
      <CroutonDate :date="row.original.date"></CroutonDate>
    </template>
    <template #draft-cell="{ row }">
      <CroutonBoolean :value="row.original.draft" />
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import useContentAgendas from '../composables/useContentAgendas'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { columns } = useContentAgendas()

const { items: agendas, pending } = await useCollectionQuery(
  'contentAgendas'
)

</script>