<!--
  @crouton-generated
  @collection locations
  @layer bookings
  @generated 2026-02-16

  ## AI Context
  - Form component for locations collection
  - Handles: create, update, delete actions
  - API endpoint: /api/teams/[id]/bookings-locations
  - Zod schema: useBookingsLocations() composable
  - Fields: title, color, street, zip, city, location, content, allowedMemberIds, slots, openDays, slotSchedule, blockedDates, inventoryMode, quantity

  ## Common Modifications
  - Add field: Add UFormField in template, update schema in composable
  - Custom validation: Modify schema in composable
  - Custom field component: Use meta.component in schema JSON
  - Change layout: Modify CroutonFormLayout template slots

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonFormActionButton
    v-if="action === 'delete'"
    :action="action"
    :collection="collection"
    :items="items"
    :loading="loading"
    @click="handleSubmit"
  />

  <UForm
    v-else
    :schema="schema"
    :state="state"
    @submit="handleSubmit"
  >
    <CroutonFormLayout>
      <template #main>
      <div class="flex flex-col gap-4 p-1">
        <UFormField label="Slots" name="slots" class="not-last:pb-4">
          <CroutonFormRepeater
            v-model="state.slots"
            component-name="BookingsLocationsSlotInput"
            add-label="Add Time Slot"
            :sortable="true"
          />
        </UFormField>
        <UFormField label="OpenDays" name="openDays" class="not-last:pb-4">
          <OpenDaysPicker v-model="state.openDays" />
        </UFormField>
        <UFormField label="SlotSchedule" name="slotSchedule" class="not-last:pb-4">
          <ScheduleGrid v-model="state.slotSchedule" />
        </UFormField>
        <UFormField label="BlockedDates" name="blockedDates" class="not-last:pb-4">
          <CroutonFormRepeater
            v-model="state.blockedDates"
            component-name="BookingsLocationsBlockedDateInput"
            add-label="Add Blocked Period"
            :sortable="false"
          />
        </UFormField>
      </div>

      <div>


      <CroutonI18nInput
        v-model="state.translations"
        :fields="['title', 'street', 'zip', 'city', 'content']"
        :default-values="{
          title: state.title || '',
          street: state.street || '',
          zip: state.zip || '',
          city: state.city || '',
          content: state.content || ''
        }"
        :field-components="{
          content: 'CroutonEditorSimple'
        }"
        show-ai-translate
        field-type="locations"
        label="Translations"
      />
      </div>
      </template>

      <template #sidebar>
      <div class="flex flex-col gap-4 p-1">
      </div>
      <div class="flex flex-col gap-4 p-1">
        <UFormField label="Color" name="color" class="not-last:pb-4">
          <UColorPicker v-model="state.color" />
        </UFormField>
      </div>

      <div class="flex flex-col gap-4 p-1">
        <UFormField label="AllowedMemberIds" name="allowedMemberIds" class="not-last:pb-4">
          <UTextarea
            :model-value="Array.isArray(state.allowedMemberIds) ? state.allowedMemberIds.join('\n') : ''"
            @update:model-value="(val) => state.allowedMemberIds = val ? val.split('\n').filter(Boolean) : []"
            class="w-full"
            :rows="6"
            placeholder="Enter one value per line"
          />
          <p class="text-sm text-gray-500 mt-1">Enter one value per line</p>
        </UFormField>
      </div>

      <div class="flex flex-col gap-4 p-1">
        <UFormField label="InventoryMode" name="inventoryMode" class="not-last:pb-4">
          <UCheckbox v-model="state.inventoryMode" />
        </UFormField>
        <UFormField label="Quantity" name="quantity" class="not-last:pb-4">
          <UInputNumber v-model="state.quantity" class="w-full" />
        </UFormField>
      </div>

      <div class="flex flex-col gap-4 p-1">


       <!-- MapBox Map Display -->
      <UFormField label="Location Map" name="location" class="not-last:pb-4">
        <CroutonMapsMap
          :center="mapCenter"
          :zoom="14"
          height="400px"
          class="rounded-lg border"
          :fly-to-on-center-change="true"
          @load="handleMapLoad"
        >
          <template #default="{ map }">
            <CroutonMapsMarker
              v-if="mapCenter[0] !== 0 || mapCenter[1] !== 0"
              :map="map"
              :position="mapCenter"
              :color="markerColor"
              :options="{ draggable: true }"
              :animate-transitions="true"
              @dragEnd="handleMarkerDragEnd"
            />
          </template>
        </CroutonMapsMap>
        <p v-if="geocoding" class="text-sm text-gray-500 mt-2">
          Geocoding address...
        </p>
      </UFormField>
      </div>
      </template>

      <template #footer>
        <CroutonFormActionButton
          :action="action"
          :collection="collection"
          :items="items"
          :loading="loading"
        />
      </template>
    </CroutonFormLayout>
  </UForm>
</template>

<script setup lang="ts">
import type { BookingsLocationFormProps, BookingsLocationFormData } from '../../types'
import useBookingsLocations from '../composables/useBookingsLocations'

const props = defineProps<BookingsLocationFormProps>()
const { defaultValue, schema, collection } = useBookingsLocations()

// Form layout configuration
const tabs = ref(false)



// Use new mutation composable for data operations
const { create, update, deleteItems } = useCollectionMutation(collection)

// useCrouton still manages modal state
const { close, loading } = useCrouton()

// Initialize form state with proper values (no watch needed!)
const initialValues = props.action === 'update' && props.activeItem?.id
  ? { ...defaultValue, ...props.activeItem }
  : { ...defaultValue }

const state = ref<BookingsLocationFormData & { id?: string | null }>(initialValues)

// Map & Geocoding functionality
const { geocode, loading: geocoding } = useGeocode()

// Parse existing coordinates from location field (handle both array and string formats)
const parseCoordinates = (value: any): [number, number] | null => {
  if (!value) return null
  if (Array.isArray(value) && value.length === 2) {
    return [Number(value[0]), Number(value[1])]
  }
  if (typeof value === 'string') {
    try {
      const parsed = JSON.parse(value)
      if (Array.isArray(parsed) && parsed.length === 2) {
        return [Number(parsed[0]), Number(parsed[1])]
      }
    } catch {
      return null
    }
  }
  return null
}

const initialCoordinates = parseCoordinates(state.value.location)
const mapCenter = ref<[number, number]>(initialCoordinates || [0, 0])
const mapInstance = ref<any>(null)

const markerColor = useMarkerColor()

// Store map instance when loaded
const handleMapLoad = (map: any) => {
  mapInstance.value = map
}

// Auto-geocode when address fields change
watchDebounced(
  () => [state.value.street, state.value.zip, state.value.city],
  async () => {
    if (canGeocode.value) {
      await handleGeocode()
    }
  },
  { debounce: 1000, maxWait: 3000 }
)

// Check if we have enough address data to geocode
const canGeocode = computed(() => {
  return !!state.value.street || !!state.value.zip
})

// Handle geocoding of address fields
const handleGeocode = async () => {
  try {
    // Build address query from all address fields
    const addressParts: string[] = []
    if (state.value.street) addressParts.push(state.value.street as string)
    if (state.value.zip) addressParts.push(state.value.zip as string)
    if (state.value.city) addressParts.push(state.value.city as string)

    const addressQuery = addressParts.join(', ')
    if (!addressQuery.trim()) return

    const result = await geocode(addressQuery)
    if (result) {
      mapCenter.value = result.coordinates

      // Update the coordinate field in the form state (store as JSON string)
      state.value.location = JSON.stringify(result.coordinates)
    }
  } catch (error) {
    console.error('Geocoding failed:', error)
  }
}

// Handle marker drag to update coordinates
const handleMarkerDragEnd = (position: { lng: number; lat: number }) => {
  mapCenter.value = [position.lng, position.lat]
  state.value.location = JSON.stringify([position.lng, position.lat])
}

const handleSubmit = async () => {
  try {
    if (props.action === 'create') {
      await create(state.value)
    } else if (props.action === 'update' && state.value.id) {
      await update(state.value.id, state.value)
    } else if (props.action === 'delete') {
      await deleteItems(props.items)
    }

    close()

  } catch (error) {
    console.error('Form submission failed:', error)
    // You can add toast notification here if available
    // toast.add({ title: 'Error', description: 'Failed to submit form', color: 'red' })
  }
}
</script>