/**
 * @crouton-generated
 * @collection posts
 * @layer blog
 * @generated 2025-12-20
 *
 * ## AI Context
 * - Main interface: BlogPost
 * - Form data type: BlogPostFormData
 * - New item type: NewBlogPost
 * - Form props: BlogPostFormProps
 * - Fields: title, content, published
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @friendlyinternet/nuxt-crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { blogPostSchema } from './app/composables/useBlogPosts'

export interface BlogPost {
  id: string
  teamId: string
  owner: string
  title: string
  content?: string
  published?: boolean
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type BlogPostFormData = z.infer<typeof blogPostSchema>
export type NewBlogPost = Omit<BlogPost, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'>

// Props type for the Form component
export interface BlogPostFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: BlogPost | Record<string, never> // BlogPost for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}