<!--
  @crouton-generated
  @collection watchedrepos
  @layer thinkgraph
  @generated 2026-04-07

  ## AI Context
  - List component for watchedrepos collection
  - Collection name: thinkgraphWatchedRepos
  - API endpoint: /api/teams/[id]/thinkgraph-watchedrepos
  - Columns composable: useThinkgraphWatchedRepos()
  - Column fields: repo, branch, lastCheckedSha, notes, active

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="thinkgraphWatchedRepos"
    :columns="columns"
    :rows="watchedrepos || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="ThinkgraphWatchedRepos"
        :collection="'thinkgraphWatchedRepos'"
        createButton
      />
    </template>
    <template #active-cell="{ row }">
      <CroutonBoolean :value="row.original.active" />
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import useThinkgraphWatchedRepos from '../composables/useThinkgraphWatchedRepos'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { columns } = useThinkgraphWatchedRepos()

const { items: watchedRepos, pending } = await useCollectionQuery(
  'thinkgraphWatchedRepos'
)

</script>