/**
 * @crouton-generated
 * @collection emaillogs
 * @layer bookings
 * @generated 2026-01-06
 *
 * ## AI Context
 * - Main interface: BookingsEmaillog
 * - Form data type: BookingsEmaillogFormData
 * - New item type: NewBookingsEmaillog
 * - Form props: BookingsEmaillogFormProps
 * - Fields: bookingId, templateId, recipientEmail, triggerType, status, sentAt, error
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @friendlyinternet/nuxt-crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { bookingsEmaillogSchema } from './app/composables/useBookingsEmaillogs'

export interface BookingsEmaillog {
  id: string
  teamId: string
  owner: string
  bookingId?: string
  templateId?: string
  recipientEmail: string
  triggerType: string
  status: string
  sentAt?: string
  error?: string
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type BookingsEmaillogFormData = z.infer<typeof bookingsEmaillogSchema>
export type NewBookingsEmaillog = Omit<BookingsEmaillog, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'>

// Props type for the Form component
export interface BookingsEmaillogFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: BookingsEmaillog | Record<string, never> // BookingsEmaillog for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}