/**
 * @crouton-generated
 * @collection options
 * @layer playground
 * @generated 2025-12-18
 *
 * ## AI Context
 * - Composable: usePlaygroundOptions
 * - Collection name: playgroundOptions
 * - API endpoint: /api/teams/[id]/playground-options
 * - Form component: PlaygroundOptionsForm
 * - List component: PlaygroundOptionsList
 * - Fields: id, title, description, icon, category
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @friendlyinternet/nuxt-crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

export const playgroundOptionSchema = z.object({
  title: z.string().min(1, 'title is required'),
  description: z.string().optional(),
  icon: z.string().optional(),
  category: z.string().optional()
})

export const playgroundOptionsColumns = [
  { accessorKey: 'id', header: 'Id' },
  { accessorKey: 'title', header: 'Title' },
  { accessorKey: 'description', header: 'Description' },
  { accessorKey: 'icon', header: 'Icon' },
  { accessorKey: 'category', header: 'Category' }
]

export const playgroundOptionsConfig = {
  name: 'playgroundOptions',
  layer: 'playground',
  apiPath: 'playground-options',
  componentName: 'PlaygroundOptionsForm',
  schema: playgroundOptionSchema,
  defaultValues: {
    title: '',
    description: '',
    icon: '',
    category: ''
  },
  columns: playgroundOptionsColumns,
}

export const usePlaygroundOptions = () => playgroundOptionsConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: playgroundOptionsConfig.defaultValues,
    schema: playgroundOptionsConfig.schema,
    columns: playgroundOptionsConfig.columns,
    collection: playgroundOptionsConfig.name
  }
}