/**
 * @crouton-generated
 * @collection projects
 * @layer designer
 * @generated 2026-02-16
 *
 * ## AI Context
 * - Main interface: DesignerProject
 * - Form data type: DesignerProjectFormData
 * - New item type: NewDesignerProject
 * - Form props: DesignerProjectFormProps
 * - Fields: id, name, currentPhase, config, messages
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { designerProjectSchema } from './app/composables/useDesignerProjects'

export interface DesignerProject {
  id: string
  teamId: string
  owner: string
  name: string
  currentPhase: string
  config?: Record<string, any>
  messages?: Record<string, any>
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type DesignerProjectFormData = z.infer<typeof designerProjectSchema>
export type NewDesignerProject = Omit<DesignerProject, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'>

// Props type for the Form component
export interface DesignerProjectFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: DesignerProject | Record<string, never> // DesignerProject for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}