/**
 * @crouton-generated
 * Collection Type Registry
 *
 * This file is auto-generated by @fyit/crouton-cli
 * Run `crouton sync-types` to regenerate after adding collections.
 *
 * Generated: 2026-02-23
 *
 * ## How This Works
 * This file augments the CollectionTypeMap interface from @crouton/types.
 * When you use useCollectionQuery('blogPosts'), TypeScript automatically
 * knows the return type is BlogPost[] without requiring explicit generics.
 *
 * ## Registered Collections
 * - bookingsBookings: BookingsBooking
 * - bookingsLocations: BookingsLocation
 * - bookingsSettings: BookingsSetting
 * - contentArticles: ContentArticle
 * - contentTestimonials: ContentTestimonial
 * - pagesPages: PagesPage
 * - peopleContacts: PeopleContact
 * - projectsTasks: ProjectsTask
 * - shopCategories: ShopCategory
 * - shopOrders: ShopOrder
 * - shopProducts: ShopProduct
 */

import type { BookingsBooking, BookingsBookingFormData, NewBookingsBooking } from './layers/bookings/collections/bookings/types'
import type { BookingsLocation, BookingsLocationFormData, NewBookingsLocation } from './layers/bookings/collections/locations/types'
import type { BookingsSetting, BookingsSettingFormData, NewBookingsSetting } from './layers/bookings/collections/settings/types'
import type { ContentArticle, ContentArticleFormData, NewContentArticle } from './layers/content/collections/articles/types'
import type { ContentTestimonial, ContentTestimonialFormData, NewContentTestimonial } from './layers/content/collections/testimonials/types'
import type { PagesPage, PagesPageFormData, NewPagesPage } from './layers/pages/collections/pages/types'
import type { PeopleContact, PeopleContactFormData, NewPeopleContact } from './layers/people/collections/contacts/types'
import type { ProjectsTask, ProjectsTaskFormData, NewProjectsTask } from './layers/projects/collections/tasks/types'
import type { ShopCategory, ShopCategoryFormData, NewShopCategory } from './layers/shop/collections/categories/types'
import type { ShopOrder, ShopOrderFormData, NewShopOrder } from './layers/shop/collections/orders/types'
import type { ShopProduct, ShopProductFormData, NewShopProduct } from './layers/shop/collections/products/types'

declare module '#crouton/types' {
  interface CollectionTypeMap {
    bookingsBookings: {
      Item: BookingsBooking
      FormData: BookingsBookingFormData
      NewItem: NewBookingsBooking
    }
    bookingsLocations: {
      Item: BookingsLocation
      FormData: BookingsLocationFormData
      NewItem: NewBookingsLocation
    }
    bookingsSettings: {
      Item: BookingsSetting
      FormData: BookingsSettingFormData
      NewItem: NewBookingsSetting
    }
    contentArticles: {
      Item: ContentArticle
      FormData: ContentArticleFormData
      NewItem: NewContentArticle
    }
    contentTestimonials: {
      Item: ContentTestimonial
      FormData: ContentTestimonialFormData
      NewItem: NewContentTestimonial
    }
    pagesPages: {
      Item: PagesPage
      FormData: PagesPageFormData
      NewItem: NewPagesPage
    }
    peopleContacts: {
      Item: PeopleContact
      FormData: PeopleContactFormData
      NewItem: NewPeopleContact
    }
    projectsTasks: {
      Item: ProjectsTask
      FormData: ProjectsTaskFormData
      NewItem: NewProjectsTask
    }
    shopCategories: {
      Item: ShopCategory
      FormData: ShopCategoryFormData
      NewItem: NewShopCategory
    }
    shopOrders: {
      Item: ShopOrder
      FormData: ShopOrderFormData
      NewItem: NewShopOrder
    }
    shopProducts: {
      Item: ShopProduct
      FormData: ShopProductFormData
      NewItem: NewShopProduct
    }
  }
}

export {}
