export default {
  // Feature flags - which crouton packages to enable
  features: {
    bookings: true,
    pages: true
  },

  // Collections generated by Schema Designer
  collections: [
    { name: 'booking', fieldsFile: './schemas/booking.json' },
    { name: 'location', fieldsFile: './schemas/location.json' },
    { name: 'settings', fieldsFile: './schemas/settings.json' },
    { name: 'pages', fieldsFile: './schemas/pages.json', formComponent: 'CroutonPagesForm', hierarchy: { enabled: true, parentField: 'parentId', orderField: 'order', pathField: 'path', depthField: 'depth' } }
  ],

  // Target layers
  targets: [
    { layer: 'bookings', collections: ['booking', 'location', 'settings'] },
    { layer: 'pages', collections: ['pages'] }
  ],

  dialect: 'sqlite'
}
