<!--
  @crouton-generated
  @collection locations
  @layer bookings
  @generated 2026-02-16

  ## AI Context
  - Form component for locations collection
  - Handles: create, update, delete actions
  - API endpoint: /api/teams/[id]/bookings-locations
  - Zod schema: useBookingsLocations() composable
  - Fields: title, color, street, zip, city, location, content, allowedMemberIds, slots, openDays, slotSchedule, blockedDates, inventoryMode, quantity, maxBookingsPerMonth

  ## Common Modifications
  - Add field: Add UFormField in template, update schema in composable
  - Custom validation: Modify schema in composable
  - Custom field component: Use meta.component in schema JSON
  - Change layout: Modify CroutonFormLayout template slots

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonFormActionButton
    v-if="action === 'delete'"
    :action="action"
    :collection="collection"
    :items="items"
    :loading="loading"
    @click="handleSubmit"
  />

  <UForm
    v-else
    :schema="schema"
    :state="state"
    @submit="handleSubmit"
    @error="handleValidationError"
  >
    <CroutonFormLayout :tabs="tabs" :navigation-items="navigationItems" :tab-errors="tabErrorCounts" v-model="activeSection">
      <template #main="{ activeSection }">
        <!-- Settings -->
        <div v-show="activeSection === 'settings'" class="flex flex-col gap-6 p-1">
          <!-- Location Details -->
          <fieldset class="flex flex-col gap-4">
            <legend class="text-sm font-semibold text-gray-900 dark:text-white mb-1">Location Details</legend>
            <p class="text-sm text-gray-500 -mt-1">Display color for this location.</p>
            <UFormField label="Color" name="color">
              <CroutonFormColorPicker v-model="state.color" />
            </UFormField>
          </fieldset>

          <USeparator />

          <!-- Address & Map -->
          <fieldset class="flex flex-col gap-4">
            <legend class="text-sm font-semibold text-gray-900 dark:text-white mb-1">Address</legend>
            <p class="text-sm text-gray-500 -mt-1">Physical address and map pin. The map updates automatically as you type.</p>
            <UFormField label="Street" name="street">
              <UInput v-model="state.street" class="w-full" />
            </UFormField>
            <div class="grid grid-cols-2 gap-4">
              <UFormField label="ZIP Code" name="zip">
                <UInput v-model="state.zip" class="w-full" />
              </UFormField>
              <UFormField label="City" name="city">
                <UInput v-model="state.city" class="w-full" />
              </UFormField>
            </div>
            <UFormField label="Location Map" name="location">
              <CroutonMapsMap
                :center="mapCenter"
                :zoom="14"
                height="400px"
                class="rounded-lg border"
                :fly-to-on-center-change="true"
                @load="handleMapLoad"
              >
                <template #default="{ map }">
                  <CroutonMapsMarker
                    v-if="mapCenter[0] !== 0 || mapCenter[1] !== 0"
                    :map="map"
                    :position="mapCenter"
                    :color="markerColor"
                    :options="{ draggable: true }"
                    :animate-transitions="true"
                    @dragEnd="handleMarkerDragEnd"
                  />
                </template>
              </CroutonMapsMap>
              <p v-if="geocoding" class="text-sm text-gray-500 mt-2">
                Geocoding address...
              </p>
            </UFormField>
          </fieldset>

          <USeparator />

          <!-- Booking Rules -->
          <fieldset class="flex flex-col gap-4">
            <legend class="text-sm font-semibold text-gray-900 dark:text-white mb-1">Booking Rules</legend>
            <p class="text-sm text-gray-500 -mt-1">Control how bookings work at this location.</p>
            <UFormField label="Inventory Mode" name="inventoryMode" help="Enable to use quantity-based availability instead of time slots.">
              <USwitch v-model="state.inventoryMode" />
            </UFormField>
            <UFormField v-show="state.inventoryMode" label="Available Units" name="quantity" help="Number of units available for booking at the same time.">
              <UInputNumber v-model="state.quantity" class="w-full" />
            </UFormField>
            <UFormField label="Max Bookings Per Month" name="maxBookingsPerMonth" help="Limit how many bookings a single user can make per calendar month. Leave empty for unlimited.">
              <UInputNumber v-model="state.maxBookingsPerMonth" class="w-full" :min="0" placeholder="Unlimited" />
            </UFormField>
          </fieldset>

          <USeparator />

          <!-- Access Control -->
          <fieldset class="flex flex-col gap-4">
            <legend class="text-sm font-semibold text-gray-900 dark:text-white mb-1">Access Control</legend>
            <p class="text-sm text-gray-500 -mt-1">Restrict which members can book this location. Leave empty to allow all team members.</p>
            <UFormField label="Allowed Member IDs" name="allowedMemberIds">
              <UTextarea
                :model-value="Array.isArray(state.allowedMemberIds) ? state.allowedMemberIds.join('\n') : ''"
                @update:model-value="(val: string) => state.allowedMemberIds = val ? val.split('\n').filter(Boolean) : []"
                class="w-full"
                :rows="6"
                placeholder="Enter one member ID per line"
              />
            </UFormField>
          </fieldset>
        </div>

        <!-- Scheduling -->
        <div v-show="activeSection === 'scheduling'" class="flex flex-col gap-4 p-1">
          <UFormField v-if="!state.inventoryMode" label="Slots" name="slots">
            <CroutonFormRepeater
              v-model="state.slots"
              component-name="BookingsLocationsSlotInput"
              add-label="Add Time Slot"
              :sortable="true"
            />
          </UFormField>
          <UFormField label="Open Days" name="openDays">
            <CroutonBookingsOpenDaysPicker v-model="state.openDays" />
          </UFormField>
          <UFormField v-if="!state.inventoryMode" label="Slot Schedule" name="slotSchedule">
            <CroutonBookingsScheduleGrid v-model="state.slotSchedule" :slots="state.slots" />
          </UFormField>
          <UFormField label="Blocked Dates" name="blockedDates">
            <CroutonFormRepeater
              v-model="state.blockedDates"
              component-name="CroutonBookingsBlockedDateInput"
              add-label="Add Blocked Period"
              :sortable="false"
            />
          </UFormField>
        </div>

        <!-- Content -->
        <div v-show="activeSection === 'content'" class="flex flex-col gap-4 p-1">
          <CroutonI18nInput
            v-model="state.translations"
            :fields="['title', 'street', 'zip', 'city', 'content']"
            :default-values="{
              title: state.title || '',
              street: state.street || '',
              zip: state.zip || '',
              city: state.city || '',
              content: state.content || ''
            }"
            :field-components="{
              content: 'CroutonEditorSimple'
            }"
            show-ai-translate
            field-type="locations"
            label="Translations"
          />
        </div>
      </template>

      <template #footer>
        <CroutonValidationErrorSummary
          v-if="validationErrors.length > 0"
          :tab-errors="tabErrorCounts"
          :navigation-items="navigationItems"
          @switch-tab="switchToTab"
        />

        <CroutonFormActionButton
          :action="action"
          :collection="collection"
          :items="items"
          :loading="loading"
          :has-validation-errors="validationErrors.length > 0"
        />
      </template>
    </CroutonFormLayout>
  </UForm>
</template>

<script setup lang="ts">
import type { BookingsLocationFormProps, BookingsLocationFormData } from '../../types'
import useBookingsLocations from '../composables/useBookingsLocations'

const props = defineProps<BookingsLocationFormProps>()
const { defaultValue, schema, collection } = useBookingsLocations()

// Form layout configuration
const navigationItems = [
  { label: 'Settings', value: 'settings', icon: 'i-lucide-settings' },
  { label: 'Scheduling', value: 'scheduling', icon: 'i-lucide-calendar' },
  { label: 'Content', value: 'content', icon: 'i-lucide-globe' }
]

const tabs = ref(true)
const activeSection = ref('settings')

// Map field names to their tab groups for error tracking
const fieldToGroup: Record<string, string> = {
  'title': 'settings',
  'color': 'settings',
  'street': 'settings',
  'zip': 'settings',
  'city': 'settings',
  'content': 'settings',
  'location': 'settings',
  'inventoryMode': 'settings',
  'quantity': 'settings',
  'maxBookingsPerMonth': 'settings',
  'allowedMemberIds': 'settings',
  'slots': 'scheduling',
  'openDays': 'scheduling',
  'slotSchedule': 'scheduling',
  'blockedDates': 'scheduling',
  'translations': 'content'
}

// Track validation errors for tab indicators
const validationErrors = ref<Array<{ name: string; message: string }>>([])

// Handle form validation errors
const handleValidationError = (event: any) => {
  if (event?.errors) {
    validationErrors.value = event.errors
  }
}

// Compute errors per tab
const tabErrorCounts = computed(() => {
  const counts: Record<string, number> = {}

  validationErrors.value.forEach((error) => {
    const tabName = fieldToGroup[error.name] || 'settings'
    counts[tabName] = (counts[tabName] || 0) + 1
  })

  return counts
})

// Switch to a specific tab (for clicking error links)
const switchToTab = (tabValue: string) => {
  activeSection.value = tabValue
}

// Use new mutation composable for data operations
const { create, update, deleteItems } = useCollectionMutation(collection)

// useCrouton still manages modal state
const { close, loading } = useCrouton()

// Initialize form state with proper values (no watch needed!)
const initialValues = props.action === 'update' && props.activeItem?.id
  ? { ...defaultValue, ...props.activeItem }
  : { ...defaultValue }

const state = ref<BookingsLocationFormData & { id?: string | null }>(initialValues)

// Map & Geocoding functionality
const { geocode, loading: geocoding } = useGeocode()

// Parse existing coordinates from location field (handle both array and string formats)
const parseCoordinates = (value: any): [number, number] | null => {
  if (!value) return null
  if (Array.isArray(value) && value.length === 2) {
    return [Number(value[0]), Number(value[1])]
  }
  if (typeof value === 'string') {
    try {
      const parsed = JSON.parse(value)
      if (Array.isArray(parsed) && parsed.length === 2) {
        return [Number(parsed[0]), Number(parsed[1])]
      }
    } catch {
      return null
    }
  }
  return null
}

const initialCoordinates = parseCoordinates(state.value.location)
const mapCenter = ref<[number, number]>(initialCoordinates || [0, 0])
const mapInstance = ref<any>(null)

const markerColor = useMarkerColor()

// Store map instance when loaded
const handleMapLoad = (map: any) => {
  mapInstance.value = map
}

// Auto-geocode when address fields change
watchDebounced(
  () => [state.value.street, state.value.zip, state.value.city],
  async () => {
    if (canGeocode.value) {
      await handleGeocode()
    }
  },
  { debounce: 1000, maxWait: 3000 }
)

// Check if we have enough address data to geocode
const canGeocode = computed(() => {
  return !!state.value.street || !!state.value.zip
})

// Handle geocoding of address fields
const handleGeocode = async () => {
  try {
    // Build address query from all address fields
    const addressParts: string[] = []
    if (state.value.street) addressParts.push(state.value.street as string)
    if (state.value.zip) addressParts.push(state.value.zip as string)
    if (state.value.city) addressParts.push(state.value.city as string)

    const addressQuery = addressParts.join(', ')
    if (!addressQuery.trim()) return

    const result = await geocode(addressQuery)
    if (result) {
      mapCenter.value = result.coordinates

      // Update the coordinate field in the form state (store as JSON string)
      state.value.location = JSON.stringify(result.coordinates)
    }
  } catch (error) {
    console.error('Geocoding failed:', error)
  }
}

// Handle marker drag to update coordinates
const handleMarkerDragEnd = (position: { lng: number; lat: number }) => {
  mapCenter.value = [position.lng, position.lat]
  state.value.location = JSON.stringify([position.lng, position.lat])
}

const handleSubmit = async () => {
  try {
    if (props.action === 'create') {
      await create(state.value)
    } else if (props.action === 'update' && state.value.id) {
      await update(state.value.id, state.value)
    } else if (props.action === 'delete') {
      await deleteItems(props.items)
    }

    // Clear validation errors on successful submission
    validationErrors.value = []

    close()

  } catch (error) {
    console.error('Form submission failed:', error)
  }
}
</script>
