<!--
  @crouton-generated
  @collection locations
  @layer bookings
  @generated 2026-01-20

  ## AI Context
  - Form component for locations collection
  - Handles: create, update, delete actions
  - API endpoint: /api/teams/[id]/bookings-locations
  - Zod schema: useBookingsLocations() composable
  - Fields: title, color, street, zip, city, location, content, allowedMemberIds, slots, inventoryMode, quantity

  ## Common Modifications
  - Add field: Add UFormField in template, update schema in composable
  - Custom validation: Modify schema in composable
  - Custom field component: Use meta.component in schema JSON
  - Change layout: Modify CroutonFormLayout template slots

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonFormActionButton
    v-if="action === 'delete'"
    :action="action"
    :collection="collection"
    :items="items"
    :loading="loading"
    @click="handleSubmit"
  />

  <UForm
    v-else
    :schema="schema"
    :state="state"
    @submit="handleSubmit"
  >
    <CroutonFormLayout>
      <template #main>
      <div class="flex flex-col gap-4 p-1">
        <UFormField label="Slots" name="slots" class="not-last:pb-4">
          <CroutonFormRepeater
            v-model="state.slots"
            component-name="BookingsLocationsSlotInput"
            add-label="Add Time Slot"
            :sortable="true"
          />
        </UFormField>
      </div>

      <div>


      <CroutonI18nInput
        v-model="state.translations"
        :fields="['title', 'street', 'zip', 'city', 'content']"
        :default-values="{
          title: state.title || '',
          street: state.street || '',
          zip: state.zip || '',
          city: state.city || '',
          content: state.content || ''
        }"
        :field-components="{
          content: 'CroutonEditorSimple'
        }"
        show-ai-translate
        field-type="locations"
        label="Translations"
      />
      </div>
      </template>

      <template #sidebar>
      <div class="flex flex-col gap-4 p-1">
      </div>
      <div class="flex flex-col gap-4 p-1">
        <UFormField label="Color" name="color" class="not-last:pb-4">
          <UColorPicker v-model="state.color" />
        </UFormField>
      </div>

      <div class="flex flex-col gap-4 p-1">
        <UFormField label="Location" name="location" class="not-last:pb-4">
          <UTextarea v-model="state.location" class="w-full" size="xl" />
        </UFormField>
      </div>

      <div class="flex flex-col gap-4 p-1">
        <UFormField label="AllowedMemberIds" name="allowedMemberIds" class="not-last:pb-4">
          <UTextarea
            :model-value="Array.isArray(state.allowedMemberIds) ? state.allowedMemberIds.join('\n') : ''"
            @update:model-value="(val) => state.allowedMemberIds = val ? val.split('\n').filter(Boolean) : []"
            class="w-full"
            :rows="6"
            placeholder="Enter one value per line"
          />
          <p class="text-sm text-gray-500 mt-1">Enter one value per line</p>
        </UFormField>
      </div>

      <div class="flex flex-col gap-4 p-1">
        <UFormField label="InventoryMode" name="inventoryMode" class="not-last:pb-4">
          <UCheckbox v-model="state.inventoryMode" />
        </UFormField>
        <UFormField label="Quantity" name="quantity" class="not-last:pb-4">
          <UInputNumber v-model="state.quantity" class="w-full" />
        </UFormField>
      </div>
      </template>

      <template #footer>
        <CroutonFormActionButton
          :action="action"
          :collection="collection"
          :items="items"
          :loading="loading"
        />
      </template>
    </CroutonFormLayout>
  </UForm>
</template>

<script setup lang="ts">
import type { BookingsLocationFormProps, BookingsLocationFormData } from '../../types'
import useBookingsLocations from '../composables/useBookingsLocations'

const props = defineProps<BookingsLocationFormProps>()
const { defaultValue, schema, collection } = useBookingsLocations()

// Form layout configuration
const tabs = ref(false)



// Use new mutation composable for data operations
const { create, update, deleteItems } = useCollectionMutation(collection)

// useCrouton still manages modal state
const { close, loading } = useCrouton()

// Initialize form state with proper values (no watch needed!)
const initialValues = props.action === 'update' && props.activeItem?.id
  ? { ...defaultValue, ...props.activeItem }
  : { ...defaultValue }

const state = ref<BookingsLocationFormData & { id?: string | null }>(initialValues)

const handleSubmit = async () => {
  try {
    if (props.action === 'create') {
      await create(state.value)
    } else if (props.action === 'update' && state.value.id) {
      await update(state.value.id, state.value)
    } else if (props.action === 'delete') {
      await deleteItems(props.items)
    }

    close()

  } catch (error) {
    console.error('Form submission failed:', error)
    // You can add toast notification here if available
    // toast.add({ title: 'Error', description: 'Failed to submit form', color: 'red' })
  }
}
</script>