/**
 * @crouton-generated
 * @collection customers
 * @layer bookings-app
 * @generated 2026-02-18
 *
 * ## AI Context
 * - Composable: useBookingsAppCustomers
 * - Collection name: bookingsAppCustomers
 * - API endpoint: /api/teams/[id]/bookings-app-customers
 * - Form component: BookingsAppCustomersForm
 * - List component: BookingsAppCustomersList
 * - Fields: display, fields
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

// Schema exported separately - Zod 4 schemas cannot survive deep cloning
// Keep schema outside of objects that might be serialized/cloned during SSR
export const bookingsAppCustomerSchema = z.object({
  display: z.string().optional(),
  fields: z.string().optional()
})

export const bookingsAppCustomersColumns = [
  { accessorKey: 'display', header: 'Display' },
  { accessorKey: 'fields', header: 'Fields' }
]

// Config object WITHOUT schema - safe for SSR serialization
const _bookingsAppCustomersConfig = {
  name: 'bookingsAppCustomers',
  layer: 'bookings-app',
  apiPath: 'bookings-app-customers',
  componentName: 'BookingsAppCustomersForm',
  defaultValues: {
    display: '',
    fields: ''
  },
  columns: bookingsAppCustomersColumns,
  fields: [
      {
          "name": "display",
          "type": "string",
          "label": "Display",
          "area": "main"
      },
      {
          "name": "fields",
          "type": "string",
          "label": "Fields",
          "area": "main"
      }
  ],
}

// Add schema as non-enumerable property so klona skips it during cloning
Object.defineProperty(_bookingsAppCustomersConfig, 'schema', {
  value: bookingsAppCustomerSchema,
  enumerable: false,
  configurable: false,
  writable: false
})

export const bookingsAppCustomersConfig = _bookingsAppCustomersConfig as typeof _bookingsAppCustomersConfig & { schema: typeof bookingsAppCustomerSchema }

export const useBookingsAppCustomers = () => bookingsAppCustomersConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: bookingsAppCustomersConfig.defaultValues,
    schema: bookingsAppCustomerSchema,
    columns: bookingsAppCustomersConfig.columns,
    collection: bookingsAppCustomersConfig.name
  }
}