/**
 * @crouton-generated
 * @collection usermappings
 * @layer triage
 * @generated 2026-02-10
 *
 * ## AI Context
 * - Main interface: TriageUserMapping
 * - Form data type: TriageUserMappingFormData
 * - New item type: NewTriageUserMapping
 * - Form props: TriageUserMappingFormProps
 * - Fields: sourceType, sourceWorkspaceId, sourceUserId, sourceUserEmail, sourceUserName, notionUserId, notionUserName, notionUserEmail, mappingType, confidence, active, lastSyncedAt, metadata
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { triageUserMappingSchema } from './app/composables/useTriageUserMappings'

export interface TriageUserMapping {
  id: string
  teamId: string
  owner: string
  sourceType: string
  sourceWorkspaceId: string
  sourceUserId: string
  sourceUserEmail?: string
  sourceUserName?: string
  notionUserId: string
  notionUserName?: string
  notionUserEmail?: string
  mappingType: string
  confidence?: number
  active: boolean
  lastSyncedAt?: string
  metadata?: Record<string, any>
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type TriageUserMappingFormData = z.infer<typeof triageUserMappingSchema>
export type NewTriageUserMapping = Omit<TriageUserMapping, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'>

// Props type for the Form component
export interface TriageUserMappingFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: TriageUserMapping | Record<string, never> // TriageUserMapping for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}