/**
 * @crouton-generated
 * @collection tasks
 * @layer triage
 * @generated 2026-02-11
 *
 * ## AI Context
 * - Main interface: TriageTask
 * - Form data type: TriageTaskFormData
 * - New item type: NewTriageTask
 * - Form props: TriageTaskFormProps
 * - Fields: discussionId, syncJobId, notionPageId, notionPageUrl, title, description, status, priority, assignee, summary, sourceUrl, isMultiTaskChild, taskIndex, metadata
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { triageTaskSchema } from './app/composables/useTriageTasks'

export interface TriageTask {
  id: string
  teamId: string
  owner: string
  discussionId: string
  syncJobId: string
  notionPageId: string
  notionPageUrl: string
  title: string
  description?: string
  status: string
  priority?: string
  assignee?: string
  summary?: string
  sourceUrl: string
  isMultiTaskChild: boolean
  taskIndex?: number
  metadata?: Record<string, any>
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type TriageTaskFormData = z.infer<typeof triageTaskSchema>
export type NewTriageTask = Omit<TriageTask, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'>

// Props type for the Form component
export interface TriageTaskFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: TriageTask | Record<string, never> // TriageTask for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}