<!--
  @crouton-generated
  @collection outputs
  @layer triage
  @generated 2026-02-10

  ## AI Context
  - List component for outputs collection
  - Collection name: triageOutputs
  - API endpoint: /api/teams/[id]/triage-outputs
  - Columns composable: useTriageOutputs()
  - Column fields: flowId, outputType, name, domainFilter, isDefault, outputConfig, active

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="triageOutputs"
    :columns="columns"
    :rows="outputs || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="TriageOutputs"
        :collection="'triageOutputs'"
        createButton
      />
    </template>
    <template #flowId-cell="{ row }">
      <CroutonItemCardMini
        v-if="row.original.flowId"
        :id="row.original.flowId"
        collection="triageFlows"
      />
    </template>
    <template #domainFilter-cell="{ row }">
      <div v-if="row.original.domainFilter && row.original.domainFilter.length > 0" class="flex flex-wrap gap-1">
        <UBadge
          v-for="(item, idx) in row.original.domainFilter"
          :key="idx"
          color="neutral"
          variant="subtle"
          size="md"
        >
          {{ item }}
        </UBadge>
      </div>
      <span v-else class="text-gray-400">—</span>
    </template>
    <template #isDefault-cell="{ row }">
      <CroutonBoolean :value="row.original.isDefault" />
    </template>
    <template #active-cell="{ row }">
      <CroutonBoolean :value="row.original.active" />
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import useTriageOutputs from '../composables/useTriageOutputs'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { columns } = useTriageOutputs()

const { items: outputs, pending } = await useCollectionQuery(
  'triageOutputs'
)

</script>