/**
 * @crouton-generated
 * @collection locations
 * @layer bookings
 * @generated 2026-02-25
 *
 * ## AI Context
 * - Composable: useBookingsLocations
 * - Collection name: bookingsLocations
 * - API endpoint: /api/teams/[id]/bookings-locations
 * - Form component: BookingsLocationsForm
 * - List component: BookingsLocationsList
 * - Fields: title, color, street, zip, city, location, content, allowedMemberIds, slots, openDays, slotSchedule, blockedDates, inventoryMode, quantity, maxBookingsPerMonth
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

export const bookingsLocationsSlotItemSchema = z.object({
  id: z.string(),
  label: z.string(),
  capacity: z.number().optional()
})

// Schema exported separately - Zod 4 schemas cannot survive deep cloning
// Keep schema outside of objects that might be serialized/cloned during SSR
export const bookingsLocationSchema = z.object({
  color: z.string().optional(),
  location: z.string().optional(),
  allowedMemberIds: z.array(z.string()).nullish(),
  slots: z.array(bookingsLocationsSlotItemSchema).optional(),
  openDays: z.array(z.number()).nullish(),
  slotSchedule: z.record(z.string(), z.any()).nullish(),
  blockedDates: z.array(z.any()).nullish(),
  inventoryMode: z.boolean().optional(),
  quantity: z.number().optional(),
  maxBookingsPerMonth: z.number().optional(),
  title: z.string().optional(),
  street: z.string().optional(),
  zip: z.string().optional(),
  city: z.string().optional(),
  content: z.string().optional(),
  translations: z.record(
    z.string(),
    z.object({
      title: z.string().min(1, 'Title is required'),
      street: z.string().optional(),
      zip: z.string().optional(),
      city: z.string().optional(),
      content: z.string().optional()
    })
  ).refine(
    (translations) => translations.en && translations.en.title,
    { message: 'English translations for title are required' }
  )
})

export const bookingsLocationsColumns = [
  { accessorKey: 'title', header: 'Title' },
  { accessorKey: 'color', header: 'Color' },
  { accessorKey: 'street', header: 'Street' },
  { accessorKey: 'zip', header: 'Zip' },
  { accessorKey: 'city', header: 'City' },
  { accessorKey: 'location', header: 'Location' },
  { accessorKey: 'content', header: 'Content' },
  { accessorKey: 'allowedMemberIds', header: 'AllowedMemberIds' },
  { accessorKey: 'slots', header: 'Slots' },
  { accessorKey: 'openDays', header: 'OpenDays' },
  { accessorKey: 'slotSchedule', header: 'SlotSchedule' },
  { accessorKey: 'blockedDates', header: 'BlockedDates' },
  { accessorKey: 'inventoryMode', header: 'InventoryMode' },
  { accessorKey: 'quantity', header: 'Quantity' },
  { accessorKey: 'maxBookingsPerMonth', header: 'MaxBookingsPerMonth' },
  { accessorKey: 'translations', header: 'Translations' }
]

// Config object WITHOUT schema - safe for SSR serialization
const _bookingsLocationsConfig = {
  name: 'bookingsLocations',
  layer: 'bookings',
  apiPath: 'bookings-locations',
  componentName: 'CroutonBookingsLocationForm',
  defaultValues: {
    title: '',
    color: '',
    street: '',
    zip: '',
    city: '',
    location: '',
    content: '',
    allowedMemberIds: [],
    slots: [],
    openDays: [],
    slotSchedule: {},
    blockedDates: [],
    inventoryMode: false,
    quantity: 0,
    maxBookingsPerMonth: 0,
    translations: {}
  },
  columns: bookingsLocationsColumns,
  dependentFieldComponents: {
    slots: 'BookingsLocationsSlotSelect',
    blockedDates: 'BookingsLocationsBlockedDateSelect',
    quantity: 'BookingsLocationsQuantitySelect'
  },
  fields: [
      {
          "name": "title",
          "type": "string",
          "label": "Title",
          "area": "main"
      },
      {
          "name": "color",
          "type": "string",
          "label": "Color",
          "area": "sidebar"
      },
      {
          "name": "street",
          "type": "string",
          "label": "Street",
          "area": "main"
      },
      {
          "name": "zip",
          "type": "string",
          "label": "ZIP Code",
          "area": "main"
      },
      {
          "name": "city",
          "type": "string",
          "label": "City",
          "area": "main"
      },
      {
          "name": "location",
          "type": "text",
          "label": "Coordinates (GeoJSON)",
          "area": "main"
      },
      {
          "name": "content",
          "type": "text",
          "label": "Content",
          "area": "main"
      },
      {
          "name": "allowedMemberIds",
          "type": "array",
          "label": "Allowed Member IDs",
          "area": "sidebar"
      },
      {
          "name": "slots",
          "type": "repeater",
          "label": "Available Time Slots",
          "area": "main"
      },
      {
          "name": "openDays",
          "type": "array",
          "label": "Open Days",
          "area": "main"
      },
      {
          "name": "slotSchedule",
          "type": "json",
          "label": "Slot Schedule",
          "area": "main"
      },
      {
          "name": "blockedDates",
          "type": "repeater",
          "label": "Blocked Dates",
          "area": "main"
      },
      {
          "name": "inventoryMode",
          "type": "boolean",
          "label": "Inventory Mode",
          "area": "sidebar"
      },
      {
          "name": "quantity",
          "type": "number",
          "label": "Available Units",
          "area": "sidebar"
      },
      {
          "name": "maxBookingsPerMonth",
          "type": "number",
          "label": "Max Bookings Per Month",
          "area": "sidebar"
      }
  ],
}

// Add schema as non-enumerable property so klona skips it during cloning
Object.defineProperty(_bookingsLocationsConfig, 'schema', {
  value: bookingsLocationSchema,
  enumerable: false,
  configurable: false,
  writable: false
})

export const bookingsLocationsConfig = _bookingsLocationsConfig as typeof _bookingsLocationsConfig & { schema: typeof bookingsLocationSchema }

export const useBookingsLocations = () => bookingsLocationsConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: bookingsLocationsConfig.defaultValues,
    schema: bookingsLocationSchema,
    columns: bookingsLocationsConfig.columns,
    collection: bookingsLocationsConfig.name
  }
}