/**
 * @crouton-generated
 * @collection items
 * @layer main
 * @generated 2026-06-15
 *
 * ## AI Context
 * - Main interface: MainItem
 * - Form data type: MainItemFormData
 * - New item type: NewMainItem
 * - Form props: MainItemFormProps
 * - Fields: name, done
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { mainItemSchema } from './app/composables/useMainItems'

export interface MainItem {
  id: string
  teamId: string
  owner: string
  name: string
  done?: boolean
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type MainItemFormData = z.infer<typeof mainItemSchema>
// New* allows the server-set fields (id, createdBy, updatedBy) as optional — the
// generated POST endpoint provides them; other callers (e.g. seed) may omit them.
export type NewMainItem = Omit<MainItem, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'> & { id?: string; createdBy?: string; updatedBy?: string }

// Props type for the Form component
export interface MainItemFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: MainItem | Record<string, never> // MainItem for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}