<!--
  @crouton-generated
  @collection products
  @layer sales
  @generated 2025-12-25

  ## AI Context
  - List component for products collection
  - Collection name: salesProducts
  - API endpoint: /api/teams/[id]/sales-products
  - Columns composable: useSalesProducts()
  - Column fields: eventId, categoryId, locationId, title, description, price, isActive, requiresRemark, remarkPrompt, hasOptions, multipleOptionsAllowed, options, sortOrder

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="salesProducts"
    :columns="columns"
    :rows="products || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="SalesProducts"
        :collection="'salesProducts'"
        createButton
      />
    </template>
    <template #eventId-cell="{ row }">
      <CroutonItemCardMini
        v-if="row.original.eventId"
        :id="row.original.eventId"
        collection="salesEvents"
      />
    </template>
    <template #categoryId-cell="{ row }">
      <CroutonItemCardMini
        v-if="row.original.categoryId"
        :id="row.original.categoryId"
        collection="salesCategories"
      />
    </template>
    <template #locationId-cell="{ row }">
      <CroutonItemCardMini
        v-if="row.original.locationId"
        :id="row.original.locationId"
        collection="salesLocations"
      />
    </template>
    <template #options-cell="{ row }">
      <SalesProductsOptionCardMini :value="row.original.options" />
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import useSalesProducts from '../composables/useSalesProducts'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { columns } = useSalesProducts()

const { items: products, pending } = await useCollectionQuery(
  'salesProducts'
)
</script>