#!/usr/bin/env node
/**
 * Generate writeups/architecture/routing-registry.md from .claude/routing.yaml.
 * WS6a of epic #669 (#864) — the human-readable "what runs on what model" registry.
 *
 *   node scripts/gen-routing.mjs          # write the registry
 *   node scripts/gen-routing.mjs --check  # exit 1 if the registry is stale OR routing.yaml
 *                                         # drifts from the real agent frontmatter (CI guard)
 *
 * Source of truth: .claude/routing.yaml (tiers + routes + overrides). The registry is
 * derived, never hand-edited. `--check` also enforces that each route's `tier` matches
 * the model actually pinned in .claude/agents/<route>.md — so the "current" column can't
 * silently lie. (Pin-back/sync into the agent files is the NEXT step, not this skeleton.)
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parse } from 'yaml'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = join(ROOT, '.claude/routing.yaml')
const AGENTS = join(ROOT, '.claude/agents')
const OUT = join(ROOT, 'writeups/architecture/routing-registry.md')
const check = process.argv.includes('--check')

const cfg = parse(readFileSync(SRC, 'utf8'))
const tiers = cfg.tiers || {}
const FULL = { haiku: 'claude-haiku-4-5', sonnet: 'claude-sonnet-4-6', opus: 'claude-opus-4-8' }
const full = (short) => FULL[short] || short

// Read the model actually pinned in an agent file (frontmatter `model:`), or null.
function agentModel(name) {
  const f = join(AGENTS, `${name}.md`)
  if (!existsSync(f)) return null
  const m = readFileSync(f, 'utf8').match(/^model:\s*(\S+)/m)
  return m ? m[1] : null
}

const drift = []
const rows = Object.entries(cfg.routes || {}).map(([name, r]) => {
  const t = tiers[r.tier] || {}
  const actual = agentModel(name)
  // Drift: routing.yaml claims this route is on `tier` (→ tiers[tier].claude); the
  // agent file must agree. (Routes without an agent file — e.g. future flows — skip.)
  if (actual && t.claude && actual !== t.claude) {
    drift.push(`  • ${name}: routing.yaml says ${r.tier} (${t.claude}) but .claude/agents/${name}.md pins ${actual}`)
  }
  const prop = r.proposed ? tiers[r.proposed] : null
  return {
    name,
    tier: r.tier,
    claude: full(t.claude),
    pi: t.pi || '—',
    cost: t.out_per_mtok != null ? `$${t.out_per_mtok}` : '—',
    proposed: r.proposed ? `${r.proposed} (${full(prop?.claude)})` : '—',
    why: r.why || '',
  }
})

const table = [
  '| Agent / flow | Current tier | Claude model | pi / local | $out/Mtok | Proposed | Why |',
  '|---|---|---|---|---|---|---|',
  ...rows.map(r => `| \`${r.name}\` | ${r.tier} | ${r.claude} | ${r.pi} | ${r.cost} | ${r.proposed} | ${r.why} |`),
].join('\n')

const overrides = (cfg.overrides || []).length
  ? (cfg.overrides || []).map(o => `- **${o.flow}** → \`${o.model}\` — ${o.why}`).join('\n')
  : '_none_'

const out = `<!-- GENERATED by scripts/gen-routing.mjs from .claude/routing.yaml — do not edit by hand. -->
# Model routing registry

The single view of **what runs on what model**. Source of truth: \`.claude/routing.yaml\`
(WS6a / #864). Cheaper-tier proposals are validated by the #865 eval loop before any
demotion. \`$out/Mtok\` is the Claude baseline output price — the cost lever.

## Tiers
${Object.entries(tiers).map(([k, t]) => `- **${k}** — Claude \`${full(t.claude)}\` · pi \`${t.pi}\` · ~$${t.out_per_mtok}/Mtok out — ${t.note || ''}`).join('\n')}

Default tier: **${cfg.default || 'medium'}**

## Routes
${table}

## Overrides (per-flow exact-model pins)
${overrides}

## Known gaps
The top-level workflow loop (claude.yml, decompose-on-issue.yml, fix-ci, daily sweeps)
runs on the \`claude-code-action\` **default** model — unpinned. Pinning those promotes
them into the routes table above.
`

if (check) {
  let stale = false
  if (!existsSync(OUT) || readFileSync(OUT, 'utf8') !== out) {
    console.error('✗ routing-registry.md is stale — run: node scripts/gen-routing.mjs')
    stale = true
  }
  if (drift.length) {
    console.error('✗ routing.yaml drifts from agent frontmatter:\n' + drift.join('\n'))
    stale = true
  }
  if (stale) process.exit(1)
  console.log('✓ routing registry current; no drift')
} else {
  writeFileSync(OUT, out)
  console.log(`✓ wrote ${OUT.replace(ROOT + '/', '')} (${rows.length} routes)`)
  if (drift.length) console.warn('⚠ drift vs agent frontmatter:\n' + drift.join('\n'))
}
