<!--
  @crouton-generated
  @collection articles
  @layer content
  @generated 2026-03-10

  ## AI Context
  - List component for articles collection
  - Collection name: contentArticles
  - API endpoint: /api/teams/[id]/content-articles
  - Columns composable: useContentArticles()
  - Column fields: title, date, category, content, embed, imageUrl, tags, featured, status, publishedAt

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="contentArticles"
    :columns="columns"
    :rows="articles || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="ContentArticles"
        :collection="'contentArticles'"
        createButton
      />
    </template>
    <template #content-cell="{ row }">
      <CroutonEditorPreview :content="row.original.content" />
    </template>
    <template #tags-cell="{ row }">
      <div v-if="row.original.tags && row.original.tags.length > 0" class="flex flex-wrap gap-1">
        <CroutonItemCardMini
          v-for="itemId in row.original.tags"
          :key="itemId"
          :id="itemId"
          collection="contentTags"
        />
      </div>
      <span v-else class="text-gray-400">—</span>
    </template>
    <template #date-cell="{ row }">
      <CroutonDate :date="row.original.date"></CroutonDate>
    </template>
    <template #featured-cell="{ row }">
      <CroutonBoolean :value="row.original.featured" />
    </template>
    <template #status-cell="{ row }">
      <UBadge
        :color="row.original.status === 'published' ? 'success' : row.original.status === 'archived' ? 'neutral' : 'warning'"
        variant="subtle"
        size="sm"
      >
        {{ row.original.status }}
      </UBadge>
    </template>
    <template #publishedAt-cell="{ row }">
      <CroutonDate v-if="row.original.publishedAt" :date="row.original.publishedAt" />
      <span v-else class="text-gray-400">—</span>
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import useContentArticles from '../composables/useContentArticles'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { columns } = useContentArticles()

const { items: articles, pending } = await useCollectionQuery(
  'contentArticles'
)

</script>