<!--
  @crouton-generated
  @collection fields
  @layer designer
  @generated 2026-02-16

  ## AI Context
  - List component for fields collection
  - Collection name: designerFields
  - API endpoint: /api/teams/[id]/designer-fields
  - Columns composable: useDesignerFields()
  - Column fields: collectionId, name, type, meta, refTarget, sortOrder

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="designerFields"
    :columns="columns"
    :rows="fields || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="DesignerFields"
        :collection="'designerFields'"
        createButton
      />
    </template>
    <template #collectionId-cell="{ row }">
      <CroutonItemCardMini
        v-if="row.original.collectionId"
        :id="row.original.collectionId"
        collection="designerCollections"
      />
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import useDesignerFields from '../composables/useDesignerFields'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { columns } = useDesignerFields()

const { items: fields, pending } = await useCollectionQuery(
  'designerFields'
)

</script>