/**
 * @crouton-generated
 * @collection authors
 * @layer main
 * @generated 2026-06-16
 *
 * ## AI Context
 * - Main interface: MainAuthor
 * - Form data type: MainAuthorFormData
 * - New item type: NewMainAuthor
 * - Form props: MainAuthorFormProps
 * - Fields: name, bio
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { mainAuthorSchema } from './app/composables/useMainAuthors'

export interface MainAuthor {
  id: string
  teamId: string
  owner: string
  name: string
  bio?: string
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type MainAuthorFormData = z.infer<typeof mainAuthorSchema>
// New* allows the server-set fields (id, createdBy, updatedBy) as optional — the
// generated POST endpoint provides them; other callers (e.g. seed) may omit them.
export type NewMainAuthor = Omit<MainAuthor, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'> & { id?: string; createdBy?: string; updatedBy?: string }

// Props type for the Form component
export interface MainAuthorFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: MainAuthor | Record<string, never> // MainAuthor for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}