<!--
  @crouton-generated
  @collection events
  @layer sales
  @generated 2026-05-19

  ## AI Context
  - Form component for events collection
  - Handles: create, update, delete actions
  - API endpoint: /api/teams/[id]/sales-events
  - Zod schema: useSalesEvents() composable
  - Fields: title, slug, description, eventType, startDate, endDate, status, isCurrent, helperPin, metadata, archivedAt

  ## Common Modifications
  - Add field: Add UFormField in template, update schema in composable
  - Custom validation: Modify schema in composable
  - Custom field component: Use meta.component in schema JSON
  - Change layout: Modify CroutonFormLayout template slots

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonFormActionButton
    v-if="action === 'delete'"
    :action="action"
    :collection="collection"
    :items="items"
    :loading="loading"
    @click="handleSubmit"
  />

  <UForm
    v-else
    :schema="schema"
    :state="state"
    @submit="handleSubmit"
  >
    <CroutonFormLayout>
      <template #main>
      <div class="flex flex-col gap-6 p-1">
        <!-- Event details -->
        <section class="flex flex-col gap-4">
          <p class="text-xs font-semibold uppercase tracking-wide text-muted">Event details</p>

          <UFormField label="Event name" name="title" class="not-last:pb-4">
            <UInput v-model="state.title" class="w-full" size="xl" placeholder="e.g. Summer Market 2026" />
          </UFormField>

          <UFormField
            label="URL slug"
            name="slug"
            help="Used in the public order link. Auto-filled from the name — edit if you want."
            class="not-last:pb-4"
          >
            <UInput
              v-model="state.slug"
              class="w-full"
              size="xl"
              :ui="{ base: 'font-mono' }"
              @input="slugManuallyEdited = true"
            />
          </UFormField>

          <UFormField label="Description" name="description" class="not-last:pb-4">
            <UTextarea v-model="state.description" class="w-full" size="xl" :rows="3" placeholder="Optional — shown on the event page" />
          </UFormField>

          <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <UFormField label="Event type" name="eventType">
              <UInput v-model="state.eventType" class="w-full" size="xl" placeholder="e.g. market, festival, popup" />
            </UFormField>

            <UFormField label="Status" name="status">
              <USelect v-model="state.status" :items="statusOptions" class="w-full" size="xl" />
            </UFormField>
          </div>
        </section>

        <!-- Schedule -->
        <section class="flex flex-col gap-4">
          <p class="text-xs font-semibold uppercase tracking-wide text-muted">Schedule</p>
          <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <UFormField label="Start date" name="startDate">
              <CroutonCalendar v-model:date="state.startDate" />
            </UFormField>
            <UFormField label="End date" name="endDate">
              <CroutonCalendar v-model:date="state.endDate" />
            </UFormField>
          </div>
        </section>

        <!-- Access & options -->
        <section class="flex flex-col gap-4">
          <p class="text-xs font-semibold uppercase tracking-wide text-muted">Access &amp; options</p>

          <UFormField label="Helper PIN" name="helperPin" help="Digits only, max 6 — staff use this to log into the POS" class="not-last:pb-4">
            <UInput
              v-model="state.helperPin"
              class="w-full"
              size="xl"
              inputmode="numeric"
              pattern="[0-9]*"
              maxlength="6"
              placeholder="e.g. 1234"
              :ui="{ base: 'font-mono tracking-widest' }"
              @input="(e: any) => { state.helperPin = (e.target.value || '').replace(/\D/g, '').slice(0, 6) }"
            />
          </UFormField>

          <UFormField name="isCurrent" class="not-last:pb-4">
            <UCheckbox v-model="state.isCurrent" label="Make this the current event" />
          </UFormField>

          <UFormField name="requiresClient" class="not-last:pb-4">
            <UCheckbox
              v-model="state.requiresClient"
              label="Require a client on every order"
            />
          </UFormField>
        </section>
      </div>
      </template>

      <template #footer>
        <CroutonFormActionButton
          :action="action"
          :collection="collection"
          :items="items"
          :loading="loading"
        />
      </template>
    </CroutonFormLayout>
  </UForm>
</template>

<script setup lang="ts">
import type { SalesEventFormProps, SalesEventFormData } from '../../types'
import useSalesEvents from '../composables/useSalesEvents'

const props = defineProps<SalesEventFormProps>()
const { defaultValue, schema, collection } = useSalesEvents()

// Form layout configuration
const tabs = ref(false)

// Status is a fixed set of states (matches Card.vue statusColor() rendering)
const statusOptions = [
  { label: 'Upcoming', value: 'upcoming' },
  { label: 'Active', value: 'active' },
  { label: 'Completed', value: 'completed' },
  { label: 'Cancelled', value: 'cancelled' }
]

// Slug helpers — auto-derive from the event name until the user edits it manually
const slugManuallyEdited = ref(false)
function slugify(value: string): string {
  return (value || '')
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '') // strip accents
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}



// Use new mutation composable for data operations
const { create, update, deleteItems } = useCollectionMutation(collection)

// useCrouton still manages modal state
const { close, loading } = useCrouton()

// Initialize form state with proper values (no watch needed!)
const initialValues = props.action === 'update' && props.activeItem?.id
  ? { ...defaultValue, ...props.activeItem }
  : { ...defaultValue }

// Convert date strings to Date objects for date fields during editing
if (props.action === 'update' && props.activeItem?.id) {
  if (initialValues.startDate) {
    initialValues.startDate = new Date(initialValues.startDate)
  }
  if (initialValues.endDate) {
    initialValues.endDate = new Date(initialValues.endDate)
  }
  if (initialValues.archivedAt) {
    initialValues.archivedAt = new Date(initialValues.archivedAt)
  }
}

const state = ref<SalesEventFormData & { id?: string | null }>(initialValues)

// When editing, the slug already exists — never auto-overwrite it
if (props.action === 'update') {
  slugManuallyEdited.value = true
}

// Auto-derive slug from the event name until the user types their own
watch(() => state.value.title, (title) => {
  if (!slugManuallyEdited.value) {
    state.value.slug = slugify(title || '')
  }
})

const handleSubmit = async () => {
  try {
    // Serialize Date objects to ISO strings for API submission
    const serializedData = { ...state.value }
    if (serializedData.startDate instanceof Date) {
      serializedData.startDate = serializedData.startDate.toISOString()
    }
    if (serializedData.endDate instanceof Date) {
      serializedData.endDate = serializedData.endDate.toISOString()
    }
    if (serializedData.archivedAt instanceof Date) {
      serializedData.archivedAt = serializedData.archivedAt.toISOString()
    }

    if (props.action === 'create') {
      await create(serializedData)
    } else if (props.action === 'update' && state.value.id) {
      await update(state.value.id, serializedData)
    } else if (props.action === 'delete') {
      await deleteItems(props.items)
    }

    close()

  } catch (error) {
    console.error('Form submission failed:', error)
    // You can add toast notification here if available
    // toast.add({ title: 'Error', description: 'Failed to submit form', color: 'red' })
  }
}
</script>