/**
 * @crouton-generated
 * Collection Type Registry
 *
 * This file is auto-generated by @fyit/crouton-cli
 * Run `crouton sync-types` to regenerate after adding collections.
 *
 * Generated: 2026-03-11
 *
 * ## How This Works
 * This file augments the CollectionTypeMap interface from @crouton/types.
 * When you use useCollectionQuery('blogPosts'), TypeScript automatically
 * knows the return type is BlogPost[] without requiring explicit generics.
 *
 * ## Registered Collections
 * - contentAteliers: ContentAtelier
 * - contentCategories: ContentCategory
 * - contentDownloads: ContentDownload
 * - contentLocations: ContentLocation
 * - contentNews: ContentNew
 * - contentPersons: ContentPerson
 * - croutonAssets: CroutonAsset
 * - pagesPages: PagesPage
 */

import type { ContentAtelier, ContentAtelierFormData, NewContentAtelier } from './layers/content/collections/ateliers/types'
import type { ContentCategory, ContentCategoryFormData, NewContentCategory } from './layers/content/collections/categories/types'
import type { ContentDownload, ContentDownloadFormData, NewContentDownload } from './layers/content/collections/downloads/types'
import type { ContentLocation, ContentLocationFormData, NewContentLocation } from './layers/content/collections/locations/types'
import type { ContentNew, ContentNewFormData, NewContentNew } from './layers/content/collections/news/types'
import type { ContentPerson, ContentPersonFormData, NewContentPerson } from './layers/content/collections/persons/types'
import type { CroutonAsset, CroutonAssetFormData, NewCroutonAsset } from './layers/crouton/collections/assets/types'
import type { PagesPage, PagesPageFormData, NewPagesPage } from './layers/pages/collections/pages/types'

declare module '#crouton/types' {
  interface CollectionTypeMap {
    contentAteliers: {
      Item: ContentAtelier
      FormData: ContentAtelierFormData
      NewItem: NewContentAtelier
    }
    contentCategories: {
      Item: ContentCategory
      FormData: ContentCategoryFormData
      NewItem: NewContentCategory
    }
    contentDownloads: {
      Item: ContentDownload
      FormData: ContentDownloadFormData
      NewItem: NewContentDownload
    }
    contentLocations: {
      Item: ContentLocation
      FormData: ContentLocationFormData
      NewItem: NewContentLocation
    }
    contentNews: {
      Item: ContentNew
      FormData: ContentNewFormData
      NewItem: NewContentNew
    }
    contentPersons: {
      Item: ContentPerson
      FormData: ContentPersonFormData
      NewItem: NewContentPerson
    }
    croutonAssets: {
      Item: CroutonAsset
      FormData: CroutonAssetFormData
      NewItem: NewCroutonAsset
    }
    pagesPages: {
      Item: PagesPage
      FormData: PagesPageFormData
      NewItem: NewPagesPage
    }
  }
}

export {}
