<!--
  @crouton-generated
  @collection testimonials
  @layer content
  @generated 2026-02-20

  ## AI Context
  - List component for testimonials collection
  - Collection name: contentTestimonials
  - API endpoint: /api/teams/[id]/content-testimonials
  - Columns composable: useContentTestimonials()
  - Column fields: author, company, role, quote, rating, featured, avatar

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="contentTestimonials"
    :columns="columns"
    :rows="testimonials || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="ContentTestimonials"
        :collection="'contentTestimonials'"
        createButton
      />
    </template>
    <template #featured-cell="{ row }">
      <CroutonBoolean :value="row.original.featured" />
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import useContentTestimonials from '../composables/useContentTestimonials'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { columns } = useContentTestimonials()

const { items: testimonials, pending } = await useCollectionQuery(
  'contentTestimonials'
)

</script>