<!--
  @crouton-generated
  @collection posts
  @layer blog
  @generated 2025-12-18

  ## AI Context
  - Form component for posts collection
  - Handles: create, update, delete actions
  - API endpoint: /api/teams/[id]/blog-posts
  - Zod schema: useBlogPosts() composable
  - Fields: title, slug, content, published, publishedAt, authorName

  ## Common Modifications
  - Add field: Add UFormField in template, update schema in composable
  - Custom validation: Modify schema in composable
  - Custom field component: Use meta.component in schema JSON
  - Change layout: Modify CroutonFormLayout template slots

  Generated by @friendlyinternet/nuxt-crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonFormActionButton
    v-if="action === 'delete'"
    :action="action"
    :collection="collection"
    :items="items"
    :loading="loading"
    @click="handleSubmit"
  />

  <UForm
    v-else
    :schema="schema"
    :state="state"
    @submit="handleSubmit"
  >
    <CroutonFormLayout>
      <template #main>
      <div class="flex flex-col gap-4 p-1">
        <UFormField label="Title" name="title" class="not-last:pb-4">
          <UInput v-model="state.title" class="w-full" size="xl" />
        </UFormField>
        <UFormField label="Slug" name="slug" class="not-last:pb-4">
          <UInput v-model="state.slug" class="w-full" size="xl" />
        </UFormField>
        <UFormField label="Content" name="content" class="not-last:pb-4">
          <UTextarea v-model="state.content" class="w-full" size="xl" />
        </UFormField>
        <UFormField label="Published" name="published" class="not-last:pb-4">
          <UCheckbox v-model="state.published" />
        </UFormField>
        <UFormField label="PublishedAt" name="publishedAt" class="not-last:pb-4">
          <UInput v-model="state.publishedAt" class="w-full" size="xl" />
        </UFormField>
        <UFormField label="AuthorName" name="authorName" class="not-last:pb-4">
          <UInput v-model="state.authorName" class="w-full" size="xl" />
        </UFormField>
      </div>
      </template>

      <template #footer>
        <CroutonFormActionButton
          :action="action"
          :collection="collection"
          :items="items"
          :loading="loading"
        />
      </template>
    </CroutonFormLayout>
  </UForm>
</template>

<script setup lang="ts">
import type { BlogPostFormProps, BlogPostFormData } from '../../types'
import useBlogPosts from '../composables/useBlogPosts'

const props = defineProps<BlogPostFormProps>()
const { defaultValue, schema, collection } = useBlogPosts()

// Form layout configuration
const tabs = ref(false)



// Use new mutation composable for data operations
const { create, update, deleteItems } = useCollectionMutation(collection)

// useCrouton still manages modal state
const { close, loading } = useCrouton()

// Initialize form state with proper values (no watch needed!)
const initialValues = props.action === 'update' && props.activeItem?.id
  ? { ...defaultValue, ...props.activeItem }
  : { ...defaultValue }

const state = ref<BlogPostFormData & { id?: string | null }>(initialValues)

const handleSubmit = async () => {
  try {
    if (props.action === 'create') {
      await create(state.value)
    } else if (props.action === 'update' && state.value.id) {
      await update(state.value.id, state.value)
    } else if (props.action === 'delete') {
      await deleteItems(props.items)
    }

    close()

  } catch (error) {
    console.error('Form submission failed:', error)
    // You can add toast notification here if available
    // toast.add({ title: 'Error', description: 'Failed to submit form', color: 'red' })
  }
}
</script>