<!--
  @crouton-generated
  @collection posts
  @layer blog
  @generated 2025-12-18

  ## AI Context
  - List component for posts collection
  - Collection name: blogPosts
  - API endpoint: /api/teams/[id]/blog-posts
  - Columns composable: useBlogPosts()
  - Column fields: title, slug, content, published, publishedAt, authorName

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @friendlyinternet/nuxt-crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="blogPosts"
    :columns="columns"
    :rows="posts || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="BlogPosts"
        :collection="'blogPosts'"
        createButton
      />
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import useBlogPosts from '../composables/useBlogPosts'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { columns } = useBlogPosts()

const { items: posts, pending } = await useCollectionQuery(
  'blogPosts'
)
</script>