/**
 * @crouton-generated
 * @collection posts
 * @layer playground
 * @generated 2025-12-19
 *
 * ## AI Context
 * - Composable: usePlaygroundPosts
 * - Collection name: playgroundPosts
 * - API endpoint: /api/teams/[id]/playground-posts
 * - Form component: PlaygroundPostsForm
 * - List component: PlaygroundPostsList
 * - Fields: id, title, slug, excerpt, content, status, publishedAt, featuredImage, categoryId, metadata
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

// Schema exported separately - Zod 4 schemas cannot survive deep cloning
// Keep schema outside of objects that might be serialized/cloned during SSR
export const playgroundPostSchema = z.object({
  slug: z.string().optional(),
  status: z.string().optional(),
  publishedAt: z.date().optional(),
  featuredImage: z.string().optional(),
  categoryId: z.string().optional(),
  metadata: z.array(z.any()).optional(),
  title: z.string().optional(),
  excerpt: z.string().optional(),
  content: z.string().optional(),
  translations: z.record(
    z.string(),
    z.object({
      title: z.string().min(1, 'Title is required'),
      excerpt: z.string().optional(),
      content: z.string().optional()
    })
  ).refine(
    (translations) => translations.en && translations.en.title,
    { message: 'English translations for title are required' }
  )
})

export const playgroundPostsColumns = [
  { accessorKey: 'id', header: 'Id' },
  { accessorKey: 'title', header: 'Title' },
  { accessorKey: 'slug', header: 'Slug' },
  { accessorKey: 'excerpt', header: 'Excerpt' },
  { accessorKey: 'content', header: 'Content' },
  { accessorKey: 'status', header: 'Status' },
  { accessorKey: 'publishedAt', header: 'PublishedAt' },
  { accessorKey: 'featuredImage', header: 'FeaturedImage' },
  { accessorKey: 'categoryId', header: 'CategoryId' },
  { accessorKey: 'metadata', header: 'Metadata' },
  { accessorKey: 'translations', header: 'Translations' }
]

// Config object WITHOUT schema - safe for SSR serialization
const _playgroundPostsConfig = {
  name: 'playgroundPosts',
  layer: 'playground',
  apiPath: 'playground-posts',
  componentName: 'PlaygroundPostsForm',
  defaultValues: {
    title: '',
    slug: '',
    excerpt: '',
    content: '',
    status: '',
    publishedAt: null,
    featuredImage: '',
    categoryId: '',
    metadata: [],
    translations: {}
  },
  columns: playgroundPostsColumns,
  dependentFieldComponents: {
    metadata: 'PlaygroundPostsMetadataSelect'
  },
}

// Add schema as non-enumerable property so klona skips it during cloning
Object.defineProperty(_playgroundPostsConfig, 'schema', {
  value: playgroundPostSchema,
  enumerable: false,
  configurable: false,
  writable: false
})

export const playgroundPostsConfig = _playgroundPostsConfig as typeof _playgroundPostsConfig & { schema: typeof playgroundPostSchema }

export const usePlaygroundPosts = () => playgroundPostsConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: playgroundPostsConfig.defaultValues,
    schema: playgroundPostSchema,
    columns: playgroundPostsConfig.columns,
    collection: playgroundPostsConfig.name
  }
}