<!--
  @crouton-generated
  @collection inputs
  @layer triage
  @generated 2026-02-11

  ## AI Context
  - List component for inputs collection
  - Collection name: triageInputs
  - API endpoint: /api/teams/[id]/triage-inputs
  - Columns composable: useTriageInputs()
  - Column fields: flowId, sourceType, name, apiToken, webhookUrl, webhookSecret, emailAddress, emailSlug, sourceMetadata, accountId, active

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="triageInputs"
    :columns="columns"
    :rows="inputs || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="TriageInputs"
        :collection="'triageInputs'"
        createButton
      />
    </template>
    <template #flowId-cell="{ row }">
      <CroutonItemCardMini
        v-if="row.original.flowId"
        :id="row.original.flowId"
        collection="triageFlows"
      />
    </template>
    <template #accountId-cell="{ row }">
      <CroutonItemCardMini
        v-if="row.original.accountId"
        :id="row.original.accountId"
        collection="triageAccounts"
      />
    </template>
    <template #active-cell="{ row }">
      <CroutonBoolean :value="row.original.active" />
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import useTriageInputs from '../composables/useTriageInputs'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { columns } = useTriageInputs()

const { items: inputs, pending } = await useCollectionQuery(
  'triageInputs'
)

</script>