<!--
  @crouton-generated
  @collection orderitems
  @layer sales
  @generated 2025-12-25

  ## AI Context
  - Form component for orderitems collection
  - Handles: create, update, delete actions
  - API endpoint: /api/teams/[id]/sales-orderitems
  - Zod schema: useSalesOrderItems() composable
  - Fields: orderId, productId, quantity, unitPrice, totalPrice, remarks, selectedOptions

  ## Common Modifications
  - Add field: Add UFormField in template, update schema in composable
  - Custom validation: Modify schema in composable
  - Custom field component: Use meta.component in schema JSON
  - Change layout: Modify CroutonFormLayout template slots

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonFormActionButton
    v-if="action === 'delete'"
    :action="action"
    :collection="collection"
    :items="items"
    :loading="loading"
    @click="handleSubmit"
  />

  <UForm
    v-else
    :schema="schema"
    :state="state"
    @submit="handleSubmit"
  >
    <CroutonFormLayout>
      <template #main>
      <div class="flex flex-col gap-4 p-1">
        <UFormField label="OrderId" name="orderId" class="not-last:pb-4">
          <CroutonFormReferenceSelect
            v-model="state.orderId"
            collection="salesOrders"
            label="OrderId"
          />
        </UFormField>
        <UFormField label="ProductId" name="productId" class="not-last:pb-4">
          <CroutonFormReferenceSelect
            v-model="state.productId"
            collection="salesProducts"
            label="ProductId"
          />
        </UFormField>
        <UFormField label="Quantity" name="quantity" class="not-last:pb-4">
          <UInput v-model="state.quantity" class="w-full" size="xl" />
        </UFormField>
        <UFormField label="UnitPrice" name="unitPrice" class="not-last:pb-4">
          <UInputNumber v-model="state.unitPrice" class="w-full" />
        </UFormField>
        <UFormField label="TotalPrice" name="totalPrice" class="not-last:pb-4">
          <UInputNumber v-model="state.totalPrice" class="w-full" />
        </UFormField>
        <UFormField label="Remarks" name="remarks" class="not-last:pb-4">
          <UTextarea v-model="state.remarks" class="w-full" size="xl" />
        </UFormField>
        <UFormField label="SelectedOptions" name="selectedOptions" class="not-last:pb-4">
          <UTextarea
            :model-value="typeof state.selectedOptions === 'string' ? state.selectedOptions : JSON.stringify(state.selectedOptions, null, 2)"
            @update:model-value="(val) => { try { state.selectedOptions = val ? JSON.parse(val) : {} } catch (e) { console.error('Invalid JSON:', e) } }"
            class="w-full font-mono text-sm"
            :rows="8"
            placeholder="Enter JSON object"
          />
        </UFormField>
      </div>
      </template>

      <template #footer>
        <CroutonFormActionButton
          :action="action"
          :collection="collection"
          :items="items"
          :loading="loading"
        />
      </template>
    </CroutonFormLayout>
  </UForm>
</template>

<script setup lang="ts">
import type { SalesOrderItemFormProps, SalesOrderItemFormData } from '../../types'
import useSalesOrderItems from '../composables/useSalesOrderItems'

const props = defineProps<SalesOrderItemFormProps>()
const { defaultValue, schema, collection } = useSalesOrderItems()

// Form layout configuration
const tabs = ref(false)



// Use new mutation composable for data operations
const { create, update, deleteItems } = useCollectionMutation(collection)

// useCrouton still manages modal state
const { close, loading } = useCrouton()

// Initialize form state with proper values (no watch needed!)
const initialValues = props.action === 'update' && props.activeItem?.id
  ? { ...defaultValue, ...props.activeItem }
  : { ...defaultValue }

const state = ref<SalesOrderItemFormData & { id?: string | null }>(initialValues)

const handleSubmit = async () => {
  try {
    if (props.action === 'create') {
      await create(state.value)
    } else if (props.action === 'update' && state.value.id) {
      await update(state.value.id, state.value)
    } else if (props.action === 'delete') {
      await deleteItems(props.items)
    }

    close()

  } catch (error) {
    console.error('Form submission failed:', error)
    // You can add toast notification here if available
    // toast.add({ title: 'Error', description: 'Failed to submit form', color: 'red' })
  }
}
</script>