<!--
  @crouton-generated
  @collection products
  @layer shop
  @generated 2026-02-20

  ## AI Context
  - Form component for products collection
  - Handles: create, update, delete actions
  - API endpoint: /api/teams/[id]/shop-products
  - Zod schema: useShopProducts() composable
  - Fields: name, description, shortDescription, price, stock, featured, inStock, thumbnail, tags

  ## Common Modifications
  - Add field: Add UFormField in template, update schema in composable
  - Custom validation: Modify schema in composable
  - Custom field component: Use meta.component in schema JSON
  - Change layout: Modify CroutonFormLayout template slots

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonFormActionButton
    v-if="action === 'delete'"
    :action="action"
    :collection="collection"
    :items="items"
    :loading="loading"
    @click="handleSubmit"
  />

  <UForm
    v-else
    :schema="schema"
    :state="state"
    @submit="handleSubmit"
  >
    <CroutonFormLayout>
      <template #main>
      <div class="flex flex-col gap-4 p-1">
        <UFormField label="Name" name="name" class="not-last:pb-4">
          <UInput v-model="state.name" class="w-full" size="xl" />
        </UFormField>
        <UFormField label="Description" name="description" class="not-last:pb-4">
          <UTextarea v-model="state.description" class="w-full" size="xl" />
        </UFormField>
        <UFormField label="ShortDescription" name="shortDescription" class="not-last:pb-4">
          <UTextarea v-model="state.shortDescription" class="w-full" size="xl" />
        </UFormField>
      </div>
      </template>

      <template #sidebar>
      <div class="flex flex-col gap-4 p-1">
      </div>
      <div class="flex flex-col gap-4 p-1">
        <UFormField label="Price" name="price" class="not-last:pb-4">
          <UInputNumber v-model="state.price" class="w-full" />
        </UFormField>
        <UFormField label="Stock" name="stock" class="not-last:pb-4">
          <UInputNumber v-model="state.stock" class="w-full" />
        </UFormField>
        <UFormField label="Featured" name="featured" class="not-last:pb-4">
          <UCheckbox v-model="state.featured" />
        </UFormField>
        <UFormField label="InStock" name="inStock" class="not-last:pb-4">
          <UCheckbox v-model="state.inStock" />
        </UFormField>
        <UFormField label="Thumbnail" name="thumbnail" class="not-last:pb-4">
          <CroutonAssetsPicker
            v-model="state.thumbnail"
            :crop="true"
          />
        </UFormField>
        <UFormField label="Tags" name="tags" class="not-last:pb-4">
          <UTextarea
            :model-value="Array.isArray(state.tags) ? state.tags.join('\n') : ''"
            @update:model-value="(val) => state.tags = val ? val.split('\n').filter(Boolean) : []"
            class="w-full"
            :rows="6"
            placeholder="Enter one value per line"
          />
          <p class="text-sm text-gray-500 mt-1">Enter one value per line</p>
        </UFormField>
      </div>
      </template>

      <template #footer>
        <CroutonFormActionButton
          :action="action"
          :collection="collection"
          :items="items"
          :loading="loading"
        />
      </template>
    </CroutonFormLayout>
  </UForm>
</template>

<script setup lang="ts">
import type { ShopProductFormProps, ShopProductFormData } from '../../types'
import useShopProducts from '../composables/useShopProducts'

const props = defineProps<ShopProductFormProps>()
const { defaultValue, schema, collection } = useShopProducts()

// Form layout configuration
const tabs = ref(false)



// Use new mutation composable for data operations
const { create, update, deleteItems } = useCollectionMutation(collection)

// useCrouton still manages modal state
const { close, loading } = useCrouton()

// Initialize form state with proper values (no watch needed!)
const initialValues = props.action === 'update' && props.activeItem?.id
  ? { ...defaultValue, ...props.activeItem }
  : { ...defaultValue }

const state = ref<ShopProductFormData & { id?: string | null }>(initialValues)

const handleSubmit = async () => {
  try {
    if (props.action === 'create') {
      await create(state.value)
    } else if (props.action === 'update' && state.value.id) {
      await update(state.value.id, state.value)
    } else if (props.action === 'delete') {
      await deleteItems(props.items)
    }

    close()

  } catch (error) {
    console.error('Form submission failed:', error)
    // You can add toast notification here if available
    // toast.add({ title: 'Error', description: 'Failed to submit form', color: 'red' })
  }
}
</script>