<!--
  @crouton-generated
  @collection categories
  @layer sales
  @generated 2025-12-25

  ## AI Context
  - List component for categories collection
  - Collection name: salesCategories
  - API endpoint: /api/teams/[id]/sales-categories
  - Columns composable: useSalesCategories()
  - Column fields: eventId, title, displayOrder

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="salesCategories"
    :columns="columns"
    :rows="categories || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="SalesCategories"
        :collection="'salesCategories'"
        createButton
      />
    </template>
    <template #eventId-cell="{ row }">
      <CroutonItemCardMini
        v-if="row.original.eventId"
        :id="row.original.eventId"
        collection="salesEvents"
      />
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import useSalesCategories from '../composables/useSalesCategories'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { columns } = useSalesCategories()

const { items: categories, pending } = await useCollectionQuery(
  'salesCategories'
)
</script>