/**
 * @crouton-generated
 * @collection locations
 * @layer bookings
 * @generated 2026-01-20
 *
 * ## AI Context
 * - Main interface: BookingsLocation
 * - Form data type: BookingsLocationFormData
 * - New item type: NewBookingsLocation
 * - Form props: BookingsLocationFormProps
 * - Fields: title, color, street, zip, city, location, content, allowedMemberIds, slots, inventoryMode, quantity
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { bookingsLocationSchema } from './app/composables/useBookingsLocations'

export interface BookingsLocation {
  id: string
  teamId: string
  owner: string
  title: string
  color?: string
  street?: string
  zip?: string
  city?: string
  location?: string
  content?: string
  allowedMemberIds?: string[]
  slots?: any[]
  inventoryMode?: boolean
  quantity?: number
  translations?: Record<string, { title?: string; street?: string; zip?: string; city?: string; content?: string }>
  locale?: string
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type BookingsLocationFormData = z.infer<typeof bookingsLocationSchema>
export type NewBookingsLocation = Omit<BookingsLocation, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'>

// Props type for the Form component
export interface BookingsLocationFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: BookingsLocation | Record<string, never> // BookingsLocation for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}