/**
 * @crouton-generated
 * @collection printqueues
 * @layer sales
 * @generated 2026-06-24
 *
 * ## AI Context
 * - Main interface: SalesPrintqueue
 * - Form data type: SalesPrintqueueFormData
 * - New item type: NewSalesPrintqueue
 * - Form props: SalesPrintqueueFormProps
 * - Fields: id, eventId, orderId, printerId, locationId, status, printData, printMode, errorMessage, retryCount, completedAt
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { salesPrintqueueSchema } from './app/composables/useSalesPrintqueues'

export interface SalesPrintqueue {
  id: string
  teamId: string
  owner: string
  eventId: string
  orderId: string
  printerId: string
  locationId?: string
  status: string
  printData: string
  printMode?: string
  errorMessage?: string
  retryCount?: string
  completedAt?: string
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type SalesPrintqueueFormData = z.infer<typeof salesPrintqueueSchema>
// New* allows the server-set fields (id, createdBy, updatedBy) as optional — the
// generated POST endpoint provides them; other callers (e.g. seed) may omit them.
export type NewSalesPrintqueue = Omit<SalesPrintqueue, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'> & { id?: string; createdBy?: string; updatedBy?: string }

// Props type for the Form component
export interface SalesPrintqueueFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: SalesPrintqueue | Record<string, never> // SalesPrintqueue for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}