/**
 * @crouton-generated
 * @collection orderitems
 * @layer sales
 * @generated 2025-12-25
 *
 * ## AI Context
 * - Composable: useSalesOrderItems
 * - Collection name: salesOrderItems
 * - API endpoint: /api/teams/[id]/sales-orderitems
 * - Form component: SalesOrderItemsForm
 * - List component: SalesOrderItemsList
 * - Fields: id, orderId, productId, quantity, unitPrice, totalPrice, remarks, selectedOptions
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @friendlyinternet/nuxt-crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

// Schema exported separately - Zod 4 schemas cannot survive deep cloning
// Keep schema outside of objects that might be serialized/cloned during SSR
export const salesOrderItemSchema = z.object({
  orderId: z.string().min(1, 'orderId is required'),
  productId: z.string().min(1, 'productId is required'),
  quantity: z.string().min(1, 'quantity is required'),
  unitPrice: z.number(),
  totalPrice: z.number(),
  remarks: z.string().optional(),
  selectedOptions: z.record(z.string(), z.any()).optional()
})

export const salesOrderItemsColumns = [
  { accessorKey: 'id', header: 'Id' },
  { accessorKey: 'orderId', header: 'OrderId' },
  { accessorKey: 'productId', header: 'ProductId' },
  { accessorKey: 'quantity', header: 'Quantity' },
  { accessorKey: 'unitPrice', header: 'UnitPrice' },
  { accessorKey: 'totalPrice', header: 'TotalPrice' },
  { accessorKey: 'remarks', header: 'Remarks' },
  { accessorKey: 'selectedOptions', header: 'SelectedOptions' }
]

// Config object WITHOUT schema - safe for SSR serialization
const _salesOrderItemsConfig = {
  name: 'salesOrderItems',
  layer: 'sales',
  apiPath: 'sales-orderitems',
  componentName: 'SalesOrderItemsForm',
  defaultValues: {
    orderId: '',
    productId: '',
    quantity: '',
    unitPrice: 0,
    totalPrice: 0,
    remarks: '',
    selectedOptions: {}
  },
  columns: salesOrderItemsColumns,
}

// Add schema as non-enumerable property so klona skips it during cloning
Object.defineProperty(_salesOrderItemsConfig, 'schema', {
  value: salesOrderItemSchema,
  enumerable: false,
  configurable: false,
  writable: false
})

export const salesOrderItemsConfig = _salesOrderItemsConfig as typeof _salesOrderItemsConfig & { schema: typeof salesOrderItemSchema }

export const useSalesOrderItems = () => salesOrderItemsConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: salesOrderItemsConfig.defaultValues,
    schema: salesOrderItemSchema,
    columns: salesOrderItemsConfig.columns,
    collection: salesOrderItemsConfig.name
  }
}