/**
 * @crouton-generated
 * @collection flowoutputs
 * @layer triage
 * @generated 2026-02-10
 *
 * ## AI Context
 * - Composable: useTriageFlowOutputs
 * - Collection name: triageFlowOutputs
 * - API endpoint: /api/teams/[id]/triage-flowoutputs
 * - Form component: TriageFlowOutputsForm
 * - List component: TriageFlowOutputsList
 * - Fields: flowId, outputType, name, domainFilter, isDefault, outputConfig, active
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

// Schema exported separately - Zod 4 schemas cannot survive deep cloning
// Keep schema outside of objects that might be serialized/cloned during SSR
export const triageFlowOutputSchema = z.object({
  flowId: z.string().min(1, 'flowId is required'),
  outputType: z.string().min(1, 'outputType is required'),
  name: z.string().min(1, 'name is required'),
  domainFilter: z.array(z.string()).optional(),
  isDefault: z.boolean().optional(),
  outputConfig: z.record(z.string(), z.any()).optional(),
  active: z.boolean()
})

export const triageFlowOutputsColumns = [
  { accessorKey: 'flowId', header: 'FlowId' },
  { accessorKey: 'outputType', header: 'OutputType' },
  { accessorKey: 'name', header: 'Name' },
  { accessorKey: 'domainFilter', header: 'DomainFilter' },
  { accessorKey: 'isDefault', header: 'IsDefault' },
  { accessorKey: 'outputConfig', header: 'OutputConfig' },
  { accessorKey: 'active', header: 'Active' }
]

// Config object WITHOUT schema - safe for SSR serialization
const _triageFlowOutputsConfig = {
  name: 'triageFlowOutputs',
  layer: 'triage',
  apiPath: 'triage-flowoutputs',
  componentName: 'TriageFlowOutputsForm',
  defaultValues: {
    flowId: '',
    outputType: '',
    name: '',
    domainFilter: [],
    isDefault: false,
    outputConfig: {},
    active: false
  },
  columns: triageFlowOutputsColumns,
}

// Add schema as non-enumerable property so klona skips it during cloning
Object.defineProperty(_triageFlowOutputsConfig, 'schema', {
  value: triageFlowOutputSchema,
  enumerable: false,
  configurable: false,
  writable: false
})

export const triageFlowOutputsConfig = _triageFlowOutputsConfig as typeof _triageFlowOutputsConfig & { schema: typeof triageFlowOutputSchema }

export const useTriageFlowOutputs = () => triageFlowOutputsConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: triageFlowOutputsConfig.defaultValues,
    schema: triageFlowOutputSchema,
    columns: triageFlowOutputsConfig.columns,
    collection: triageFlowOutputsConfig.name
  }
}