/**
 * @crouton-generated
 * @collection tags
 * @layer playground
 * @generated 2025-12-18
 *
 * ## AI Context
 * - Composable: usePlaygroundTags
 * - Collection name: playgroundTags
 * - API endpoint: /api/teams/[id]/playground-tags
 * - Form component: PlaygroundTagsForm
 * - List component: PlaygroundTagsList
 * - Fields: id, name, slug, color, order
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @friendlyinternet/nuxt-crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

export const playgroundTagSchema = z.object({
  name: z.string().min(1, 'name is required'),
  slug: z.string().optional(),
  color: z.string().optional(),
  order: z.number().optional()
})

export const playgroundTagsColumns = [
  { accessorKey: 'id', header: 'Id' },
  { accessorKey: 'name', header: 'Name' },
  { accessorKey: 'slug', header: 'Slug' },
  { accessorKey: 'color', header: 'Color' },
  { accessorKey: 'order', header: 'Order' }
]

export const playgroundTagsConfig = {
  name: 'playgroundTags',
  layer: 'playground',
  apiPath: 'playground-tags',
  componentName: 'PlaygroundTagsForm',
  schema: playgroundTagSchema,
  defaultValues: {
    name: '',
    slug: '',
    color: '',
    order: 0
  },
  columns: playgroundTagsColumns,
}

export const usePlaygroundTags = () => playgroundTagsConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: playgroundTagsConfig.defaultValues,
    schema: playgroundTagsConfig.schema,
    columns: playgroundTagsConfig.columns,
    collection: playgroundTagsConfig.name
  }
}