import { resolveTeamAndCheckMembership } from '@fyit/crouton-auth/server/utils/team'
import { getAllThinkgraphNodes, updateThinkgraphNode } from '~~/layers/thinkgraph/collections/nodes/server/database/queries'
import { buildNodeContext } from '~~/server/utils/context-builder'
import { buildConversationRoundup } from '~~/server/utils/dispatch-conversation'
import { detectTemplate } from '~~/server/utils/template-detector'
import { NODE_TYPE_SKILLS, NODE_TYPE_STEPS, normalizeNodeType } from '~~/layers/thinkgraph/collections/nodes/types'

/**
 * Dispatch a work item to Pi.dev or another provider.
 *
 * POST /api/teams/[id]/dispatch/work-item
 * Body: { workItemId, prompt?, options? }
 *
 * For Pi.dev: stores handoff metadata on the work item's artifacts,
 * sets status to 'active'. The Pi worker picks up the handoff via polling.
 */
export default defineEventHandler(async (event) => {
  const { team, user, membership } = await resolveTeamAndCheckMembership(event)
  const body = await readBody(event)

  const { workItemId, prompt, options } = body
  if (!workItemId) {
    throw createError({ status: 400, statusText: 'Missing workItemId' })
  }

  // Load all work items for this team to build context chain
  const allItems = await getAllThinkgraphNodes(team.id)
  const targetItem = allItems.find((item: any) => item.id === workItemId)

  if (!targetItem) {
    throw createError({ status: 404, statusText: 'Work item not found' })
  }

  // Validate and normalize node type before dispatch
  let nodeType = normalizeNodeType(targetItem.template)

  // Auto-classify if still an idea
  if (nodeType === 'idea') {
    const detected = detectTemplate(targetItem.title, targetItem.brief || undefined)
    if (detected.template !== 'idea') {
      nodeType = detected.template
      await updateThinkgraphNode(workItemId, team.id, user.id, {
        template: nodeType,
        steps: detected.steps,
      } as any, { role: membership.role })
    }
  }

  // Check if this type is dispatchable
  const skill = NODE_TYPE_SKILLS[nodeType]
  if (!skill) {
    throw createError({
      status: 400,
      statusText: `Node type '${nodeType}' is not dispatchable. Classify as discover/architect/generate/compose/deploy first.`,
    })
  }

  // Ensure steps are set
  const steps = (Array.isArray(targetItem.steps) && targetItem.steps.length > 0)
    ? targetItem.steps
    : NODE_TYPE_STEPS[nodeType]
  if (steps.length > 0 && (!Array.isArray(targetItem.steps) || targetItem.steps.length === 0)) {
    await updateThinkgraphNode(workItemId, team.id, user.id, { steps } as any, { role: membership.role })
  }

  // Build context chain from ancestor work items
  const contextPayload = buildNodeContext(
    allItems.map((item: any) => ({
      id: item.id,
      parentId: item.parentId,
      title: item.title,
      nodeType: normalizeNodeType(item.template),
      status: item.status,
      summary: item.summary,
      brief: item.brief,
      output: item.output,
      pinned: item.pinned,
      contextScope: item.contextScope,
      contextNodeIds: item.contextNodeIds,
    })),
    workItemId,
  )

  // Build the per-node chat conversation roundup. This is the "conversation as
  // execution context" hand-off — the structured brief of what was decided in
  // chat, generated by the AI provider and cached on the conversation row.
  // Falls back to deterministic truncation if generation fails.
  const conversationRoundup = await buildConversationRoundup(event, team.id, workItemId)

  // Compose the final context: structural chain + (if present) conversation roundup
  const composedContext = conversationRoundup.markdown
    ? `${contextPayload.markdown}\n\n${conversationRoundup.markdown}`
    : contextPayload.markdown
  const composedContextTokens = contextPayload.tokenEstimate + conversationRoundup.tokenEstimate

  // Default stage to first step in node's steps array
  const defaultStage = steps.length > 0 ? steps[0] : 'analyst'
  const stage = targetItem.stage || defaultStage
  if (!targetItem.stage) {
    await updateThinkgraphNode(
      workItemId,
      team.id,
      user.id,
      { stage },
      { role: membership.role },
    )
  }

  // Determine the assignee/provider
  const assignee = targetItem.assignee || 'pi'
  const provider = targetItem.provider || (assignee.startsWith('api:') ? assignee.replace('api:', '') : assignee)

  // Build the handoff metadata
  const handoffMeta = {
    type: 'handoff' as const,
    provider,
    skill,
    prompt: prompt || targetItem.brief || '',
    context: composedContext,
    contextTokens: composedContextTokens,
    conversationSummaryStatus: conversationRoundup.status,
    projectId: targetItem.projectId,
    workItemId,
    workItemTitle: targetItem.title,
    workItemType: nodeType,
    teamId: team.id,
    dispatchedBy: user.id,
    dispatchedAt: new Date().toISOString(),
  }

  // Store handoff metadata and set status to active
  const existingArtifacts = Array.isArray(targetItem.artifacts) ? targetItem.artifacts : []
  const cleanedArtifacts = existingArtifacts.filter((a: any) => a?.type !== 'handoff')

  await updateThinkgraphNode(
    workItemId,
    team.id,
    user.id,
    {
      status: 'active',
      artifacts: [...cleanedArtifacts, handoffMeta],
    },
    { role: membership.role },
  )

  // Dispatch to Pi worker via HTTP
  const config = useRuntimeConfig()
  const piWorkerUrl = config.piWorkerUrl || 'https://pi-api.pmcp.dev'
  let piAccepted = false

  if (provider === 'pi') {
    try {
      const piResponse = await $fetch<{ accepted: boolean }>(`${piWorkerUrl}/dispatch`, {
        method: 'POST',
        headers: {
          ...(config.piDispatchSecret ? { Authorization: `Bearer ${config.piDispatchSecret}` } : {}),
        },
        body: {
          workItemId,
          projectId: targetItem.projectId,
          prompt: handoffMeta.prompt || targetItem.brief || targetItem.title,
          context: composedContext,
          skill: handoffMeta.skill,
          workItemType: nodeType,
          stage,
          teamId: team.id,
          teamSlug: team.slug || team.id,
          callbackUrl: `${config.public?.siteUrl || `https://${getHeader(event, 'host') || 'localhost:3004'}`}/api/teams/${team.id}/dispatch/webhook`,
        },
      })
      piAccepted = piResponse?.accepted || false
    }
    catch (err: any) {
      console.warn(`[dispatch] Pi worker not reachable at ${piWorkerUrl}:`, err.message)
      // Don't fail — handoff metadata is stored, Pi can pick it up via polling
    }
  }

  return {
    success: true,
    workItemId,
    provider,
    skill: handoffMeta.skill,
    contextTokens: composedContextTokens,
    conversationSummaryStatus: conversationRoundup.status,
    piAccepted,
  }
})
