/**
 * @crouton-generated
 * @collection tasks
 * @layer triage
 * @generated 2026-03-10
 *
 * ## AI Context
 * - Composable: useTriageTasks
 * - Collection name: triageTasks
 * - API endpoint: /api/teams/[id]/triage-tasks
 * - Form component: TriageTasksForm
 * - List component: TriageTasksList
 * - Fields: discussionId, syncJobId, notionPageId, notionPageUrl, title, description, status, priority, assignee, summary, sourceUrl, isMultiTaskChild, taskIndex, metadata
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

// Schema exported separately - Zod 4 schemas cannot survive deep cloning
// Keep schema outside of objects that might be serialized/cloned during SSR
export const triageTaskSchema = z.object({
  discussionId: z.string().min(1, 'discussionId is required'),
  syncJobId: z.string().min(1, 'syncJobId is required'),
  notionPageId: z.string().min(1, 'notionPageId is required'),
  notionPageUrl: z.string().min(1, 'notionPageUrl is required'),
  title: z.string().min(1, 'title is required'),
  description: z.string().optional(),
  status: z.string().min(1, 'status is required'),
  priority: z.string().optional(),
  assignee: z.string().optional(),
  summary: z.string().optional(),
  sourceUrl: z.string().min(1, 'sourceUrl is required'),
  isMultiTaskChild: z.boolean(),
  taskIndex: z.number().optional(),
  metadata: z.record(z.string(), z.any()).optional()
})

export const triageTasksColumns = [
  { accessorKey: 'discussionId', header: 'DiscussionId' },
  { accessorKey: 'syncJobId', header: 'SyncJobId' },
  { accessorKey: 'notionPageId', header: 'NotionPageId' },
  { accessorKey: 'notionPageUrl', header: 'NotionPageUrl' },
  { accessorKey: 'title', header: 'Title' },
  { accessorKey: 'description', header: 'Description' },
  { accessorKey: 'status', header: 'Status' },
  { accessorKey: 'priority', header: 'Priority' },
  { accessorKey: 'assignee', header: 'Assignee' },
  { accessorKey: 'summary', header: 'Summary' },
  { accessorKey: 'sourceUrl', header: 'SourceUrl' },
  { accessorKey: 'isMultiTaskChild', header: 'IsMultiTaskChild' },
  { accessorKey: 'taskIndex', header: 'TaskIndex' },
  { accessorKey: 'metadata', header: 'Metadata' }
]

// Config object WITHOUT schema - safe for SSR serialization
const _triageTasksConfig = {
  name: 'triageTasks',
  layer: 'triage',
  apiPath: 'triage-tasks',
  componentName: 'TriageTasksForm',
  defaultValues: {
    discussionId: '',
    syncJobId: '',
    notionPageId: '',
    notionPageUrl: '',
    title: '',
    description: '',
    status: '',
    priority: '',
    assignee: '',
    summary: '',
    sourceUrl: '',
    isMultiTaskChild: false,
    taskIndex: 0,
    metadata: {}
  },
  columns: triageTasksColumns,
  fields: [
      {
          "name": "discussionId",
          "type": "string",
          "label": "Discussion",
          "area": "sidebar"
      },
      {
          "name": "syncJobId",
          "type": "string",
          "label": "Sync Job",
          "area": "sidebar"
      },
      {
          "name": "notionPageId",
          "type": "string",
          "label": "Notion Page ID",
          "area": "sidebar"
      },
      {
          "name": "notionPageUrl",
          "type": "string",
          "label": "Notion Page URL",
          "area": "main"
      },
      {
          "name": "title",
          "type": "string",
          "label": "Task Title",
          "area": "main"
      },
      {
          "name": "description",
          "type": "text",
          "label": "Task Description",
          "area": "main"
      },
      {
          "name": "status",
          "type": "string",
          "label": "Status",
          "area": "sidebar",
          "displayAs": "badge"
      },
      {
          "name": "priority",
          "type": "string",
          "label": "Priority",
          "area": "sidebar"
      },
      {
          "name": "assignee",
          "type": "string",
          "label": "Assignee Handle",
          "area": "sidebar"
      },
      {
          "name": "summary",
          "type": "text",
          "label": "AI Summary",
          "area": "main"
      },
      {
          "name": "sourceUrl",
          "type": "string",
          "label": "Source URL",
          "area": "main"
      },
      {
          "name": "isMultiTaskChild",
          "type": "boolean",
          "label": "Is Multi-Task Child",
          "area": "sidebar"
      },
      {
          "name": "taskIndex",
          "type": "number",
          "label": "Task Index",
          "area": "sidebar"
      },
      {
          "name": "metadata",
          "type": "json",
          "label": "Metadata",
          "area": "sidebar"
      }
  ],
}

// Add schema as non-enumerable property so klona skips it during cloning
Object.defineProperty(_triageTasksConfig, 'schema', {
  value: triageTaskSchema,
  enumerable: false,
  configurable: false,
  writable: false
})

export const triageTasksConfig = _triageTasksConfig as typeof _triageTasksConfig & { schema: typeof triageTaskSchema }

export const useTriageTasks = () => triageTasksConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: triageTasksConfig.defaultValues,
    schema: triageTaskSchema,
    columns: triageTasksConfig.columns,
    collection: triageTasksConfig.name
  }
}