/**
 * @crouton-generated
 * @collection categories
 * @layer playground
 * @generated 2025-12-18
 *
 * ## AI Context
 * - Main interface: PlaygroundCategorie
 * - Form data type: PlaygroundCategorieFormData
 * - New item type: NewPlaygroundCategorie
 * - Form props: PlaygroundCategorieFormProps
 * - Fields: id, name, description, icon, color
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @friendlyinternet/nuxt-crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { playgroundCategorieSchema } from './app/composables/usePlaygroundCategories'

export interface PlaygroundCategorie {
  id: string
  teamId: string
  owner: string
  name: string
  description?: string
  icon?: string
  color?: string
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type PlaygroundCategorieFormData = z.infer<typeof playgroundCategorieSchema>
export type NewPlaygroundCategorie = Omit<PlaygroundCategorie, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'>

// Props type for the Form component
export interface PlaygroundCategorieFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: PlaygroundCategorie | Record<string, never> // PlaygroundCategorie for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}