#!/usr/bin/env node
/**
 * Render the housekeeping digest data (from gather.mjs) into Markdown.
 *
 *   node render.mjs housekeeping.data.json [--out-dir .]
 *
 * Render-only: it transforms JSON → text and writes a file. It never calls GitHub.
 * Each section is a skimmable list and is OMITTED entirely when it has no findings —
 * a quiet week renders to "✨ Nothing needs your eyes." so an empty digest reads as a
 * win, not a wall. Mirrors the shape of .claude/skills/epic-digest/render.mjs.
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const args = process.argv.slice(2)
const dataPath = args.find((a) => !a.startsWith('--'))
if (!dataPath) {
  console.error('render.mjs: pass the path to housekeeping.data.json')
  process.exit(1)
}
const outDir = (() => {
  const i = args.indexOf('--out-dir')
  return i >= 0 ? args[i + 1] : '.'
})()

const data = JSON.parse(readFileSync(dataPath, 'utf8'))
const N = data.staleDays
const link = (n, t, url) => `[#${n}](${url}) — ${t}`

// Each entry: [heading, lines[]]. A section with no lines is dropped.
const sections = []

if (data.staleBranches === null) {
  sections.push([
    '🌿 Stale unmerged branches',
    ['_Branch data unavailable this run (shallow checkout) — skipped._']
  ])
} else if (data.staleBranches.length) {
  sections.push([
    '🌿 Stale unmerged branches',
    [
      `Not contained in \`main\` and untouched for >${N}d — review then merge or delete (not auto-touched):`,
      ...data.staleBranches.map((b) => `- \`${b.name}\` — last commit ${b.lastCommit} (${b.ageDays}d ago)`)
    ]
  ])
}

if (data.unlabeled?.length) {
  sections.push([
    '🏷️ Issues missing labels',
    [
      'Open issues without a `type:*` and/or a component (`pkg`/`app`/`worker`/`poc`) label:',
      ...data.unlabeled.map((i) => `- ${link(i.number, i.title, i.url)} — missing **${i.missing.join('**, **')}**`)
    ]
  ])
}

if (data.stuck?.length) {
  sections.push([
    '⏳ Stuck in-progress',
    [
      `\`status:in-progress\` with no activity in >${N}d (likely no PR moving it):`,
      ...data.stuck.map((i) => `- ${link(i.number, i.title, i.url)} — idle ${i.ageDays}d`)
    ]
  ])
}

if (data.staleEpics?.length) {
  sections.push([
    '✅ Epics ready to close',
    [
      'All sub-issues are closed but the epic is still open — verify the rollup, then close:',
      ...data.staleEpics.map((e) => `- ${link(e.number, e.title, e.url)} — ${e.children}/${e.children} children closed`)
    ]
  ])
}

if (data.idlePRs?.length) {
  sections.push([
    '🔀 Idle PRs',
    [
      `Open PRs with no activity in >${N}d:`,
      ...data.idlePRs.map((p) => `- ${link(p.number, p.title, p.url)}${p.draft ? ' _(draft)_' : ''} — idle ${p.ageDays}d`)
    ]
  ])
}

const when = new Date(data.generatedAt).toISOString().slice(0, 10)
const head = [`## 🧹 Housekeeping — ${when}`, '']
const body = sections.length
  ? sections.flatMap(([h, lines]) => [`### ${h}`, ...lines, ''])
  : ['✨ Nothing needs your eyes — branches, labels, and issue state look clean.', '']
const foot = [
  '---',
  `_Render-only digest · drift threshold ${N}d · nothing here was modified. Generated by \`.github/workflows/housekeeping.yml\`._`
]
const md = [...head, ...body, ...foot].join('\n') + '\n'

const outFile = join(outDir, `housekeeping-${when}.md`)
writeFileSync(outFile, md)
process.stdout.write(`Wrote ${outFile}\n`)
