<!--
  @crouton-generated
  @collection users
  @layer triage
  @generated 2026-02-11

  ## AI Context
  - List component for users collection
  - Collection name: triageUsers
  - API endpoint: /api/teams/[id]/triage-users
  - Columns composable: useTriageUsers()
  - Column fields: sourceType, sourceWorkspaceId, sourceUserId, sourceUserEmail, sourceUserName, notionUserId, notionUserName, notionUserEmail, mappingType, confidence, active, lastSyncedAt, metadata

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="triageUsers"
    :columns="columns"
    :rows="users || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="TriageUsers"
        :collection="'triageUsers'"
        createButton
      />
    </template>
    <template #active-cell="{ row }">
      <CroutonBoolean :value="row.original.active" />
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import useTriageUsers from '../composables/useTriageUsers'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { columns } = useTriageUsers()

const { items: users, pending } = await useCollectionQuery(
  'triageUsers'
)

</script>