<!--
  @crouton-generated
  @collection pages
  @layer pages
  @generated 2026-01-14

  ## AI Context
  - List component for pages collection
  - Collection name: pagesPages
  - API endpoint: /api/teams/[id]/pages-pages
  - Columns composable: usePagesPages()
  - Column fields: name, label, icon, description, hierarchy, fields

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @friendlyinternet/nuxt-crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="pagesPages"
    :columns="columns"
    :rows="pages || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="PagesPages"
        :collection="'pagesPages'"
        createButton
      />
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import usePagesPages from '../composables/usePagesPages'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { columns } = usePagesPages()

const { items: pages, pending } = await useCollectionQuery(
  'pagesPages'
)
</script>