/**
 * @crouton-generated
 * Collection Type Registry
 *
 * This file is auto-generated by @fyit/crouton-cli
 * Run `crouton sync-types` to regenerate after adding collections.
 *
 * Generated: 2026-03-16
 *
 * ## How This Works
 * This file augments the CollectionTypeMap interface from @crouton/types.
 * When you use useCollectionQuery('blogPosts'), TypeScript automatically
 * knows the return type is BlogPost[] without requiring explicit generics.
 *
 * ## Registered Collections
 * - thinkgraphCanvases: ThinkgraphCanvase
 * - thinkgraphChatconversations: ThinkgraphChatconversation
 * - thinkgraphDecisions: ThinkgraphDecision
 * - thinkgraphGraphs: ThinkgraphGraph
 * - thinkgraphInjectrequests: ThinkgraphInjectrequest
 * - thinkgraphNodes: ThinkgraphNode
 */

import type { ThinkgraphCanvase, ThinkgraphCanvaseFormData, NewThinkgraphCanvase } from './layers/thinkgraph/collections/canvases/types'
import type { ThinkgraphChatconversation, ThinkgraphChatconversationFormData, NewThinkgraphChatconversation } from './layers/thinkgraph/collections/chatconversations/types'
import type { ThinkgraphDecision, ThinkgraphDecisionFormData, NewThinkgraphDecision } from './layers/thinkgraph/collections/decisions/types'
import type { ThinkgraphGraph, ThinkgraphGraphFormData, NewThinkgraphGraph } from './layers/thinkgraph/collections/graphs/types'
import type { ThinkgraphInjectrequest, ThinkgraphInjectrequestFormData, NewThinkgraphInjectrequest } from './layers/thinkgraph/collections/injectrequests/types'
import type { ThinkgraphNode, ThinkgraphNodeFormData, NewThinkgraphNode } from './layers/thinkgraph/collections/nodes/types'

declare module '#crouton/types' {
  interface CollectionTypeMap {
    thinkgraphCanvases: {
      Item: ThinkgraphCanvase
      FormData: ThinkgraphCanvaseFormData
      NewItem: NewThinkgraphCanvase
    }
    thinkgraphChatconversations: {
      Item: ThinkgraphChatconversation
      FormData: ThinkgraphChatconversationFormData
      NewItem: NewThinkgraphChatconversation
    }
    thinkgraphDecisions: {
      Item: ThinkgraphDecision
      FormData: ThinkgraphDecisionFormData
      NewItem: NewThinkgraphDecision
    }
    thinkgraphGraphs: {
      Item: ThinkgraphGraph
      FormData: ThinkgraphGraphFormData
      NewItem: NewThinkgraphGraph
    }
    thinkgraphInjectrequests: {
      Item: ThinkgraphInjectrequest
      FormData: ThinkgraphInjectrequestFormData
      NewItem: NewThinkgraphInjectrequest
    }
    thinkgraphNodes: {
      Item: ThinkgraphNode
      FormData: ThinkgraphNodeFormData
      NewItem: NewThinkgraphNode
    }
  }
}

export {}
