<!--
  @crouton-generated
  @collection injectrequests
  @layer thinkgraph
  @generated 2026-03-19

  ## AI Context
  - List component for injectrequests collection
  - Collection name: thinkgraphInjectRequests
  - API endpoint: /api/teams/[id]/thinkgraph-injectrequests
  - Columns composable: useThinkgraphInjectRequests()
  - Column fields: nodeId, fromUserId, content, status

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="thinkgraphInjectRequests"
    :columns="columns"
    :rows="injectrequests || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="ThinkgraphInjectRequests"
        :collection="'thinkgraphInjectRequests'"
        createButton
      />
    </template>
    <template #nodeId-cell="{ row }">
      <CroutonItemCardMini
        v-if="row.original.nodeId"
        :id="row.original.nodeId"
        collection="thinkgraphNodes"
      />
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import useThinkgraphInjectRequests from '../composables/useThinkgraphInjectRequests'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { columns } = useThinkgraphInjectRequests()

const { items: injectRequests, pending } = await useCollectionQuery(
  'thinkgraphInjectRequests'
)

</script>