/**
 * @crouton-generated
 * @collection tags
 * @layer playground
 * @generated 2025-12-18
 *
 * ## AI Context
 * - Main interface: PlaygroundTag
 * - Form data type: PlaygroundTagFormData
 * - New item type: NewPlaygroundTag
 * - Form props: PlaygroundTagFormProps
 * - Fields: id, name, slug, color, order
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @friendlyinternet/nuxt-crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { playgroundTagSchema } from './app/composables/usePlaygroundTags'

export interface PlaygroundTag {
  id: string
  teamId: string
  owner: string
  name: string
  slug?: string
  color?: string
  order?: number
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type PlaygroundTagFormData = z.infer<typeof playgroundTagSchema>
export type NewPlaygroundTag = Omit<PlaygroundTag, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'>

// Props type for the Form component
export interface PlaygroundTagFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: PlaygroundTag | Record<string, never> // PlaygroundTag for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}