/**
 * @crouton-generated
 * @collection members
 * @layer bookingtest3
 * @generated 2026-02-25
 *
 * ## AI Context
 * - Main interface: Bookingtest3Member
 * - Form data type: Bookingtest3MemberFormData
 * - New item type: NewBookingtest3Member
 * - Form props: Bookingtest3MemberFormProps
 * - Fields: display, fields
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { bookingtest3MemberSchema } from './app/composables/useBookingtest3Members'

export interface Bookingtest3Member {
  id: string
  teamId: string
  owner: string
  display?: string
  fields?: string
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type Bookingtest3MemberFormData = z.infer<typeof bookingtest3MemberSchema>
export type NewBookingtest3Member = Omit<Bookingtest3Member, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'>

// Props type for the Form component
export interface Bookingtest3MemberFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: Bookingtest3Member | Record<string, never> // Bookingtest3Member for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}