CREATE TABLE `triage_accounts` (
	`id` text PRIMARY KEY NOT NULL,
	`teamId` text NOT NULL,
	`owner` text NOT NULL,
	`order` integer NOT NULL,
	`provider` text NOT NULL,
	`label` text NOT NULL,
	`providerAccountId` text NOT NULL,
	`accessToken` text NOT NULL,
	`accessTokenHint` text,
	`refreshToken` text,
	`tokenExpiresAt` integer,
	`scopes` text,
	`providerMetadata` text,
	`status` text NOT NULL,
	`lastVerifiedAt` integer,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL,
	`createdBy` text NOT NULL,
	`updatedBy` text NOT NULL
);
