/**
 * @crouton-generated
 * Collection Type Registry
 *
 * This file is auto-generated by @friendlyinternet/nuxt-crouton-cli
 * Run `crouton sync-types` to regenerate after adding collections.
 *
 * Generated: 2025-12-25
 *
 * ## How This Works
 * This file augments the CollectionTypeMap interface from @crouton/types.
 * When you use useCollectionQuery('blogPosts'), TypeScript automatically
 * knows the return type is BlogPost[] without requiring explicit generics.
 *
 * ## Registered Collections
 * - salesCategories: SalesCategory
 * - salesClients: SalesClient
 * - salesEvents: SalesEvent
 * - salesEventsettings: SalesEventsetting
 * - salesLocations: SalesLocation
 * - salesOrderitems: SalesOrderitem
 * - salesOrders: SalesOrder
 * - salesPrinters: SalesPrinter
 * - salesPrintqueues: SalesPrintqueue
 * - salesProducts: SalesProduct
 */

import type { SalesCategory, SalesCategoryFormData, NewSalesCategory } from './layers/sales/collections/categories/types'
import type { SalesClient, SalesClientFormData, NewSalesClient } from './layers/sales/collections/clients/types'
import type { SalesEvent, SalesEventFormData, NewSalesEvent } from './layers/sales/collections/events/types'
import type { SalesEventsetting, SalesEventsettingFormData, NewSalesEventsetting } from './layers/sales/collections/eventsettings/types'
import type { SalesLocation, SalesLocationFormData, NewSalesLocation } from './layers/sales/collections/locations/types'
import type { SalesOrderitem, SalesOrderitemFormData, NewSalesOrderitem } from './layers/sales/collections/orderitems/types'
import type { SalesOrder, SalesOrderFormData, NewSalesOrder } from './layers/sales/collections/orders/types'
import type { SalesPrinter, SalesPrinterFormData, NewSalesPrinter } from './layers/sales/collections/printers/types'
import type { SalesPrintqueue, SalesPrintqueueFormData, NewSalesPrintqueue } from './layers/sales/collections/printqueues/types'
import type { SalesProduct, SalesProductFormData, NewSalesProduct } from './layers/sales/collections/products/types'

declare module '#crouton/types' {
  interface CollectionTypeMap {
    salesCategories: {
      Item: SalesCategory
      FormData: SalesCategoryFormData
      NewItem: NewSalesCategory
    }
    salesClients: {
      Item: SalesClient
      FormData: SalesClientFormData
      NewItem: NewSalesClient
    }
    salesEvents: {
      Item: SalesEvent
      FormData: SalesEventFormData
      NewItem: NewSalesEvent
    }
    salesEventsettings: {
      Item: SalesEventsetting
      FormData: SalesEventsettingFormData
      NewItem: NewSalesEventsetting
    }
    salesLocations: {
      Item: SalesLocation
      FormData: SalesLocationFormData
      NewItem: NewSalesLocation
    }
    salesOrderitems: {
      Item: SalesOrderitem
      FormData: SalesOrderitemFormData
      NewItem: NewSalesOrderitem
    }
    salesOrders: {
      Item: SalesOrder
      FormData: SalesOrderFormData
      NewItem: NewSalesOrder
    }
    salesPrinters: {
      Item: SalesPrinter
      FormData: SalesPrinterFormData
      NewItem: NewSalesPrinter
    }
    salesPrintqueues: {
      Item: SalesPrintqueue
      FormData: SalesPrintqueueFormData
      NewItem: NewSalesPrintqueue
    }
    salesProducts: {
      Item: SalesProduct
      FormData: SalesProductFormData
      NewItem: NewSalesProduct
    }
  }
}

export {}
