/**
 * @crouton-generated
 * @collection orders
 * @layer sales
 * @generated 2025-12-25
 *
 * ## AI Context
 * - Composable: useSalesOrders
 * - Collection name: salesOrders
 * - API endpoint: /api/teams/[id]/sales-orders
 * - Form component: SalesOrdersForm
 * - List component: SalesOrdersList
 * - Fields: id, eventId, clientId, clientName, eventOrderNumber, overallRemarks, isPersonnel, status
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @friendlyinternet/nuxt-crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

// Schema exported separately - Zod 4 schemas cannot survive deep cloning
// Keep schema outside of objects that might be serialized/cloned during SSR
export const salesOrderSchema = z.object({
  eventId: z.string().min(1, 'eventId is required'),
  clientId: z.string().optional(),
  clientName: z.string().optional(),
  eventOrderNumber: z.string().optional(),
  overallRemarks: z.string().optional(),
  isPersonnel: z.boolean().optional(),
  status: z.string().min(1, 'status is required')
})

export const salesOrdersColumns = [
  { accessorKey: 'id', header: 'Id' },
  { accessorKey: 'eventId', header: 'EventId' },
  { accessorKey: 'clientId', header: 'ClientId' },
  { accessorKey: 'clientName', header: 'ClientName' },
  { accessorKey: 'eventOrderNumber', header: 'EventOrderNumber' },
  { accessorKey: 'overallRemarks', header: 'OverallRemarks' },
  { accessorKey: 'isPersonnel', header: 'IsPersonnel' },
  { accessorKey: 'status', header: 'Status' }
]

// Config object WITHOUT schema - safe for SSR serialization
const _salesOrdersConfig = {
  name: 'salesOrders',
  layer: 'sales',
  apiPath: 'sales-orders',
  componentName: 'SalesOrdersForm',
  defaultValues: {
    eventId: '',
    clientId: '',
    clientName: '',
    eventOrderNumber: '',
    overallRemarks: '',
    isPersonnel: false,
    status: ''
  },
  columns: salesOrdersColumns,
}

// Add schema as non-enumerable property so klona skips it during cloning
Object.defineProperty(_salesOrdersConfig, 'schema', {
  value: salesOrderSchema,
  enumerable: false,
  configurable: false,
  writable: false
})

export const salesOrdersConfig = _salesOrdersConfig as typeof _salesOrdersConfig & { schema: typeof salesOrderSchema }

export const useSalesOrders = () => salesOrdersConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: salesOrdersConfig.defaultValues,
    schema: salesOrderSchema,
    columns: salesOrdersConfig.columns,
    collection: salesOrdersConfig.name
  }
}