/**
 * @crouton-generated
 * @collection categories
 * @layer playground
 * @generated 2025-12-19
 *
 * ## AI Context
 * - Composable: usePlaygroundCategories
 * - Collection name: playgroundCategories
 * - API endpoint: /api/teams/[id]/playground-categories
 * - Form component: PlaygroundCategoriesForm
 * - List component: PlaygroundCategoriesList
 * - Fields: id, name, description, icon, color
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

// Schema exported separately - Zod 4 schemas cannot survive deep cloning
// Keep schema outside of objects that might be serialized/cloned during SSR
export const playgroundCategorieSchema = z.object({
  icon: z.string().optional(),
  color: z.string().optional(),
  name: z.string().optional(),
  description: z.string().optional(),
  parentId: z.string().nullable().optional(),
  translations: z.record(
    z.string(),
    z.object({
      name: z.string().min(1, 'Name is required'),
      description: z.string().optional()
    })
  ).refine(
    (translations) => translations.en && translations.en.name,
    { message: 'English translations for name are required' }
  )
})

export const playgroundCategoriesColumns = [
  { accessorKey: 'id', header: 'Id' },
  { accessorKey: 'name', header: 'Name' },
  { accessorKey: 'description', header: 'Description' },
  { accessorKey: 'icon', header: 'Icon' },
  { accessorKey: 'color', header: 'Color' },
  { accessorKey: 'translations', header: 'Translations' }
]

// Config object WITHOUT schema - safe for SSR serialization
const _playgroundCategoriesConfig = {
  name: 'playgroundCategories',
  layer: 'playground',
  apiPath: 'playground-categories',
  componentName: 'PlaygroundCategoriesForm',
  defaultValues: {
    name: '',
    description: '',
    icon: '',
    color: '',
    parentId: null,
    translations: {}
  },
  columns: playgroundCategoriesColumns,
  hierarchy: {
    enabled: true,
    parentField: 'parentId',
    pathField: 'path',
    depthField: 'depth',
    orderField: 'order'
  },
}

// Add schema as non-enumerable property so klona skips it during cloning
Object.defineProperty(_playgroundCategoriesConfig, 'schema', {
  value: playgroundCategorieSchema,
  enumerable: false,
  configurable: false,
  writable: false
})

export const playgroundCategoriesConfig = _playgroundCategoriesConfig as typeof _playgroundCategoriesConfig & { schema: typeof playgroundCategorieSchema }

export const usePlaygroundCategories = () => playgroundCategoriesConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: playgroundCategoriesConfig.defaultValues,
    schema: playgroundCategorieSchema,
    columns: playgroundCategoriesConfig.columns,
    collection: playgroundCategoriesConfig.name
  }
}